buildkite/elastic-ci-stack-for-aws

.gitignore, Makefile, README.md, build/cloudformation.json, create-stack.sh
This ditches the cfoo dependency if you aren't developing the stack definition.
=> Add the generated json version of the cfn tpl

Makefile, build/cloudformation.json, buildkite-elastic.yml
This creates a VPC and Subnets if none are provided.
=> Optionally create a dedicated VPC

build/cloudformation.json, buildkite-elastic.yml, create-stack.sh, mappings.yml
This changes the default agents to 1.9
=> Docker 1.9

packer/scripts/install-buildkite.sh
This will be done for us in the new buildkite-agent 2.1.5 stable package.
/cc @lox
=> Make upstart workaround conditional

packer/conf/hooks/environment, packer/conf/hooks/pre-command, packer/scripts/install-docker.sh
This also unsets the docker auth vars so that they aren't exposed to the command
=> Add back support for DOCKER_HUB_AUTH

templates/buildkite-elastic.yml
Adds an SNS topic with autoscale notifications. Allows for integration into slack/email, etc
=> Auto scale notifications

packer/scripts/install-docker.sh
Let's you use version 2 of the docker-compose.yml file https://docs.docker.com/compose/compose-file/#version-2
=> bump docker-compose version

templates/buildkite-elastic.yml
Group up the CloudFormation parameters to make the form a little more approachable.
=> CloudFormation parameter groups

packer/conf/buildkite-agent/hooks/environment
Let's see if this solves the forever hang in environment setup, or at least makes it more obvious what's going on.
=> Make sure docker is awake before asking it questions

packer/conf/buildkite-agent/scripts/buildkite-agent-lifecycled-handler
Reverts buildkite/elastic-ci-stack-for-aws#101
=> Revert "Have the lifecycled handler script look for just the build agent it is trying to shut down."

packer/conf/docker/docker.conf, packer/conf/docker/init.d/docker, packer/scripts/install-docker.sh
Bump to [Docker 1.12.1](https://github.com/docker/docker/releases/tag/v1.12.1)
=> Docker 1.12.1

templates/buildkite-elastic.yml
Looks like I broke `UseSpecifiedIamPolicies`. This will fix #173.
=> Nested if to fix #173

packer/conf/buildkite-agent/hooks/environment
This cleans up the SSH key checks and env loading by iterating over a set of possible keys. Makes it much easier to reason about and add consistent error checking.
=> Cleanup ssh key check and env loading

README.md
it was creating an invalid formatting of the readme.
=> removed uneeded ```

README.md
=> documented global env file

packer/conf/buildkite-agent/hooks/environment
Fix the breakage caused in https://github.com/buildkite/elastic-ci-stack-for-aws/commit/69d82cbc0d2c33e7cedc07dd96e882c045ffee68.
Apologies @holmesjr!
=> Fix previous merge that overwrote s3_exists

README.md, packer/conf/buildkite-agent/hooks/environment, packer/conf/buildkite-agent/hooks/pre-command
Makes the stack default KMS for all the secrets bucket. Closes #160.
=> Default to KMS for secrets

.buildkite/steps/test.sh, Makefile, templates/description.yml
This provides a description for the stack that includes a version number, which makes it easier to determine what stack version you are running.
=> Version in stack description

templates/buildkite-elastic.yml
=> Allow bootstrap script to come from S3 as well as web.

README.md, templates/autoscale.yml, templates/buildkite-elastic.yml, templates/metrics.yml
Note that this entirely replaces the substack, which makes things less confusing. It also costs less.
=> Use new lambda function for metrics stack

packer/buildkite-ami.json, packer/scripts/install-awslogs.sh, packer/scripts/install-docker.sh
Updating things to their most recent versions.
=> Bump amazon linux, docker and docker-compose versions

.buildkite/pipeline.sh, packer/conf/bin/bk-install-elastic-stack.sh, packer/scripts/install-utils.sh, tests/agent.bats, tests/aws.bats, tests/docker.bats
```bash
$ /usr/local/bin/bats --pretty tests
✓ Check buildkite-agent-1 is running
✓ Check docker is running
2 tests, 0 failures
```
=> Add some basic bats test

packer/conf/bin/bk-install-elastic-stack.sh, packer/scripts/install-utils.sh, templates/buildkite-elastic.yml
This uses bash traps to record the last line of the logs as the reason for stack failure.
=> Capture stack failure reason in install script

templates/buildkite-elastic.yml, templates/metrics.yml
Also, manually tested and seems to work fine
=> Remove the custom lambda parameters altogether

packer/conf/docker/docker.conf
See https://github.com/docker/docker/issues/22673 for more details.
/cc @toolmantim
=> Force native cgo resolver for docker

README.md, packer/conf/docker/cron.daily/docker-gc, packer/conf/docker/init.d/docker, packer/scripts/install-docker.sh, tests/docker.bats
This moves to the newest docker 1.13.1, replaces docker-gc with the new system commands and also updates docker-compose.
=> Docker 1.13.1

.buildkite/steps/publish.sh
=> Publish to eu-west-2 (London)

.buildkite/pipeline.sh, .buildkite/steps/lint.sh, packer/conf/buildkite-agent/hooks/environment, packer/scripts/install-utils.sh
This adds a linting check step for all shell scripts in the repo.
=> Add shellcheck linting for shell scripts

templates/outputs.yml
I use terraform wrapped around this cfn template, and would like to pull out the ASG name by using the cloudformation data source.
I have created a new file on the thought that people might like other output values and that this list my grow.
=> Add ASG Name output.

packer/conf/docker/cron.daily/docker-gc
fix bad flag https://github.com/buildkite/elastic-ci-stack-for-aws/issues/252
=> fix_for_#252

templates/buildkite-elastic.yml
See https://github.com/buildkite/elastic-ci-stack-for-aws/pull/270#issuecomment-293740743
=> Remove DesiredCapacity entirely

README.md, templates/buildkite-elastic.yml
This creates a secrets bucket if none is provided. This bucket will be left in place when the stack is deleted.
=> Create the secrets bucket if left blank

README.md, packer/buildkite-ami.json, packer/scripts/install-docker.sh
Docker 17.04.0-ce, Docker-compose 1.12.0 and Amazon Linux 2017.03.
=> Bump docker, docker-compose and amazon linux

templates/buildkite-elastic.yml
Swap from rolling updates to group replacement. See http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html
=> Spin up new ASG and replace on update

packer/scripts/install-utils.sh
=> Update the version of awscli on the host

Makefile, generate.js, package.json, templates/buildkite-elastic.yml
Fixes https://github.com/buildkite/elastic-ci-stack-for-aws/issues/282
=> Set the correct env var when secrets bucket is managed

README.md
=> Improve documentation for uploading env files to s3

README.md, packer/buildkite-ami.json
See https://aws.amazon.com/security/security-bulletins/AWS-2017-007/
=> Update to latest Amazon Linux 2017.03.1

packer/conf/buildkite-agent/hooks/pre-command, packer/scripts/install-docker.sh
This should fix the issue on master where the ECR plugin is failing.
=> Replace ecr plugin with credential helper

.buildkite/steps/cleanup.sh, README.md, packer/scripts/install-docker.sh
=> Docker 17.06

.buildkite/steps/publish.sh
=> Publish a latest template with the stable release (Port of #327)

packer/conf/buildkite-agent/hooks/pre-exit
This should fix an issue with the secrets plugin, the stable agent and git-credentials.
=> Update s3 secrets plugin

packer/conf/lifecycled/upstart/lifecycled.conf, templates/buildkite-elastic.yml
=> Fix lifecycled thrashing

packer/conf/bin/bk-install-elastic-stack.sh, templates/buildkite-elastic.yml
=> Add a BuildkiteAgentTags parameter for extra agent tags

packer/scripts/install-docker.sh
Hoping this will also fix #381.
=> Install docker 17.12.1-ce-rc2 to fix moby/moby#36173

packer/conf/buildkite-agent/hooks/environment
The pgrep was incorrectly masking these
=> Show docker logs if docker isn't running

packer/conf/bin/bk-install-elastic-stack.sh
Currently if the stack is updated and there is an error, the error will be silently discarded. This marks the instance as unhealthy and it will be cycled out.
=> Mark instances unhealthy if the update fails

packer/scripts/install-docker.sh
This claims to include containerd 1.0.1 which fixes https://github.com/moby/moby/issues/36002
=> Update docker to stable 17.12.1-ce

packer/conf/bin/bk-install-elastic-stack.sh, templates/buildkite-elastic.yml
This allows agent experiments to be enabled.
=> Support enabling agent experiments

packer/scripts/install-docker.sh, tests/cron.bats
=> #420: move cron jobs to run hourly

templates/outputs.yml
See https://github.com/buildkite/elastic-ci-stack-for-aws/pull/434#issuecomment-395685918
=> Output InstanceRoleName

templates/buildkite-elastic.yml
=> Default BuildkiteAgentRelease to stable (4.x)

packer/scripts/install-utils.sh
=> Update to the very latest aws-cli

packer/scripts/install-utils.sh
This should update yum packages on the AMI which should speed up instance boot times.
=> Update AMI to latest packages

.buildkite/steps/cleanup.sh
The testing process leaves a lot of s3 buckets around and we frequently hit the 100 bucket limit. This makes cleanup more incremental.
=> Remove secrets and logging bucket after testing

templates/aws-stack.yml
=> Remove the dash in description to be consistent with v3

Makefile, templates/aws-stack.yml
Currently the version is showing up as `dev`.
=> Show stack version in log output again

README.md, packer/scripts/install-docker.sh
This updates docker to 18.09.0 and docker-compose to 1.23.2.
=> Bump docker to 18.09.0

README.md, packer/scripts/install-buildkite-agent.sh
=> Bump agent to 3.8.2

README.md, packer/scripts/install-docker.sh
=> Bump docker to 18.09.1

templates/aws-stack.yml
=> Fix typo in CF setting

README.md, packer/scripts/install-buildkite-agent.sh
This is particularly because I'm interested in https://github.com/buildkite/agent/pull/931
=> Bump agent to 3.9.1

.buildkite/steps/test.sh, packer/conf/bin/bk-install-elastic-stack.sh, packer/conf/buildkite-agent/scripts/terminate-instance, templates/aws-stack.yml
Going to do one last 4.x release before removing metrics-based scaling.
=> Revert metrics scaling removal

.buildkite/steps/copy.sh, templates/aws-stack.yml
=> Update regions to include ca-central-1 and eu-west-3

templates/aws-stack.yml
Closes https://github.com/buildkite/elastic-ci-stack-for-aws/issues/564.
=> Bump agent scaler to support newer regions

templates/aws-stack.yml
Some how this passed validation in the first place!
=> Fix incorrect yaml syntax for spot instances

packer/windows/conf/bin/bk-install-elastic-stack.ps1
This allows end-users to reference the buildkite-agent user in their bootscript to handle things like setting file/folder permissions.
My exact use case is that I install additional standalone binaries and folders that I need the buildkite-agent user to have access to even if they are not in the Administrators group. 
=> Run the bootstrap script AFTER the buildkite-agent user is created

.buildkite/pipeline.yml
=> Use the new dag experiment for better parallel ordering

templates/aws-stack.yml
This PR:
- Adds the cost allocation tags to S3 buckets
=> Add correct cost tags to S3

README.md, packer/linux/scripts/install-docker.sh, packer/windows/scripts/install-docker.ps1
is there a way I can test this locally?
=> bump docker version to 19.03.0

packer/conf/bin/bk-configure-docker.sh
Fixes issue mentioned in https://github.com/buildkite/elastic-ci-stack-for-aws/issues/608#issuecomment-515712325
=> Docker experimental needs boolean not string

README.md, packer/scripts/install-buildkite-agent.sh, packer/scripts/install-docker.sh
=> Bump agent to v3.13.2, docker to 19.03 and compose to 1.24.1

packer/windows/conf/bin/bk-install-elastic-stack.ps1
Every now and then we still see Windows instances fail to finish the `bk-install-elastic-stack.ps1` script because it doesn't generate a random password that satisfies the system's password policy even though the loop retries ten times. The other problem with that loop code is that it runs `exit 1` if the loop fails to generate a good password but apparently that `exit 1` doesn't trigger the `trap on_error` like you would expect in a bash script so the powershell script simply exits without marking the system unhealthy. That leaves the auto scaler in a confused state because an ec2 instance is running without a running buildkite agent.
After reviewing the Windows password policy we came up with the code in this PR that simply ensures that the generated password will always satisfy the …
=> Ensure random windows password satisfies policy

README.md, packer/linux/scripts/install-docker.sh, packer/windows/scripts/install-docker.ps1
relates to https://github.com/moby/buildkit/issues/943
=> bump docker version to 19.03.2

packer/linux/scripts/install-buildkite-agent.sh
=> Fix broken cloud-final systemd config

README.md
I received an invalid JSON error when using the example. Slightly better developer experience for folks using this snippet if we update it.
=> README.md: Fix invalid IAM policy

packer/linux/scripts/install-buildkite-agent.sh, packer/linux/scripts/install-git-lfs.sh, packer/windows/scripts/install-buildkite-agent.ps1
Just some simple minor version bumps
=> Upgrade buildkite-agent and git lfs versions

README.md, packer/linux/scripts/install-docker.sh
=> bump docker-compose version to 1.25.1

templates/aws-stack.yml, templates/ssm-ami.yml
#691 but for the master branch
=> Add an optional ImageId SSM Parameter Path

packer/scripts/install-docker.sh
For #689. Updating these docker dependencies is part of our regular release cycle.
Docker release notes  (19.03.2 > 19.03.12) 
https://docs.docker.com/engine/release-notes/
Compose release notes (moving from 1.25.1 > 1.26.2)
https://docs.docker.com/compose/release-notes/
=> Update docker & docker-compose

.buildkite/pipeline.yml, .buildkite/steps/packer.sh, Makefile, packer/linux/buildkite-ami.json, packer/windows/buildkite-ami.json
Let's see how far we can bump packer before it breaks.
Fixes #704.
=> Upgrade packer

README.md, packer/linux/scripts/install-buildkite-agent.sh, packer/windows/scripts/install-buildkite-agent.ps1
=> Bump buildkite agent to v3.22.1

CHANGELOG.md, README.md, packer/scripts/install-buildkite-agent.sh
=> Bump buildkite agent to v3.22.1 (backport to stable-4-5)

README.md
=> Update Docker and Docker Compose versions in README

templates/aws-stack.yml
=> Bump Buildkite Agent Scaler to v1.0.1

.buildkite/steps/copy.sh, templates/aws-stack.yml
Support more regions for AMI and Lambda Scaler.
=> AMI and Lambda Scaler support more regions

packer/linux/conf/buildkite-agent/scripts/stop-agent-gracefully
We forgot to run shellcheck on PR #737. Oops.
=> address some shellcheck linking failures

README.md, packer/linux/scripts/install-buildkite-agent.sh, packer/windows/scripts/install-buildkite-agent.ps1
https://github.com/buildkite/agent/releases/tag/v3.26.0
=> Bump Buildkite Agent to v3.26.0

README.md
* Update the README to reflect the current log group configuration
=> Improve log group mention in README

README.md
=> Update documentation for log group reference

templates/aws-stack.yml
Resolves #812 
Ref: https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-su-create.html
=> Bugfix: bugfix/812/BuildkiteAgentTokenParameterStorePath validation (#812)

templates/aws-stack.yml
Reverts buildkite/elastic-ci-stack-for-aws#832
=> Revert "Revert "Remove IAM roles for SNS and SQS""

templates/aws-stack.yml
This took some time spelunking around your code to figure out which user the access applies to so I decided to clarify this in the params to simplify things for people who may run into the same issue.
=> Clarify which user the SSH access applies to

README.md
Waiting on/blocked by: https://github.com/buildkite/docs/pull/1077 (as we need that live for the new links to work)
=> Readme to docs

CHANGELOG.md
=> Add changelog for v5.4.0

packer/linux/scripts/install-buildkite-agent.sh, packer/windows/scripts/install-buildkite-agent.ps1
Depends on https://github.com/buildkite/agent/pull/1462
=> Update buildkite-agent to 3.31.0

templates/aws-stack.yml
Keeps the managed and non managed cases in lock step.
=> Merge the secrets bucket policies

templates/aws-stack.yml
1. Remove SSH keyname parameter and cleaned up a bunch of stuff.
2. Add minimal iam permissions to use SSM based access. Not using the `AmazonSSMManagedInstanceCore` as that will grant additional permission that are undesirable(`ssm:GetParameter` to `*` for example)
Fixes #620
=> Enable SSM access and disable SSH access.

.gitmodules
Update’s @nitrocode’s #840 with the latest pins.
=> Pin plugins

packer/linux/conf/bin/bk-install-elastic-stack.sh
=> Finish the git lfs install as the buildkite-agent user

CHANGELOG.md, RELEASE.md, packer/linux/conf/buildkite-agent/hooks/environment, templates/aws-stack.yml
Adds release instructions in repo.
=> Release v5.7.0

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
Some initial issue templates (thanks GitHub wizard) for bug reports and feature suggestions.
=> Update issue templates

packer/linux/conf/buildkite-agent/hooks/environment
Replace "---" log header prefix with "~~~"
=> Quieten Fixing permissions header log group

CHANGELOG.md
I'll merge this PR into master, and then cherry pick it on to the `release/5.8.2` branch, then release that.
=> Add changelog for 5.8.2

README.md, utils/log-collector
@moskyb This will add a handy little script that I demoed recently, which should help customers collect the logs we need in Support. If you want to chat about it or have suggestions or anything let me know 😄
=> add the log-collector to the utils folder and update README

utils/log-collector
Some minor changes to use tar instead of zip when creating the archive and some refactoring for readability
=> Update log collector

CHANGELOG.md
This prepares for a v5.10.0 release.
=> CHANGELOG for v5.10.0

CHANGELOG.md
This PR will release the new elastic stack version, 5.11.0.
=> Update changelog for v5.11.0

templates/aws-stack.yml
=> Add groupless params to groups

templates/aws-stack.yml
Bring in agent fixes from:
- https://github.com/buildkite/buildkite-agent-scaler/releases/tag/v1.3.2
=> build(AgentScaler): bring in scaler permission fix

CHANGELOG.md
This PR will cut a release for v5.11.1
=> Add changelog for 5.11.1

packer/linux/scripts/install-buildkite-agent.sh, packer/windows/scripts/install-buildkite-agent.ps1
See https://github.com/buildkite/agent/pull/1785 https://github.com/buildkite/agent/releases/tag/v3.39.1
=> Bump buildkite-agent to v3.39.1

packer/linux/buildkite-ami.json, packer/linux/scripts/upgrade-kernel.sh
=> Bump kernel to 5.15

templates/aws-stack.yml
This PR is being raised to allow the Event Schedule implementation made in the [buildkite-agent-scaler](https://github.com/buildkite/buildkite-agent-scaler/pull/93) to be used. The parameter changes were merged into release [v1.5.0](https://github.com/buildkite/buildkite-agent-scaler/pull/96) for the agent scaler. 
The Default of `1` was set to ensure the changes are backwards compatible with existing configurations.
=> Update event trigger schedule

templates/aws-stack.yml
Closes #1154 
Propagate CostAllocationTags to EBS volume to track EBS cost
=> Add UseCostAllocationTags to EBS volume

.buildkite/steps/launch.sh, goss.yaml, packer/linux/conf/bin/bk-configure-docker.sh, packer/linux/conf/bin/bk-mount-instance-storage.sh
=> Fix instance storage docker dir not created

packer/windows/buildkite-ami.json, packer/windows/scripts/install-docker.ps1
Cherry-picking this onto the stable-5-22 branch
=> Use windows server 2019 base image and docker ce

packer/linux/scripts/install-docker.sh
https://github.com/docker/compose/releases/tag/v2.20.3
=> Bump docker-compose to v2.20.3

CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.7.0...v6.7.1)
⚠️ This release fixes a medium-severity security vulnerability. We recommend upgrading to v6.7.1 or v5.22.5.
- Affected versions: All prior versions of Elastic CI Stack (except v5.22.5). v6.7.0 and v5.22.4 contained a partial fix.
- Impact: Privilege escalation to root on Linux agent instances
- Required privileges: Users that can run user-controlled commands on agents (e.g. by pushing a branch to a repo that triggers a build with those changes)
- Attack vector: A specially crafted build can abuse the `fix-buildkite-agent-builds-permissions` script to run commands as root on subsequent builds
- Fix: Improved input validation and file handling …
=> Bump changelog for v6.7.1 and v5.22.5

packer/linux/conf/bin/bk-mount-instance-storage.sh
=> Lazy-unmount /tmp before masking

packer/linux/scripts/install-buildkite-test-splitter.sh
=> Upgrade test-splitter-client to v0.7.3

packer/linux/conf/bin/bk-install-elastic-stack.sh, packer/windows/conf/bin/bk-install-elastic-stack.ps1, templates/aws-stack.yml
This change enables customers to override the public agent API endpoint.
=> This adds an optional override for agent API endpoint

packer/linux/scripts/install-utils.sh, packer/windows/scripts/install-utils.ps1
ec2-instance-connect is a very useful tool to securely connect to your EC2 instances without having to open a port to the public internet
=> Ec2 instance connect

templates/aws-stack.yml
Offer ability of using **experimental** Elastic CI Mode of the buildkite-agent-scaler (introduced in https://github.com/buildkite/buildkite-agent-scaler/pull/212/ ). 
___
Scaling issue here where there are more than one agent per instance. We currently have an open issue with how the number of agent instances are determined from our agent scaler before scaling out. It does not look into the actual live agents, rather, it checks on the configured `AgentsPerInstance`.
When the `ScaleInIdlePeriod` is met on an instance, this agent gets terminated. 
One instance might no longer have the 4 agents running, but now 3. Our agent scaler thinks since there is one instance still up, it assumes that there are 4 agents running.
Job dispatch delays, other issues related to job processing.
- Introduces …
=> feat: add graceful scale-in with experimental Elastic CI Mode

packer/linux/scripts/install-buildkite-agent.sh, packer/windows/scripts/install-buildkite-agent.ps1
https://github.com/buildkite/agent/releases/tag/v3.101.0
=> chore: update to agent v3.101.0

packer/linux/scripts/install-docker.sh
- Update docker compose to 2.38.2
- Update docker buildx to 0.26.1
=> Update docker compose and docker buildx

.buildkite/pipeline.yaml, packer/linux/base.pkr.hcl
Skip base image rebuild when plugins are updated.
=> Don't rebuild base image on plugin update

.buildkite/pipeline.yaml, .buildkite/steps/packer.sh, packer/linux/.trigger-base-build, packer/windows/.trigger-base-build
Remove hash-based logic in packer.sh in favor of `if_changed` mechanism provided by bk agent.
=> Simplify base AMI build logic
