- README.md
Otherwise:
> A client error (ValidationError) occurred when calling the CreateStack operation: Parameters: [NotificationEmail] do not exist in the template
> README.md: drop invalid NotificationEmail parameter.

- buildkite-elastic.yml
Ensures each EC2 instance is allocated a public IP address.  VPC may default to
not allocating public IP address.
> EC2 LaunchConfiguration AssociatePublicIpAddress: true

- buildkite-elastic.yml
Cloud Formation template has RootVolumeSize parameter, default remains 80 GB.
> RootVolumeSize parameter to override 80 GB default.

- packer/conf/docker.defaults
For whatever reason, the EC2 instances I'm working with don't receive responses to DNS queries against `8.8.8.8` and `8.8.4.4` (possibly all external DNS), but they work fine with AWS internal DNS as configured by default in the EC2 instance.
Docker by default will pass this working DNS into the containers, which is preferable to using an external resolver regardless of whether I can get `8.8.8.8` etc working.
> Docker uses default DNS, not Google's 8.8.8.8

- buildkite-elastic.yml
Switching from @lox's fork back to the official [buildkite/agent](https://hub.docker.com/r/buildkite/agent/) since https://github.com/buildkite/docker-buildkite-agent/pull/8 was merged.
> buildkite/agent not lox24/buildkite-agent; PR merged.

- packer/buildkite-ubuntu-15.04.json
According to [Ubuntu](https://wiki.ubuntu.com/LTS), 15.04 isn't an LTS release; 15.10 will be.
> Remove "LTS" from the AMI release tag

- buildkite-elastic.yml
Does what it says on the tin...
When running `make`, `cfoo` was complaining:
```
cfoo buildkite-elastic.yml mappings.yml > cloudformation.json
Failed to parse 'buildkite-elastic.yml':
Location: buildkite-elastic.yml line 190, column 5
Source: #!/bin/bash -eu
if [[ -n $DOCKER_HUB_AUTH ]] ; then
echo "~~~ Overwriting /root/.dockercfg"
echo $DOCKER_HUB_AUTH > /root/.dockercfg
fi
echo "~~~ Stopping existing docker containers"
if [[ \$(docker ps -q | wc -l) -gt 0 ]] ; then
docker stop \$(docker ps -q)
fi
Cause: Extra input after last repetition at line 2 char 10.
`- Expected one of [ESCAPED_DOLLAR, LONE_BACKSLASH, EL, TEXT] at line 2 char 10.
|- Expected "\\$", but got "$D" at line 2 char 10.
|- Expected "\\", but got "$" at line 2 char 10.
|- Failed to match sequence ('$(' (MAPPING / …
```
> Fix missing escaping on `$DOCKER_HUB_AUTH`

- buildkite-elastic.yml
Original link results in 301 permanent redirect to location of new link.
> Update s3 links due to permanent aws redirect

- build/cloudformation.json
- buildkite-elastic.yml
This adds back the previously removed ssh-agent instance, which is passed into the docker agent containers via `SSH_AUTH_SOCKET=/ssh-agent`.
> Add ssh-agent

- Makefile
Instructions in README.md failed:
```
$ make setup clean build
which bundle || gem install bundler --no-ri --no-rdoc
/Users/mbailey/.gem/ruby/2.2.0/bin/bundle
bundle install --path vendor/bundle
Fetching gem metadata from https://rubygems.org/..
Installing blankslate 2.1.2.4
Installing json 1.8.2
Installing parslet 1.5.0
Installing cfoo 0.0.5
Using bundler 1.7.12
Your bundle is complete!
It was installed into ./vendor/bundle
rm build/*
rm: build/*: No such file or directory
make: [clean] Error 1 (ignored)
mkdir -p build/
cfoo templates/buildkite-elastic.yml templates/mappings.yml templates/autoscale.yml templates/vpc.yml > build/aws-stack.json
/bin/sh: cfoo: command not found
make: *** [build/aws-stack.json] Error 127
```
> `bundle exec` ensures cfoo is found

- .buildkite/pipeline.yml
- README.md
- ci/cleanup.sh
- ci/steps.sh
- ci/test.sh
- packer/conf/hooks/environment
- packer/conf/hooks/pre-command
- templates/buildkite-elastic.yml
This change will require that secrets like the github key be encrypted at rest and decrypted per job with a project specific secret key.
See specifically the changes to the README.md.
> Add generic support for encrypted secrets stored on s3

- templates/autoscale.yml
- templates/buildkite-elastic.yml
This is the beginning of autoscaling based on the metrics provided by https://github.com/buildkite/buildkite-cloudwatch-metrics-publisher. 
You can specify an `AutoscaleStrategy` of `scheduledjobs` to get this new behaviour.
A future PR will likely bring in the Lambda functions directly into this stack so we have a one-stop-shop.
> Custom autoscaling based on Buildkite/ScheduledJobsCount

- packer/conf/hooks/environment
- packer/conf/hooks/post-command
- templates/buildkite-elastic.yml
Currently the README mentions that you can have an encrypted `env` file in your `SecretsBucket` which will be sourced and executed as part of the Buildkite environment hook.
> Support encrypted env file in secrets

- README.md
- packer/conf/hooks/environment
For easier backwards compatibility with stacks that didn't have encrypted keys in a provision bucket, this allows `BUILDKITE_SECRETS_KEY` to be empty.
It also provides some extra configuration points via ENV:
- `BUILDKITE_SECRETS_PREFIX` - This is a key prefix for the secrets bucket, by default it's the name of the pipeline
- `SSH_KEY_NAME` - The name of the key file (under the above prefix), defaults to `id_rsa_github`
This change also sets the default url for env and the ssh key file to be under the above `BUILDKITE_SECRETS_PREFIX`, which is a breaking change. You can set an empty secrets prefix to emulate previous behaviour.
> Allow empty secrets key

- Makefile
Currently the mappings are not deleted on `make clean`. This means that a `make clean create-stack` does not deploy the latest AMI.
> remove old mappings on clean

- packer/conf/buildkite-sudoers.conf
- packer/conf/hooks/environment
- packer/conf/scripts/fix-checkout-permissions
- packer/scripts/install-buildkite.sh
This PR adds a 
```
chown -R  buildkite-agent.buildkite-agent /var/lib/buildkite-agent/builds
```
before doing a checkout. 
This works around permission issues caused volume mounts leaving files owned by root in the checkout. 
I think the long term aim should be https://github.com/buildkite/buildkite-aws-stack/pull/32, as it fixes the underlying security issue and not just the symptom, but it needs more thorough testing.
> Chown the builds before checkout

- packer/conf/hooks/environment
- templates/autoscale.yml
The Autoscaler is currently terminating instances too aggressively, and can get into a state where it is alarming on both scale up and scale down. It is also terminating random instances which could be still running a build.
This changes the scale down rule to "0 jobs in the last 30 minutes" which works around both of these problems.
In the future it would be nice to add metrics for the number of idle agents and scale on that instead of the number of jobs.
> Scale down much less aggressively

- packer/scripts/install-docker.sh
This splits the docker 1.10.3 version bump out of https://github.com/buildkite/buildkite-aws-stack/pull/32
> Bump to docker 1.10

- ci/test.sh
- templates/buildkite-elastic.yml
- templates/metrics.yml
Rather than relying on an external stack for metrics gathering, this uses a nested stack if a `BuildkiteApiAccessToken` parameter is provided. Due to this, the default scaling strategy can be (the much better)  `scheduledjobs` vs `cpu`.
> Nested metrics stack

- Makefile
- README.md
- ci/steps.sh
- templates/buildkite-elastic.yml
This defaults the build instance cluster size to zero, but rapidly scales up when builds are scheduled.
> Default cluster size to zero, test autoscale in CI

- Makefile
- templates/buildkite-elastic.yml
- templates/metrics.yml
Previously the created VPC or specified existing subnets weren't being passed down to the metrics stack, leading to failures like #42.
> Pass subnets into metrics stack, fixes #42

- templates/autoscale.yml
- templates/buildkite-elastic.yml
This changes the agent name pattern to include the hostname `%stackname-%hostname-%n` and adds the correct docker version to the agent metadata, as well as ec2 instance tags.
> Better agent metadata

- templates/autoscale.yml
- templates/buildkite-elastic.yml
It has proven to be an ineffective strategy, so we have decided to remove it and simplify the autoscaling template and configuration params.
> Remove CPU based autoscaling

- packer/buildkite-ami.json
- packer/scripts/install-docker.sh
This updates the Docker version to 1.11.1 (from 1.10.3) and Docker Compose to 1.7.0 (from 1.6.2).
Docker 1.11.0 had some odd bug that would hang on some Docker operations, so it was skipped.
This also updates the base Amazon Linux AMI image to `ami-08111162`
> Docker 1.11.1 + Docker Compose 1.7.0

- README.md
- templates/buildkite-elastic.yml
This PR adds an optional `ArtifactsBucket` parameter (and associated policies) to the AWS stack.
This is nice for uploading artifacts outside of buildkite agents...
> Added option for ArtifactsBucket to CFN

- Makefile
- README.md
This PR adds a setup step to the default make target (in case bundle isn't installed, for example), and makes it possible to provide variables to switch AWS profiles and stack JSON publication bucket endpoints.
It also adds a target to update your stack.
I did remove the date stamping of stacks because it made updates difficult. We could cache the value locally or something... or make it a parameter?
> Tweaks to makefile for easier setup

- templates/autoscale.yml
- templates/buildkite-elastic.yml
As part of a discussion with @arthens and @sj26, we discovered that the stack scale up fires quicker than instances can actually launch. This slows down individual scale up events with a longer cooldown, but introduces a scale up and down increment so that the stack can still quickly scale up and scale down slowly.
> Support increments for scaling up and down

- templates/autoscale.yml
The scale up policy was configured to remove instances, and the scale down policy was configured to add them.
Introduced in 005807d6d348488aff5796af2b28adb45e23c3d6
> Fix inverted scaling policy

- templates/buildkite-elastic.yml
per [this conversation in Slack](https://buildkitechat.slack.com/archives/aws/p1462549147000735), you're likely missing this permission from the instances IAM policy.
> add missing RecordLifecycleActionHeartbeat permission for instances

- ci/packer.sh
The current packer build doesn't detect a new buildkite agent being available. This adds the latest agent release tag to the packer hash, so when there's a new tag we'll get a new AMI built and an updated stack JSON.
> Use the latest agent tag in the packer hash

- templates/autoscale.yml
- templates/buildkite-elastic.yml
This slows down the scale down to larger chunks of instances over 60 minute blocks.
> Scale down over 120 minutes

- templates/buildkite-elastic.yml
One instance at a time takes a very long time to cycle through 60-80 instances after a stack update.
I thought about making this a variable but I know you're trying to avoid too many knobs. I'm thinking 5 will at least work better as a starting point.
> bump UpdatePolicy MaxBatchSize from 1 to 5

- packer/scripts/install-buildkite.sh
These are no longer needed as of buildkite-agent v2.1.10. I tested it w/ a packer build and the stack, and it works AOK 👍
> Remove old agent install hacks

- .gitignore
- Makefile
- README.md
- ci/packer.sh
- ci/publish.sh
- ci/steps.sh
- ci/test.sh
- packer/scripts/install-buildkite.sh
- packer/scripts/install-docker.sh
- templates/mappings.yml.template
This changes how `templates/mappings.yml` is pulled down, previously in development it was easy to accidentally use the master AMIs and end up with a mixed result. This now allows for a easier workflow when on a branch. 
Now to create a stack locally, you need to either run `make download-mappings` first or `make build-ami`.
> Publish mappings.yml and aws-stack.json for branches

- templates/buildkite-elastic.yml
This changes the agent names to `<stack-name>-<instance-id>`, for example `buildkite-i-fd03537a`. Previously it used the hostname, which was the internal ip address.
This also adds a few more handy tags:
```
aws-buildkite-stack=true
aws:instance-id=i-fd03537a
aws:instance-type=t2.medium
aws:ami-id=ami-37618d5a
```
> Use instance-id in name and set more EC2-related tags

- templates/autoscale.yml
- templates/buildkite-elastic.yml
This scales down one agent when all agents were idle for 6 minutes, repeating every 2 minutes.  
The old logic would scale down 5 agents if there were no *waiting* for an hour, every 10 minutes.
The scheduled agents check is broken because during normal operation there often arent any scheduled builds, and during quiet (lower than usual, but still active) periods the cluster will scale to zero. This is made worse by the 10 minute cooldown after scaling, which prevents new machines from coming up.
We were seeing this scale down behaviour over lunch. To add insult to injury it means every docker cache is now totally cold, so builds after lunch can take 20+ minutes longer than they should.
A few tweaks to the scale down behaviour:
- much lower cooldown, scaling down would prevent scaling up …
> Scale down base on idle workers

- ci/publish.sh
- ci/steps.sh
This makes the stack available in all the regions that support the features we need (CloudFormation, ASGs, etc):
* us-west-1
* us-west-2
* eu-west-1
* eu-central-1
* ap-northeast-1
* ap-northeast-2
* ap-southeast-1
* ap-southeast-2
* sa-east-1
Fixes #44
> Publish AMIs to all regions

- ci/publish.sh
- packer/buildkite-ami.json
- packer/scripts/install-docker.sh
Updates Amazon Linux from 2016.03.1 https://aws.amazon.com/amazon-linux-ami/2016.03-release-notes/
Updates Docker from 1.11.1 to 1.11.2 https://github.com/docker/docker/releases/tag/v1.11.2
> Update Amazon Linux and Docker

- packer/conf/buildkite-agent/scripts/buildkite-agent-lifecycled-handler
- packer/scripts/install-buildkite-agent.sh
- templates/buildkite-elastic.yml
This patch adds in the ability to configure multiple buildkite-agents per EC2 instance. 
This is a configuration I've seen at 3 different companies now, although in those cases, they've either been manually configured, or taken something like the CF stack and then modified post-deployment.
Some people want to get better utilization of the hardware they are running BK on, especially in the case where bigger instances are often multi-core, but their builds may be single-threaded.
Was going to keep this addition as an 'internal' fork, but following on from discussion/help from @toolmantim on Slack, have made a PR.
> Install configurations for N number of buildkite agents per instance

- packer/conf/awslogs/awslogs.conf
- packer/scripts/install-buildkite-agent.sh
- templates/buildkite-elastic.yml
In #76 we broke CloudWatch buildkite-agent logs. This fixes them again.
> Fix agent log capturing for n agents

- README.md
- packer/conf/buildkite-agent/hooks/environment
There's nothing Github specific about this key at all, so let's not include it in the name
> Remove 'github' from the secrets bucket SSH key name

- packer/conf/docker/cron.daily/docker-gc
- packer/scripts/install-docker.sh
Only clean up docker images once a week.
Closes #78
> Only docker-gc images older than 7 days

- packer/conf/buildkite-agent/scripts/buildkite-agent-lifecycled-handler
- templates/buildkite-elastic.yml
@joffotron when auditing the param descriptions and grouping I realised we named this incorrectly to start with.
This renames it to `AgentsPerInstance` (and it now lives down in the instance config)
> Rename BuildkiteAgentsPerInstance to AgentsPerInstance

- templates/autoscale.yml
I've been trying to track down why we were getting scale down events whilst we still had running jobs, and it turns out the `BusyAgentCount` metric lags behind the jobs metrics quite a bit.
Recent updates the [metrics collector](https://github.com/buildkite/buildkite-cloudwatch-metrics-publisher) and [metrics stack](buildkite/buildkite-metrics#3) means we now have an `UnfinishedJobsCount` metric we can use to represent if there's any jobs being currently worked on.
This PR updates the scaledown so it's based on this new `UnfinishedJobsCount ` metric.
> Use UnfinishedJobs not BusyAgentCount

- packer/conf/buildkite-agent/scripts/buildkite-agent-lifecycled-handler
In #76 we introduced a bug where the lifecycled hook would instantly return, even if the buildkite-agent process had not finished gracefully shutting down. This caused the scale in event to continue, shutting down the machine mid-build… causing failing build jobs, and strange errors such as `could not connect to Docker host`
This fixes it by changing `until` to `while`.
Our tests unfortunately don't cover the the scale-in lifecycled hook.
Fixes #91
> Fix the lifecycled hook from instantly returning

- templates/buildkite-elastic.yml
Fixes #86 by restarting docker and checking it's available before starting the buildkite agent
> Restart docker in cloud-init process to prevent hangs

- packer/scripts/install-docker.sh
- templates/buildkite-elastic.yml
It appears #94 seems to have just made it worse. This removes the docker start from the packer image, only starts it on cloud init, and waits 10 seconds before trying to use the daemon
> Don't start docker in packer but in cloud init

- templates/buildkite-elastic.yml
Adds the ability for the user to specify zero or more managed IAM policies to be associated with the agent IAM role. Fixes #47.
> Allow additional managed policies for container instances

- packer/conf/buildkite-agent/scripts/buildkite-agent-lifecycled-handler
Otherwise, it gets stuck as other agents are still running, and matching
the pgrep
> Have the lifecycled handler script look for just the build agent it is trying to shut down.

- packer/conf/buildkite-agent/scripts/buildkite-agent-lifecycled-handler
This changes the `service stop` calls to all happen at once, and then do the waiting… so that agents 2, 3, 4 etc don't pick up new work whilst waiting for previous agents to stop.
Related to #101
> Send all the kills before waiting

- templates/buildkite-elastic.yml
This PR adds "Name" tags for buildkite agents such that their purpose is clear in the AWS console. It also adds tags for the agent version and queue to assist with managing multiple agent stacks.
> Name tags for instances

- .gitignore
- Makefile
- README.md
- extra_tags.json.example
- templates/metrics.yml
We have a company directive to add standardised tags to EC2 instances, including the Buildkite agent/metrics boxes. The existing `Role` and `Name` tags for the agent stack is 👌  but is missing for the metrics stack, plus we also require a few more for both boxes.
1. Tags the _metrics_ stack with appropriate Name/Role tag (follow on from https://github.com/buildkite/elastic-ci-stack-for-aws/pull/104 which only named the _agent_ boxes)
2. Adds ability for user-specified tags via `extra_tags.json`, with provided example.
Is `extra_tags.json` overkill? The other option is to have organisations document the incantation to create the new stack (`aws cloudformation create-stack ...`) and add the tags directive there. You'd lose the Makefile goodness, but then again you could just document `make …
> More tags for EC2 instances

- packer/buildkite-ami.json
- packer/scripts/install-utils.sh
These tools are used when integrating with AWS services. These should be
included given the AWS CLI is installed. This is a follow up from #113.
> Install zip/unzip

- templates/buildkite-elastic.yml
This provides a similar solution like UserData. Ideally this script
would be used to install supporting packages or run other one-time
configuration (such as setting AWS CLI profiles).
Users can provide this to customize the instances in some way _without_
having to worry about building a new AMI.
> Add optional BootstrapScriptUrl parameter

- templates/buildkite-elastic.yml
Provisioned IOPS only applies to io1 volumes, not gp2. Fixes #116
> Remove provisioned IOPS from the template

- templates/buildkite-elastic.yml
For new stack users, having a queue of `elastic` causes much confusion because they think the autoscaling gear is broken, but in fact they have run a build job but there's no matching agents. Also a queue name of `elastic` never fully gelled with me as a good default.
Just like all our other installers, we should probably just stick with `default` and let people do their own queue segregation as they want. It'd definitely help people new to the platform, and experienced users will know about queues anywho.
> Use queue of "default"

- packer/conf/buildkite-agent/hooks/environment
If you run multiple agents, or you run other daemons on your instance, just stopping all Docker containers is bad. This assumes that people will stop their Docker containers, and that Buildkite's default Docker gear behaves properly.
Closes #121
> Don't stop all other Docker containers

- templates/buildkite-elastic.yml
The [default ASG termination policy](http://docs.aws.amazon.com/autoscaling/latest/userguide/as-instance-termination.html) is to keep AZ's with equal number of instances, then oldest launch config, then closest to next instance hour.
For the stack we care more about the last two, and less about AZs.
Closes #108
> Don't use default termination policy

- templates/buildkite-elastic.yml
Updating the stack with a large number of instances sometimes fails, and then the rollback itself fails. This increases the `PauseTime` to 40 minutes to help this, with the downside that if an instance fails to come up during a rolling update, it's a long wait before you can do something about it. The upside is updates, and especially rollbacks, should have a better chance of succeeding.
The amount of time that AWS CloudFormation pauses after making a change to a batch of instances to give those instances time to start software applications. For example, you might need to specify PauseTime when scaling up the number of instances in an Auto Scaling group.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html
> If you enable the WaitOnResourceSignals …
> Increase rolling update PauseTime to 40 minutes

- templates/buildkite-elastic.yml
Updating the agent queue name, and a bunch of other keys, doesn't trigger an update of instances. This outputs those params into UserData so an update is triggered.
> Update requires: Some interruptions for Amazon EBS-backed instances.
> For EBS-backed instances, changing the UserData stops and then starts the instance; however, Amazon EC2 doesn't automatically run the updated UserData. To update configurations on your instance, use the cfn-hup helper script.
> Update requires: Replacement for instance store-backed instances.
Closes #84 
This doesn't fix updating the API key, that'll have to be done in the metrics stack.
> Trigger rolling updates for key params

- templates/buildkite-elastic.yml
This works nicely with S3 urls since they will give redirects if the region is not included. This change is not AWS specific. There is not a reason to skip redirects on these urls.
> Follow bootstrap URL redirects

- README.md
- packer/conf/buildkite-agent/hooks/environment
- packer/conf/buildkite-agent/hooks/pre-command
This removes `DOCKER_HUB_*` configs in favour of generic `DOCKER_LOGIN_*` environment variables, and adds support for AWS ECR login.
This also removes the `rm` of the Docker login creds, a file that is readable by all builds. This means that if one step performs a docker login, subsequent steps can read that file. Is this a problem? I'm not sure what the answer is for a world where more than one agent runs on the machine at once. The current implementation isn't much more secure at the moment in this situation anyway.
Closes #111
> Clean up docker login

- packer/scripts/install-docker.sh
Bump to [Docker Compose v1.8.0](https://github.com/docker/compose/releases/tag/1.8.0)
> Bump Docker Compose to 1.8.0

- packer/conf/awslogs/awslogs.conf
To make it easier to debug autoscaling/cfn signals (for example, for #130), this adds the cfn logs to CloudWatch
> Send cfn-signal/init logs to CloudWatch

- templates/buildkite-elastic.yml
This fixes a race condition where the agents may accept jobs before bootstrapping completes.
> Start agents after boostrapping

- .buildkite/steps/publish.sh
This will at least give people a URL to download old releases of the stack.
> Keep each master aws-stack.json

- packer/conf/buildkite-agent/hooks/pre-command
When using AWS_ECR_LOGIN_REGISTRY_IDS variable I'm getting an error
```
Unknown options: --registry_ids,[xxxxxxxxxxxxx]
```
The parameter used by aws-cli is "registry-ids", not "registry_ids"
> use correct parameter name for ECR login

- packer/conf/buildkite-agent/hooks/environment
- packer/conf/buildkite-agent/scripts/fix-buildkite-agent-builds-permissions
If we chmod the whole builds directory at the beginning of every build then we might chmod files which are currently in use by another agent's build.
The builds path has a first component which is the agent name. We can safely chmod recursively inside there. But we don't know this path, and don't expose it anywhere. And it's not as simple as `builds-path/agent-name` because the agent name is sanitized, but how it is sanitized depends on the agent version.
So we can grab the checkout path and work backwards. It's kinda hacky, but it works.
Like @tim suggested, it might be nice to extract the munging from the fix script into the environment hook and just pass in a prepared agent directory name and just make sure it has no slashes and isn't a traversal component in the script.
> Prevent chmod collisions in multi-agent per instance stacks

- packer/scripts/install-docker.sh
Docker released [docker-compose 1.8.1](https://github.com/docker/compose/releases/tag/1.8.1) a week ago and it has some bug fixes for some issues that we are seeing regularly.
> Bumping docker-compose to 1.8.1

- README.md
- packer/conf/buildkite-agent/hooks/environment
This will allow users to encrypt their sensitive files in `secretsBucket` with KMS instead of using a passphrase that needs to be pasted as environment variables in plain text in a pipeline. I have tested using the default `aws/s3` key.
> New ENV variable BUILDKITE_USE_KMS to allow the use of KMS when downloading from secrets bucket

- templates/buildkite-elastic.yml
Solved 2 problems:
1. Instead of using http(s), I can use the existing bucket to store authorized_users, e.g. use the secrets bucket
2. Merge with the local authorized_users instead of override, to allow login with the private key which used to create the EC2 instance.
> Added feature to copy authorized_users from specified s3 bucket path

- templates/autoscale.yml
It looks like the scale up logic is incorrect. We currently scale if even if there is an agent that is free but has yet to pick the job off the queue.
We inject metrics every 15 seconds by default into cloudwatch as per:
https://github.com/buildkite/buildkite-cloudwatch-metrics-publisher/blob/master/templates/cloudformation.yml#L45
Having an alarm of maximum over that 60 seconds will always trigger an alarm and a scale up event. 
What this will mean is that agents will spin up to max-agent size quickly even though those agents are in fact idle.
Changing the scale up to minimum will mean that we will only scale up if there is a scheduled job that hasnt been picked up by an agent because the agent is busy doing other builds.
> Correct scaling up logic 

- README.md
<( command ) is different and would be used in place of a filename.
> Fix example command line.

- templates/buildkite-elastic.yml
Add an awscli.conf that sets the region for cloudwatch logs. Without this, logs are always created in us-east-1
> Set a region for Cloudwatch Logs

- templates/buildkite-elastic.yml
- templates/metrics.yml
- templates/vpc.yml
us-west-1 only has two availability zones, so attempting to create a stack there fails. This drops back to two subnets, which should be deployable everywhere.
the exact error is:
```
Subnet2 Template error: Fn::Select cannot select nonexistent value at index 2
```
I'm probably being really dumb and there is some super obvious solution to this that I'm not seeing.
> Only use two subnets/azs

- packer/conf/buildkite-agent/hooks/environment
- templates/buildkite-elastic.yml
Some regions (like eu-central-1) need a region specified for s3 operations.
~~This addresses that as well as generally refactors how ssh keys are loaded and env files loaded. I think the loops make it clearer, but recognize it probably merits its own branch.~~
~~Currently this PR would close #158, and would overlap with #162.~~
(Going to move key loading changes to new PR)
> Handle v4 signature region secrets buckets

- README.md
- templates/buildkite-elastic.yml
At the minute it's a little bit tricky to get ECR integration working, this makes it more seamless by adding a parameter called `ElasticContainerRegistryAccess` that is either `none`, `readonly`, `poweruser` or `full`. If this is set, everything else will be setup for ECR to work out of the box. 
Remaining todo:
> Easier ECR integration

- README.md
We no longer recommend this as an option (it’s best not to confuse people!)
> Remove any mention of `BUILDKITE_SECRETS_KEY`

- packer/conf/buildkite-agent/hooks/environment
Related to #174, this deprecates the use of `BUILDKITE_SECRETS_KEY`
> Deprecate BUILDKITE_SECRETS_KEY

- README.md
- packer/conf/buildkite-agent/hooks/environment
Based on discussion in Slack, this updates the README to point to the releases page. This means we can apply some quality control to code that hits master prior to release and public consumption.
> Update docs to point to latest released stack

- templates/buildkite-elastic.yml
Looking at the generated CloudFormation it seems the AvailabilityZones parameter is only used if creating subnets.
> Change parameter help text

- .buildkite/steps/test.sh
- README.md
- templates/buildkite-elastic.yml
Another attempt at fixing #177. This breaks BC by replacing `ManagedPolicyArns` with `ManagedPolicyARN`. This is because there is no mechanism to merge a list with a single item in CloudFormation.
To mitigate this, I've added a predictable RoleName for the IAMRole (as suggested in #161).
> Fix issue #177

- packer/conf/buildkite-agent/hooks/environment
The signature for s3_copy() changed but the aws s3 cp command call didn't change to match. This fixes that issue. It also removes the broken bucket_region local var.
> Fix issue with s3 cp command source location in environment hook

- packer/conf/buildkite-agent/hooks/environment
- packer/conf/buildkite-agent/hooks/pre-command
Currently if all checks for a private ssh key fail, the checkout process kicks off anyway. This changes that so that it fails.
> Fail if a secret key isn't found but a secrets bucket is set

- packer/conf/buildkite-agent/scripts/fix-buildkite-agent-builds-permissions
Otherwise a script could alias chown to something that would be executed as root.
> Refer to chown by full path

- packer/conf/buildkite-agent/hooks/environment
It appears that the vars set to trigger the ECR login in `~/cfn-vars` aren't getting exported. This applies a bash option that exports any defined vars.
> Export env vars set in ~/cfn-vars

- templates/autoscale.yml
- templates/buildkite-elastic.yml
This allows MaxSize=MinSize clusters which don't scale. If this is the case, then the autoscaling resources aren't created.
> Skip creating autoscaling resources if not required

- packer/scripts/install-buildkite-agent.sh
- templates/buildkite-elastic.yml
Applies to correct names that are used externally for agent releases as per @toolmantim.
> Rename unstable->beta and experimental->edge, closes #197

- packer/scripts/install-docker.sh
This bug caused our machines to run out of space very quickly :)
> Set executable bit on docker-gc script

- packer/buildkite-ami.json
- packer/conf/bin/bk-fetch.sh
- packer/conf/bin/bk-install-elastic-stack.sh
- packer/scripts/install-utils.sh
- templates/buildkite-elastic.yml
As part of the move towards multiple ASG's in one stack, this moves configuration from the `LaunchConfiguration` into a script on the AMI. 
This should have effectively no impact on functionality, it's just moving code from cfn-init into a shell script.
> Move runtime installation from Cloudformation metadata to to Packer/AMI

- packer/conf/bin/bk-install-elastic-stack.sh
Discovered this issue whilst debugging an issue with @bjeanes
> Fix typo preventing bootstrap script from running

- templates/buildkite-elastic.yml
- templates/metrics.yml
Provides a workaround for #208 until we get lambda's published in all regions.
> Params for bucket and key for the metrics lambda

- templates/metrics.yml
The addition of the metrics lambda stack regressed the conditional metrics creation. This re-introduces it.
> Only create metrics lambda if required

- packer/scripts/install-utils.sh
Seems like more people are seeing issues with s3 requiring v4 signatures in certain circumstances. This defaults to v4. 
/cc @benschwarz
> Enable S3 v4 Signatures by Default

- templates/buildkite-elastic.yml
These were useful for dev, but are probably just confusing now.
> Remove custom metrics from the default param groups

- packer/conf/bin/bk-install-elastic-stack.sh
I was getting my logs coming through in us-east-1.
After I restarted the process they moved to the right region. I was wondering if its because awslogs may already have been started before this scripts run (perhaps a race condition?), so that starting it is a no op?
Instead I have changed it to restart, so that it will either start if stopped, or restart if started to pickup any config changes.
> Restart awslogs instead of just start for config changes.

- templates/buildkite-elastic.yml
Not sure if there is a reason not to allow this by default, but sometimes I have pipelines that create an artifact in once stage, and then need it in the next, so it would be good to be able to pull down something from the artifacts bucket during a step.
> Allow agent to get objects from its artifacts bucket.

- Makefile
- packer/conf/bin/bk-install-elastic-stack.sh
- templates/buildkite-elastic.yml
Rather than `buildkite-aws-stack=true`, this adds `buildkite-aws-stack=vX.X.X` to the agent metadata.
> Add a stack version to metadata

- .buildkite/steps/publish.sh
- README.md
Currently https://s3.amazonaws.com/buildkite-aws-stack/aws-stack.json refers to the latest master, this would change that to be the latest tagged release, which simplifies distribution.
> Replace top level template with latest tagged release

- templates/buildkite-elastic.yml
This avoids some edge cases on stack update.
> Keep it simple, allow zero instances during update

- templates/buildkite-elastic.yml
Although the template does not add any scheduled actions, this allows
people to add a scheduled action outside of the cloudformation and
still be able to update the stack.
My use case is wrapping this stack around terraform to create S3 buckets etc, and hopefully add a scheduled action after the fact.
I believe that this should be a no-op for most people if there are no scheduled actions so it should be safe to include.
> Suspend scheduled action processes on ASG rolling update.

- packer/conf/buildkite-agent/init.d/buildkite-agent
- packer/conf/docker/init.d/docker
This changes order of services to fix issue #256 so that docker starts up before buildkite-agent.
> Make sure that docker starts before launching the buildkite-agent

- Makefile
It seems the outputs from `template/outputs.yml` were never included when generating the aws-stack.json. This addresses the issue.
> Include outputs template when building stack

- templates/buildkite-elastic.yml
Allow the DesiredCapacity to be configured via parameter to prevent always scaling down to the MinSize during stack updates. (Issue #260)
> Allow DesiredCapacity to be configured via parameter

- packer/conf/terminationd/bin/terminationd
A few people have reported that they're hitting the AWS API rate limit for the `describe-auto-scaling-instances` call. This changes the poll wait from 15 seconds to 60 seconds, which should provide some temporary relief whilst we work on a more scaleable fix.
The downside to this change is that it might take an instance 45 seconds longer to detect whether it should shut down. In a worst-case situation this could mean that the buildkite-agent picks up a new job where it wouldn't have before, and then is delayed even further. But I think this tradeoff is acceptable until we work on terminationd alternative.
> Increase polling to 60 seconds

- .buildkite/pipeline.sh
- .buildkite/steps/publish.sh
This fixes a race condition where more commits are pushed to master before the publish step has started running. It also prevents multiple publish steps running at the same time, and it makes sure to copy the AMIs to all the regions for all builds of tags (not just the "latest tag").
What was the race condition? If there's two commits on master since the last tag, git describe will append some extra info to the output:
```
$ git describe origin/master --tags
v2.0.1-2-gf121d00
```
Adding --abbrev=0 removes the extra info git adds:
```
git describe origin/master --tags --abbrev=0
v2.0.1
```
So checking `$BUILDKITE_TAG == $(git describe origin/master --tags --abbrev=0)` will work, even if new commits are pushed to master in between the build starting and the publish step running.
> Fix release tag publishing race condition

- packer/conf/bin/bk-install-elastic-stack.sh
- packer/scripts/install-docker.sh
A current theory for issue #236 is that the restart is happening during dockers initialization, which causes corruption.
This moves the first docker start from packer to when the instance boots, as well as ensuring it happens before the agents are started.
> Start docker manually to avoid corrupting init

- packer/conf/bin/bk-install-elastic-stack.sh
- packer/conf/docker/docker.conf
- packer/conf/docker/init.d/docker
Hot fixes for #266 
The docker init script seems to randomly fail to start, although docker is actually starting correctly.
This also enables docker debug by default.
> Start docker manually

- README.md
- packer/conf/buildkite-agent/hooks/environment
This checks the secrets bucket for a `git-credentials` file to support git over https. 
The format of the file (from https://git-scm.com/docs/git-credential-store#_storage_format) is:
```
https://user:pass@example.com
```
> Download git-credentials files from secrets bucket

- templates/autoscale.yml
- templates/buildkite-elastic.yml
Based on discussion in slack, this adds the ability to tune the timeframe around which scale down occurs.
It also slightly increases both the scale up and down cooldown timers (60 seconds to 300 seconds), because I've been meaning to for ages. The current stack will scale up again before the new instance has even finished booting.
> Add a ScaleDownPeriod param to control scale-down timeframe

- templates/buildkite-elastic.yml
Seeing as this is the advice I tend to give in the slack channel anyway, default the agent to beta. :rocket:
> Default the agent to beta

- .buildkite/steps/test.sh
- templates/buildkite-elastic.yml
This fixes a bug where the permissions were incorrect for managed secrets bucket.
> Add PutObject permission for managed secrets bucket

- Makefile
- packer/buildkite-ami.json
- remove duplicate setting
- mount local `~/.aws` to packer container for aws credentials files
> remove duplicate setting

- packer/conf/buildkite-agent/hooks/environment
Let's set it like [the plugin does](https://github.com/buildkite-plugins/s3-secrets-buildkite-plugin/blob/master/hooks/environment#L10).
> TMPDIR is unbound in the environment hook

- packer/conf/buildkite-agent/hooks/environment
This allows for the secrets functionality to be entirely disabled. It backports `SECRETS_PLUGIN_ENABLED` like in the forthcoming 2.2.x series. 
You can then just set this in env and it will skip the secrets code.
> Backport SECRETS_PLUGIN_ENABLED for disabling secrets in 2.1.x

- .buildkite/steps/packer.sh
- packer/conf/bin/bk-install-elastic-stack.sh
- packer/scripts/install-buildkite-agent.sh
Currently the edge binary is installed to the AMI. This makes iterating on edge difficult. This change defers download and install for edge to the install / boot of the host.
This means it's possible to bump edge version by scaling down the stack and letting new instances be spun up.
> Download the edge binary on install / startup

- README.md
- packer/scripts/install-docker.sh
Docker 17.06 supports [multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/) in a single Dockerfile, which is a massive win for CI builds.
I haven't tested this version bump in any way, but I don't see any breaking changes between 17.05 and 17.06 in the announcement: https://blog.docker.com/2017/06/announcing-docker-17-06-community-edition-ce/
> Docker 17.06.0-ce, was 17.05.0-ce.

- README.md
- packer/scripts/install-docker.sh
Reverts buildkite/elastic-ci-stack-for-aws#307
There are some breaking changes around ecr-login that I would prefer not to deal with yet, and the URL is broken.
> Revert "Docker 17.06.0-ce, was 17.05.0-ce."

- packer/conf/buildkite-agent/hooks/pre-command
- packer/scripts/install-docker.sh
Reverts buildkite/elastic-ci-stack-for-aws#308
Wait until docker 17.06 lands for this, I have some concerns about docker-compose's usage of credential helpers.
> Revert "Replace ecr plugin with credential helper"

- templates/metrics.yml
This increases the metrics lambda timeout to 2 minutes and adds a new version with retry support. Should be non-controversial.
> Bump metrics version

- packer/conf/docker/cron.daily/docker-gc
Using system prune works better than the previous `docker-gc` but we found after 10 days the unused images were enough to fill our 80GB disk.
This prunes unused images as well as "dangling" images (the default) older than 4 hours.
NOTE: This can have a nasty side effect that images are not available for use by the docker build cache, which results in slower build times. We have multiple ways to work around this internally, but it may not be desirable for all users.
Having the build cache around "forever" (as long as the instance is around) can be rather convenient.
> Prevent unused images from filling up agent disk

- .buildkite/steps/lint.sh
- .buildkite/steps/publish.sh
- .buildkite/steps/test.sh
- README.md
- packer/conf/bin/bk-install-elastic-stack.sh
Currently release candidates are published to https://s3.amazonaws.com/buildkite-aws-stack/aws-stack.json, which has lead to some people opt-ing into release candidates without realizing it.
This change keeps the behaviour for https://s3.amazonaws.com/buildkite-aws-stack/aws-stack.json, but adds https://s3.amazonaws.com/buildkite-aws-stack/latest/aws-stack.json that refers to the latest release (excluding pre-releases).
> Publish a latest template with the stable release

- templates/buildkite-elastic.yml
`30 mins` is old description since there is `ScaleDownPeriod`.
> Fix incorrect description

- templates/buildkite-elastic.yml
Adds support for #318. So far not tested due to other issues.
Note that if set to true, the instance types available for use [will be limited](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#EBSEncryption_supported_instances).
> Add configuration option to enable EBS volume encryption.

- templates/vpc.yml
Fixes a bug raised by @pda where there is a race condition between the gateway creation and the default route. Something something eventual consistency.
> Add a dependency on the Gateway for the DefaultRoute

- templates/vpc.yml
Follow-up to https://github.com/buildkite/elastic-ci-stack-for-aws/pull/336
`DependsOn` is required for implicit dependencies that aren't represented by things like `Ref: Foo`. I think the only implicit dependency here is `RouteDefault` depending on `GatewayAttachment`; the dependency on the `Gateway` itself is explicit via `GatewayId: { Ref: Gateway }`, but that `Gateway` must be attached to the `Vpc` before the `Route` can be created, so there's an implicit dependency on `GatewayAttachment`.
See similar use-case in https://github.com/awslabs/ecs-refarch-cloudformation/blob/8a10c808/infrastructure/vpc.yaml#L137-L143
> VPC: fix explicit DependsOn: GatewayAttachment

- .buildkite/pipeline.yml
- docker-compose.unit-tests.yml
- packer/conf/buildkite-agent/hooks/environment
- packer/conf/buildkite-agent/scripts/fix-buildkite-agent-builds-permissions
- unit-tests/fix-buildkite-agent-builds-permissions.bats
Currently the [fix-buildkite-agent-builds-permissions](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/conf/buildkite-agent/scripts/fix-buildkite-agent-builds-permissions) script, that's run by our [environment hook](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/conf/buildkite-agent/hooks/environment), `chown`'s the agent’s entire builds directory on every job run. This means the chown operation gets slower every time a different pipeline is checked out onto disk.
This PR changes the permissions fixing script to `chown` only the running pipeline’s checkout dir (if it exists), rather than the entire builds dir. The permissions tests have also been moved from the comment in the bottom of the file into their own executable `.bats` tests.
> Optimize the permissions check script to only fix the current pipeline’s build dir

- packer/conf/awslogs/awslogs.conf
- packer/conf/bin/bk-install-elastic-stack.sh
As reported in #342, the CloudWatch log groups are currently quite roughly named, and not namespaced to Buildkite. If you’re using the stack in an existing AWS account this can create a bit of mess.
This PR namespaces everything under `/buildkite` and renames the groups to be consistent and a little more friendly.
Closes #342
> Namespace and rename the CloudWatch log groups

- templates/metrics.yml
This brings in a new buildkite-metrics version that respects our rate limiting and reduces the volume of metrics api requests.
> Update buildkite-metrics to v2.0.0

- templates/buildkite-elastic.yml
- templates/vpc.yml
The recent NetworkConfig parameter broke backwards compatibility with previous stacks. This fixes it.
> Allow clean update from earlier stack versions

- README.md
- packer/conf/buildkite-agent/hooks/pre-command
The docs mention `AWS_ECR_LOGIN_REGISTRY_IDS`, but we weren't mapping it through to the internal ECR plugin variable.
> Pass AWS_ECR_LOGIN_REGISTRY_IDS to ecr plugin

- packer/conf/bin/bk-check-disk-space.sh
- packer/conf/bin/bk-install-elastic-stack.sh
- packer/conf/buildkite-agent/hooks/environment
- packer/conf/docker/cron.hourly/docker-gc
- packer/conf/docker/cron.hourly/docker-low-disk-gc
- tests/cron.bats
It turns out the the output of `/etc/cron.daily/docker-gc` and `/etc/cron.daily/docker-low-disk-gc` wasn't getting output anywhere.
This PR appends that to the system log. Beyond that, it checks the system disk usage as part of each job.
The motivation for these changes are the issues customers have been having with instances running out of disk. Because these checks currently only happen daily, my theory is that the instances are running out of disk before the clean up can happen. Alternately, it's possible the scripts aren't running for some reason 🤷🏼‍♂️
/cc @maria-v
> Add logging for disk space issues

- packer/conf/bin/bk-check-disk-space.sh
- packer/conf/buildkite-agent/hooks/environment
- packer/conf/docker/cron.hourly/docker-low-disk-gc
This follows up on #373 and actually tries to clear disk up before a build if space is low. This should be a good balance between not always doing this, but not failing builds because we haven't been aggressive enough on disk cleaning.
> Clean up disk space in environment

- packer/conf/bin/bk-configure-docker.sh
- packer/conf/bin/bk-install-elastic-stack.sh
- packer/conf/buildkite-agent/hooks/environment
- templates/buildkite-elastic.yml
We frequently have folks running into an issue where their docker daemon is non-responsive on boot. Historically we saw this in #266, but continue to see it sporadically. 
This uses [cloud-init boothooks](https://cloudinit.readthedocs.io/en/latest/topics/format.html#cloud-boothook) to configure docker before it boots, which avoids the (suspected) race condition entirely. 
Given it also avoids a docker restart, it should make for faster boot times too.
> Use boothook to configure docker

- packer/conf/bin/bk-install-elastic-stack.sh
This causes an instance to fail it's initial boot if docker hasn't started in 10 seconds.
> Fail install if docker hasn't started

- packer/conf/bin/bk-install-elastic-stack.sh
- packer/scripts/install-buildkite-agent.sh
A simpler take on #399, this just removes the v2 bash bootstrap.
> Drop support for buildkite-agent v2, stable is 3.0.0

- templates/buildkite-elastic.yml
Adds two new configuration values (`BuildkiteBillingTagName` and `BuildkiteBillingTagValue`) that can be used to apply a Cost Allocation Tag to instances created by the ASG.
> Add support for billing tags

- templates/buildkite-elastic.yml
The addition of cost allocation tags in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/398 broke our tests because it needs to be activated per-account:
https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/activate-built-in-tags.html
I've added a `EnableCostAllocationTags` that defaults to `false`, and also renamed the parameters `CostAllocationTagName` and `CostAllocationTagValue`.
> Turn off cost allocation tags by default

- .buildkite/steps/test.sh
- README.md
- config.json.example
- templates/buildkite-elastic.yml
- templates/metrics.yml
Using the new private elastic stack metrics API that @sj26 created we can drop the requirement for a personal access token, allowing just an agent registration token. 
Hoping this will be a big win for teams that have to manage lots of personal access tokens just for elastic stacks.
> Use new Metrics API, drop requirement for org-slug and api-token 🎉

- templates/buildkite-elastic.yml
The current version of the stack names the IAM Role in the Instance Profile with ${AWS::StackName}-Role.
Theis results in an IAM Role with a role name like 'the-build-stack-xyzqwrpqr-Role' when the stack is generated by a process which does not fix the stack name (as happens if this template is used as a nested stack). This role name changes every time the stack is re-deployed or updated.
Having this unpredictable role name is problematic if you want the build agent to assume a role, as the 'Principal' of an IAM policy needs to be fixed.
My change allows the user the option to specify a role name if needed.
> Fix cfn stack instance profile name

- packer/conf/awslogs/awslogs.conf
- packer/scripts/install-lifecycled.sh
This introduces a simpler lifecycled upstart script which I'm hoping will allow for SQS queue cleanup on shutdown (#358).
> Update lifecycled to 2.0.1

- packer/conf/bin/bk-check-disk-space.sh
Initially tried 1M, but smaller instance sizes will only have about 600K in total. 250K seems like a reasonable compromise.
> Bump the minimum inodes to 250K to allow for big docker images

- templates/buildkite-elastic.yml
When bringing back `EnableDockerUserNamespaceRemap` in #410, we forgot to default to `true`. This fixes that.
> Default EnableDockerUserNamespaceRemap to true

- templates/outputs.yml
We allow Buildkite agents to assume other IAM roles for certain deployment/operational actions. The role to be assumed needs to include the role ARN within its assume role policy.
It would be great to thread a dependency between the stack and the assume policy document via the stack output.
We use the existing `AutoScalingGroupName` stack output to create/update scheduled actions on the ASG and would like to use the role name to aid in other resources creation.
> Set InstanceRoleName as stack template output

- packer/conf/bin/bk-check-disk-space.sh
Some people might use a RAM drive for docker to get better performance. By specifying the docker dir, we make sure we are checking for disk space in the right filesystem.
> Use the docker directory to check for disk space

- templates/outputs.yml
If the `InstanceRoleName` parameter (optional) is unset, the CloudFormation stack generates a name for you based on the stack name.
This commit updates the output to extract the name from the resource directly which accounts for both cases, and should be more reliable going forward.
Follow up to https://github.com/buildkite/elastic-ci-stack-for-aws/pull/421. Addresses https://github.com/buildkite/elastic-ci-stack-for-aws/pull/421#issuecomment-392137428
> Set InstanceRoleName output from IAMRole resource

- templates/outputs.yml
This is a follow on from https://github.com/buildkite/elastic-ci-stack-for-aws/pull/428.
@dblandin unfortunately IAMRole.RoleName doesn't exist, so we'll have to settle for the ARN.
> Unfortunately IAMRole.RoleName doesn't exist, so output ARN instead

- packer/conf/docker/docker.userns-remap.conf
- packer/conf/docker/subgid
- tests/docker.bats
This makes sure that the gid inside containers is mapped to the docker group on the host, so that if the docker socket is mounted in it can be accessed.
See https://www.jujens.eu/posts/en/2017/Jul/02/docker-userns-remap/#id2 for more context.
> Fixes permissions issues accessing docker socket

- packer/conf/bin/bk-check-disk-space.sh
> 432: use exit instead of return in bk-check-disk-space.sh script

- templates/buildkite-elastic.yml
This positions us to use the same config for an ASG as a SpotFleet. See https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-launch-templates-for-amazon-ec2-instances/ for some more context.
> Convert LaunchConfiguration to a LaunchTemplate

- templates/buildkite-elastic.yml
Reverts buildkite/elastic-ci-stack-for-aws#424, there isn't a backwards compatible way to use ASG's with Spot Instances and LaunchTemplates that I can find.
> Revert "Convert LaunchConfiguration to a LaunchTemplate"

- templates/buildkite-elastic.yml
This handles default vs non default VPC reference rules per
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html#cfn-ec2-security-group-ingress-groupid
This follows on from #444 which made the rule conditional.
> Reference security group by id rather than name

- packer/conf/buildkite-agent/hooks/pre-command
I believe the variable exported after reading `AWS_ECR_LOGIN_REGISTRY_IDS` isn't correct to configure the ecr login plugin. We're currently getting around this by explicitly setting `BUILDKITE_PLUGIN_ECR_ACCOUNT_IDS_0` in our stack, but thought it was worth trying to get fixed to configure this the documented way.
https://github.com/buildkite-plugins/ecr-buildkite-plugin/blob/3068b26de2eb43b8ae6ebf081b1f0626d018d8c0/hooks/pre-command#L58
Thanks!
> Set correct variable to pass to upstream ecr plugin

- packer/scripts/install-docker.sh
We've been having strange spurious docker failures. Let's try going back. 
Reverts buildkite/elastic-ci-stack-for-aws#455
> Revert "Bump docker to 18.03.1-ce and docker-compose to 1.22.0"

- README.md
- packer/conf/awslogs/awslogs.conf
I think this change makes sense. Let me know if I'm mistaken.
> Rename the log group name we are using for elastic-stack.log file so we are consistent

- README.md
- packer/buildkite-ami.json
Bump the stable release to the latest Amazon Linux
> Bump Amazon Linux to 2018.03

- templates/buildkite-elastic.yml
Currently the default is `beta` which is confusing, we use `stable` since 3.x
> Default BuildkiteAgentRelease to stable

- templates/buildkite-elastic.yml
When using the template, timeout value for autoscaling group->creation policy can now be customised. 
Default value is PT5M which sometimes blocks the deployment as the job it is running is too heavy and 5mins is not able to finish the ASG setup.
> Added Timeout as parameter so it can be passed from stack parameters.

- README.md
- packer/buildkite-ami.json
- packer/conf/awslogs/awslogs.conf
- packer/conf/bin/bk-install-elastic-stack.sh
- packer/conf/journald-cloudwatch-logs/journald-cloudwatch-logs.conf
- packer/conf/journald-cloudwatch-logs/journald-cloudwatch-logs.service
- packer/scripts/install-journald-cloudwatch-logs.sh
Since we swapped to Amazon Linux 2 (and systemd) lots of our logs go via `systemd`, which isn't supported by `awslogs`. This adds @sj26's fork of https://github.com/sj26/journald-cloudwatch-logs to copy the systemd journal to cloudwatch logs.
Closes #459
> Add journald cloudwatch logs

- README.md
Quite a few times on support I've wanted to link people to the docs telling them how to customise their agent (e.g. setting a Docker daemon option, or installing an extra CLI tool).
This adds a docs section showing people how to do that.
> Add docs for using the bootstrap script

- .buildkite/steps/packer.sh
- packer/conf/bin/bk-install-elastic-stack.sh
- packer/conf/journald-cloudwatch-logs/journald-cloudwatch-logs.conf
Currently systemd logs fail as `/buildkite/systemd` isn't created. This rolls back the group name to `/buildkite/system` which is what it was previously and also makes sure that group is created.
> Make sure /buildkite/system log group exists

- packer/conf/bin/bk-install-elastic-stack.sh
- templates/aws-stack.yml
This fixes #485.
See: https://github.com/buildkite/agent/pull/501 and https://buildkite.com/docs/agent/v3/configuration
> Support timestamp-lines

- packer/conf/bin/bk-configure-docker.sh
- packer/conf/docker/daemon.userns-remap.json
- packer/scripts/install-docker.sh
- templates/aws-stack.yml
This adds a flag for turning on Docker's experimental mode so that we can experiment with BuildKit (not confusing at all). 
This also reconciles how we set docker daemon parameters (now using jq).
> Add a EnableDockerExperimental param

- goss.yaml
- packer/conf/bin/bk-install-elastic-stack.sh
- packer/scripts/install-lifecycled.sh
It appears that lifecycled has been starting without its handler script in place. I believe this is because the daemon is currently set to start on boot and the handler script is only configured after boot.
The [latest lifecycled version 3.0.1](https://github.com/buildkite/lifecycled/releases/tag/v3.0.1) makes this parameter required.
> Only start lifecycled after install

- packer/conf/bin/bk-install-elastic-stack.sh
- packer/scripts/install-awslogs.sh
We recently upgraded our stacks to 4.0.1 and noticed that all our logs are being sent to us-east-1, despite the stacks being created in us-west-2. In a similar vein to #507, we should ensure that the awslogsd service is not started until the region is properly set via the `bk-install-elastic-stack.sh` script.
It looks like this was previously added in #225 but was accidentally removed in 4.0 during the switch to Amazon Linux 2/systemd.
> Ensure region is set before starting awslogsd

- packer/conf/buildkite-agent/systemd/buildkite-agent@.service
The agent handles the termination of the bootstrap. This was preventing the agent from gracefully terminating.
Closes #520.
> Prevent systemd from killing agent process group

- templates/aws-stack.yml
Expose the `AgentLifecycleTopic` name so that users can use utilities like Terraform to easily create custom integrations to supplement the Cloudwatch Alarms already provided by the ElasticStack.
Specifically, we want to be able to write custom alarms that can enforce additional scaling events outside of just the default alarms. 
> Expose AgentLifecycleTopic for programatic scaling

- packer/conf/buildkite-agent/systemd/buildkite-agent@.service
Turns out that systemd before 229 didn't support `infinity`, so we use `0` to disable the stop timeout.
> Older versions of systemd don't support infinity

- templates/aws-stack.yml
We removed `BuildkiteOrgSlug` when we introduced the new Agent Metrics API. The idea was to reduce the number of required parameters, but we also removed the piece of data that was needed to support multiple Buildkite Orgs per AWS account, as otherwise the metrics are disambiguated only by queue. 
This adds back `BuildkiteOrgSlug` with a default of `` and then adds an `Org` dimension to the metrics we publish to Cloudwatch.
Closes https://github.com/buildkite/elastic-ci-stack-for-aws/issues/452.
> Add Buildkite Org to Cloudwatch Metrics as a Dimension to support multiple orgs per AWS account

- README.md
- packer/conf/bin/bk-install-elastic-stack.sh
- packer/conf/buildkite-agent/scripts/mark-asg-unhealthy
- packer/conf/buildkite-agent/scripts/terminate-instance
- packer/scripts/install-buildkite-agent.sh
- templates/aws-stack.yml
This new setting will allow you to stop (and terminate) an instance after it has completed a job.
> Add new "TerminateInstanceAfterJob" configuration

- packer/conf/bin/bk-install-elastic-stack.sh
- templates/aws-stack.yml
Specify a comma separated list into `BuildkiteAdditionalSudoPermissions`
This allows users to easily extend which commands buildkite-agent can run using sudo. The setting can also be set to `ALL` as an escape hatch for those who want to run a super-privileged agent (though this is not recommended).
> Allow users to specify additional sudo permissions

- packer/conf/bin/bk-configure-docker.sh
There was a copy and paste error in #506 which meant that the `EnableDockerExperimental` param didn't work.
> Fix typo in docker experimental config

- packer/scripts/install-docker.sh
This addresses [CVE-2019-5736](https://access.redhat.com/security/cve/cve-2019-5736) https://aws.amazon.com/security/security-bulletins/AWS-2019-002/ 
Closes #531.
> Bump docker to 18.09.2

- packer/conf/bin/bk-install-elastic-stack.sh
- templates/aws-stack.yml
This is a bug affected the new terminate functionality in 4.1.0. 
If we do not reload the unit files, the new power-off.conf file gets ignored.
> Make sure we reload the systemd unit files

- templates/aws-stack.yml
If someone is not using the default AMI, it's possible their AMI might use a different root block device name. `/dev/sda1` for example. While we're at it, also allow them to configure the volume type. 
> Allow users to configure the root block device

- Makefile
- packer/buildkite-ami.json
This adds some simple helpers to the Makefile to make building custom AMIs for dev a little bit easier. It also ensures that we're building against the latest Amazon 2 AMI by default.
> Add helpers to Makefile for building packer image

- .buildkite/steps/test.sh
- templates/aws-stack.yml
This adds a lambda that handles the metrics polling and setting the `DesiredCount` on the ASG. 
This polls the Buildkite API more frequently and bypasses the AWS autoscaling mechanisms. My current tests are showing instances booting and picking up work in about 60 seconds, which is cool. 
Still TODO is cooldown of some sort, probably just for scaling in.
> Add an experimental lambda scaler

- packer/conf/bin/bk-install-elastic-stack.sh
This will ensure that we optimize for leveraging the instances that are available to us, rather than unintentionally packing all jobs onto a single instance.
Fixes #540 
> Set the priority of the agent to its instance integer

- packer/conf/buildkite-agent/systemd/buildkite-agent@.service
We had an issue where the agent failed to restart on SIGPIPE, which turns out to be a thing when systemd and journald restart. 
Similar to https://github.com/influxdata/telegraf/pull/2716.
> Restart agent on SIGPIPE (journald restart)

- packer/buildkite-ami.json
Looks like a temporary packer key was left on the instances. These are destroyed after builds by packer, but good to remove it from `authorized_keys`. 
Fixes #544.
> Remove temporary packer key

- packer/conf/bin/bk-install-elastic-stack.sh
- templates/aws-stack.yml
This updates the https://github.com/buildkite/buildkite-agent-scaler version to the latest which includes writing `JobScheduledCount` metrics to Cloudwatch Metrics.
> Write cloudwatch metrics from lambda scaler

- goss.yaml
- packer/conf/bin/bk-install-elastic-stack.sh
- packer/conf/buildkite-agent/scripts/stop-agent-gracefully
- packer/conf/buildkite-agent/systemd/buildkite-agent.service
- packer/scripts/install-buildkite-agent.sh
This simplifies things a bit by using the new `--spawn` parameter for multiple parallel agents with a single system service.
> Use spawn vs multiple systemd units

- templates/aws-stack.yml
Currently the lambda timeout is about the same as the scheduled execution frequently, which means occasionally the function doubles up and runs in parallel.
> Decrease the lambda timeout to less than 60s

- .buildkite/steps/test.sh
- packer/conf/bin/bk-install-elastic-stack.sh
- packer/conf/buildkite-agent/scripts/terminate-instance
- templates/aws-stack.yml
This removes the old alarm-based autoscaling in favour of lambda-based scale-out and per-host based idle scale-in.
It's radically faster. I'm seeing 50-75s from the time a job is queued to the time an agent is available on a new host! 
This will likely need to be released in v5.0.0. 
Closes #93, #322 and #436.
> Remove alarm based autoscaling

- .buildkite/steps/test.sh
- packer/conf/bin/bk-install-elastic-stack.sh
- packer/scripts/install-buildkite-agent.sh
- templates/aws-stack.yml
Supports the new git mirrors functionality in the latest Agent releases:
https://github.com/buildkite/agent/pull/936
> Add EnableAgentGitMirrorsExperiment parameter

- packer/scripts/install-utils.sh
Docker added some support for slightly improving `docker pull` performance if `unpigz` is available, see the notes here: https://github.com/moby/moby/issues/37957#issuecomment-426633293
> Install pigz for parallel decompression in docker pull

- .buildkite/steps/copy.sh
us-east-1 was accidentally removed from `copy.sh` file https://github.com/buildkite/elastic-ci-stack-for-aws/commit/e0ef99968d2be086b4734890aad34ccd1a3e9721
> Add back us-east-1 to regions

- .buildkite/steps/launch.sh
- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/windows/conf/bin/bk-install-elastic-stack.ps1
- templates/aws-stack.yml
Remove AWS autoscaling in favour of lambda scaler. 
This will the default in 5.0.0.
> Remove AWS Autoscaling in favor of buildkite-agent-scaler

- templates/aws-stack.yml
This updates the template for https://github.com/buildkite/buildkite-agent-scaler/releases/tag/v1.0.0 which gives us some neat super-powers:
* Scale out based on waiting jobs
* Scale out by a factor
> Update template for v1.0.0 of buildkite-agent-scaler

- templates/aws-stack.yml
The following commit removed the ability to use the
value set by the ImageId parameter.
https://github.com/buildkite/elastic-ci-stack-for-aws/commit/7d2ec14d1dc87ae32b98e7b75905e3d1fe6c8d51
Signed-off-by: Jeremiah Snapp <jeremiah@chef.io>
> Fix cloudformation ImageId regression

- README.md
- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/linux/conf/buildkite-agent/scripts/terminate-instance
- packer/linux/conf/buildkite-agent/systemd/buildkite-agent.service
- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/conf/bin/bk-install-elastic-stack.ps1
- packer/windows/conf/buildkite-agent/scripts/terminate-instance.ps1
- packer/windows/scripts/install-buildkite-agent.ps1
- templates/aws-stack.yml
* Bumps buildkite-agent to version 3.11.5.
* Makes terminate-instance script always decrease capacity.
* Removes `BUILDKITE_TERMINATE_INSTANCE_AFTER_JOB_TIMEOUT` parameter since this is best handled by `ScaleInIdlePeriod`.
* Using the new scaler by default allows the bk-install-elastic-stack scripts to be refactored to have a cleaner way of defining `buildkite-agent.cfg` and also allows the buildkite-agent service to run `post stop` commands by default.
* Updates README.md
> Decrease capacity after terminating instance

- templates/aws-stack.yml
I'm pretty sure `BUILDKITE_LAMBDA_AUTOSCALING` and `LambdaAutoscaling` aren't needed anymore.
> Remove unnecessary BUILDKITE_LAMBDA_AUTOSCALING variable

- templates/aws-stack.yml
Apparently using LaunchTemplates solves the tag propagation problem that has resulted in the emails folks have been getting about IAM Authentication and Cross-stack Requests. 
It also opens up some nice possibilities for the easier introduction of Spot Fleet down the track. 
Tried this before in #424, but it wasn't possible then because there wasn't a way to specify a spot bid, but that now is possible in [InstanceMarketOptions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-instancemarketoptions.html).
> Use a LaunchTemplate instead of a LaunchConfiguration

- packer/linux/scripts/install-utils.sh
With Python2 aiming to EOL on Jan 1, 2020 (https://github.com/python/devguide/pull/344), we need to start prepping for Python3 conversion.
The [future module](https://python-future.org/) allows uplifting Python2 code to be mostly compatible with Python3, allowing for incremental conversions.
> Add python3 and future lib to allow prepping for Python2 EOL

- templates/aws-stack.yml
This replaces the hardcoded /dev/xvda value with appropriate
default values for amazon linux 2 and windows instances and
also allows for overriding the value.
Signed-off-by: Jeremiah Snapp <jeremiah@chef.io>
> Set RootVolumeName appropriately

- templates/aws-stack.yml
In my testing the stack's Windows Server 2019 instances take approximately 6 minutes to fully come online so we should make sure the `InstanceCreationTimeout` value is sufficiently large enough to accommodate the longer startup time.
> Add default InstanceCreationTimeout value for windows instances

- templates/aws-stack.yml
This pull request updates the policy to match what is suggested in the documentation (linked below). 
In our testing, the default policy also did not allow uploading of artifacts despite what the policy seemed to allow. However, this could be due to another issue in our configuration.
https://buildkite.com/docs/agent/v3/cli-artifact#using-your-own-private-aws-s3-bucket
> Update ArtifactBucketPolicy to match docs

- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/windows/conf/bin/bk-install-elastic-stack.ps1
- templates/aws-stack.yml
This provides changes to allow using a Buildkite agent token that is set in AWS SSM.
It should help with #422 and #597.
I'm assuming the lambda code is coming from [buildkite-agent-scaler](https://github.com/buildkite/buildkite-agent-scaler) since that's the name of the bucket the lambda binary is taken from. I've looked through that code and found that it already supports retrieving the token from SSM by setting `BUILDKITE_AGENT_TOKEN_SSM_KEY`. The only remaining thing I can think of is adding the IAM permissions to the lambda to allow it to read and/or decrypt the parameter in SSM.
Before proceeding with this further, can I get the maintainers (and community I suppose) opinion on this change? I could make further changes so that it's hopefully backwards compatible, but currently it is …
> Add support for loading BuildkiteAgentTokenPath from Parameter Store

- packer/windows/conf/bin/bk-install-elastic-stack.ps1
- templates/aws-stack.yml
Sometimes Windows instances fail to come up completely but are not marked unhealthy. It turns out sometimes the generated randomized password for the buildkite-user doesn't meet the password policy requirements and causes a failure of the `bk-install-elastic-stack.ps1` script. Normally that would trigger the `on_error` trap which would mark the instance unhealthy and it would be replaced but unfortunately there is a bug in the `on_error` trap that was preventing it from getting the instance ID. This leaves the instance running indefinitely but without a running buildkite-agent service which means jobs can wait indefinitely for an instance because the scaler lambda believes a healthy instance already exists.
This PR fixes the bug in the `on_error` trap so a failure of the …
> Ensure unhealthy Windows instances get marked correctly

- templates/aws-stack.yml
This resolves #615
I've only added the VPC and export names for the existing ones so they can be referenced in other places. Let me know if this is okay or any changes.
To clarify the exact use-case; we would like to run 2 of these stacks with different sized instances but want to share a VPC and role created by one, with the other without having to create that role externally and pass it into both.
> Add cloudformation output exports

- packer/linux/conf/buildkite-agent/systemd/buildkite-agent.service
This applies the patch that @james-portman-contino suggested in https://github.com/buildkite/agent/pull/1075.
> Prevent the agent from terminating immediately on stop

- templates/aws-stack.yml
Trying to use the CloudFormation template from the HEAD of master yields this error: `Error: ROLLBACK_COMPLETE: ["The following resource(s) failed to create: [AutoscalingLambdaExecutionRole]. . Rollback requested by user." "Value of property Policies must be a list of objects"]` (Note we are running the stack through terraform but I don't think that is necessarily related).
This PR fixes that issue.
> Fix lambda role

- packer/linux/conf/bin/bk-install-elastic-stack.sh
This is a carry on from #624 to fix the newly introduced support for SSM parameter for the agent token.
Without the change, the get-parameter command returns the value as it appeared in the default json output which includes quotes.
Eg: `"token is here"`.
This was then double quoted by the script and when the EC2 instance boots up it sends the token to the API as `""token is here""` which is invalid.
With this change the quotes are removed from the get-parameter command so there is only one level of quotes
> Get SSM parameter as raw text

- packer/linux/conf/buildkite-agent/systemd/buildkite-agent.service
Reverts buildkite/elastic-ci-stack-for-aws#622
Fixes #629
> Revert "Prevent the agent from terminating immediately on stop"

- packer/windows/scripts/install-utils.ps1
git-for-windows v2.23.0 has a bug preventing bash process substitution from working which breaks the docker-login plugin so we'll pin to v2.22.0 until a git-for-windows releases the fix.
Fixes https://github.com/buildkite/elastic-ci-stack-for-aws/issues/631
> Pin git-for-windows to v2.22.0

- packer/linux/buildkite-ami.json
Replaced the hard-coded AMI source when building the Linux instance (using Packer) to use a filter query instead. This way the latest AMI is always sourced and the value doesn't need to be as actively maintained (matches the Packer builder for the Windows image, which uses a filter query).
Doing this also reduces the need to apply updates at build time.
> Replaced Linux fixed AMI source with source AMI filter

- packer/linux/conf/buildkite-agent/systemd/cloud-final.service.d/10-power-off-on-failure.conf
- packer/linux/scripts/install-buildkite-agent.sh
This appears to fix #572 for us.
We see occasional failures from `cloud-init` failing to communicate with the EC2 metadata endpoint. These appear in systemd as a failure of the `cloud-final` service. By adding `OnFailure=poweroff.target`, the instance will power itself off when this occurs and allow the ASG to replace it instead of hanging around in a hung state forever.
> Power off immediately if cloud-init fails

- packer/windows/conf/bin/bk-fetch.ps1
- packer/windows/conf/bin/bk-install-elastic-stack.ps1
- packer/windows/scripts/ec2-userdata.ps1
- packer/windows/scripts/install-awslogs.ps1
- packer/windows/scripts/install-buildkite-agent.ps1
- packer/windows/scripts/install-docker.ps1
- packer/windows/scripts/install-lifecycled.ps1
- packer/windows/scripts/install-utils.ps1
We have to explicitly test the exit status after running executables because powershell doesn't automatically fail when an executable's exit status is non-zero.
We've deployed these changes to our own Windows Buildkite packer template and it really increases the confidence that the powershell scripts haven't silently failed.
> Ensure powershell scripts fail when executable fails

- packer/linux/conf/docker/cron.hourly/docker-low-disk-gc
Also prune docker builder caches to avoid:
> Docker builder prune

- packer/conf/bin/bk-check-disk-space.sh
e97921cc74e8a69fccbe98ebcc6ee0f50a9ccbcf on `master` increased the `DISK_MIN_AVAILABLE` threshold to 5GB a few months ago, but it doesn't seem to be in the 4.3.5 release that happened since then.
The 1GB threshold is causing us problems (https://github.com/buildkite/elastic-ci-stack-for-aws/issues/465#issuecomment-555846619) so this PR cherrypicks that existing commit onto the 4.3 series branch, as a temporary work-around while waiting for the stalled #623 and/or #639.
> Increase the threshold for disk cleanup to 5GB free for 4.3

- README.md
This PR adds missing quotes around the `$(cat config.json)` command substitution in the `README.md` example. Without them, each space-separated chunk of JSON in that file was being treated as a separate argument to the `aws create-stack` command, and only the first interpreted as (broken) JSON;
> Error parsing parameter '--parameters': Invalid JSON: [
This quoting issue was the only complaint [shellcheck](https://www.shellcheck.net/) made about that particular shell snippet:
```
Line 7:
--parameters $(cat config.json)
^-- SC2046: Quote this to prevent word splitting.
```
> README create-stack example fixed; quote command expansion

- README.md
- packer/linux/scripts/install-docker.sh
- packer/windows/scripts/install-docker.ps1
Docker 19.03.5 + docker compose 1.25.0 (allowing to use BUILDKIT builder backend)
> bump docker and docker compose versions

- README.md
- packer/linux/scripts/install-docker.sh
- packer/windows/scripts/install-docker.ps1
Partially reverts buildkite/elastic-ci-stack-for-aws#654
docker-compose 1.25.0 has a regression preventing https://github.com/buildkite-plugins/docker-compose-buildkite-plugin from using an image pre-built in a previous build step. This would cause much longer build times, and in some cases build failures if the later step is unable to build the image itself (e.g. if the Dockerfile is BuildKit-specific but the step building it doesn't support that).
See: https://github.com/docker/compose/pull/7039 and other issues linked from there.
> Revert "bump docker and docker compose versions"

- templates/aws-stack.yml
Currently the default ec2 instance role created does not have permissions to access the SSM parameter specified by the user. This also fixes a potential bug where the lambda would not have the correct set of permissions if an SSM path was provided but not a KMS key id.
* Split the KMS and SSM logic in the policy for the existing Lambda role
* Add the KMS and SSM permissions to the ec2 instance role
* Tested via using this template and using all permutations of specifying and not specifying `BuildkiteAgentToken`, `BuildkiteAgentTokenParameterStorePath` and `BuildkiteAgentTokenParameterStoreKMSKey`
> Bug with SSM permissions 

- .buildkite/steps/launch.sh
- packer/windows/scripts/install-utils.ps1
Windows AMI pinned to awscli v1
See https://github.com/buildkite-plugins/ecr-buildkite-plugin/issues/37
This patch pins `choco install awscli` to the currently-latest `1.18.11`; see https://chocolatey.org/packages/awscli/1.18.11#versionhistory (Chocolatey doesn't make it possible to pin to a major version.)
This should be reverted after the ECR plugin supports awscli v2.
> windows: pin awscli to v1; v2 breaks 'aws ecr get-login'

- packer/linux/conf/buildkite-agent/hooks/environment
- packer/linux/conf/buildkite-agent/hooks/pre-command
- packer/windows/conf/buildkite-agent/hooks/environment
- packer/windows/conf/buildkite-agent/hooks/pre-command
ECR plugin-ish hook is now an `environment`, not a `pre-command` hook.
Changed as of this ECR plugin commit:
https://github.com/buildkite-plugins/ecr-buildkite-plugin/commit/18295819f568c099ab7056d41621768e62462167
Which was part of this PR:
https://github.com/buildkite-plugins/ecr-buildkite-plugin/pull/26
Brought into this repo by:
https://github.com/buildkite/elastic-ci-stack-for-aws/commit/9bec0c348f840ccf1db1008e7f9b70d1256bd600
> Fix ECR hook; environment, not pre-command

- templates/aws-stack.yml
Fixes #562. Doesn't break existing users of `SecurityGroupId`, but it could be deprecated and later removed.
> Support multiple build instance security groups

- README.md
A customer encountered some difficulties when their stack was configured on more than one queue. This helps clarify the docs around this behavior.
> Update with clarification about how scaling works

- README.md
- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
This change updates the version of `buildkite-agent` that's bundled into the AMI to 3.21.1.
> Bump agent version to 3.21.1

- templates/aws-stack.yml
- templates/ssm-ami.yml
This adds an optional String parameter to the elastic-ci stack parameter list. If given this is expected to be an SSM Parameter Path. This cannot be typed as an `AWS::SSM::Parameter` at the top level because that would make it mandatory. Instead, if given, a substack with a `AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>` parameter is brought in whose output is the value we need.
Example error when using an `AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>` parameter with a `Default: ""`:
```
Error: Failed to create changeset for the stack: substack-laundry, An error occurred (ValidationError) when calling the CreateChangeSet operation: Parameter AmiParameterPath should either have input value or default value
```
This change removes the `UseDefaultAMI` condition and replaces it with …
> Add an optional ImageId SSM Parameter Path

- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/conf/bin/bk-install-elastic-stack.ps1
- packer/windows/scripts/install-buildkite-agent.ps1
We currently set `git-mirrors-path` even when [`EnableAgentGitMirrorsExperiment`](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/555) is `false`. That would lead to unexpected activation of the feature if a newer version of https://github.com/buildkite/agent promotes `git-mirrors` from experiment status.
This patch configures `git-mirrors-path` as an empty string unless `EnableAgentGitMirrorsExperiment` is `true`.
> Only set git-mirrors-path when EnableAgentGitMirrorsExperiment

- templates/aws-stack.yml
The newer `t3` instance family is objectively better than `t2`.
The `large` size (8 GiB RAM) is more realistic than `nano` (0.5 GiB RAM) for actual workloads, and still very affordable with autoscaling.
> InstanceType default t3.small, was t2.nano

- packer/linux/conf/buildkite-agent/scripts/terminate-instance
We run a slightly modified version of this stack, in which it doesn't have permission to call `terminate-instance-in-auto-scaling-group`.
I will change that, but for robustness I don't think a failure here should cause the box to stay up (and the buildkite-agent to get restarted by systemd).
Just falling through to `sudo poweroff` will be sufficient.
This causes issues with scaling down, as the non-zero exit code from `aws autoscaling terminate-instance-in-auto-scaling-group` results in systemd restarting buildkite-agent, which means it takes jobs even though we're trying to drain it ready for scale down.
> Ensure terminate instance exits gracefully

- .buildkite/steps/publish.sh
I recently ran into an issue when attempting to download one of the CloudFormation YAML templates provided in the release via Terraform which is caused by not setting the `content-type` to `text/yaml` on the files stored in S3.
Currently the files return `application/octet-stream` which causes the [http datasource](https://www.terraform.io/docs/providers/http/data_source.html) in Terraform to report failure as it only allows `text/*` and `application/json`.
This PR sets the content type to `text/yaml` during the upload of the file which happens in a Buildkite step.
> Set content-type on YML Files

- Makefile
- README.md
I've started working on this project in the last few days and stumbled a bit on the recommended commands.
1. I didn't realise we submodule some plugins and without them AMI building eventually fails
2. I wasn't clear on exactly what `make build` would do. I eventually worked it out, but hopefully leaving a comment makes things easier for the next person
3. The readme recommended `make build` to do the thing, but that errors out if the `build/mappings.yml` target hasn't run first. I've added it as a dependency in the Makefile
> Development setup tweaks

- Makefile
Rendering `aws-stack.yml` depends on the `mappings.yml` file existing. I previously setup that dependency directly (see PR #706), however that broke CI where we want to manually manage the mappings.yml file.
This seems like it might be a way to ensure `make build` works in our development environment (as documented in the README) while also keeping the CI pipeline working.
> make build: render the mappings.yml file before aws-stack.yml

- packer/linux/scripts/install-docker.sh
- packer/windows/scripts/install-docker.ps1
* docker to 19.03.13 (linux) and 19.03.12 (windows)
* docker-compose to 1.27.4 (linux)
* docker-compose on windows is installed via chocolatey, and at the time of this commit is version 1.27.2
v4.5.0 of the elastic stack was released with docker 19.03.12 and docker-compose 1.25.1 - the upcoming release should use at least the same versions.
I've bumped them a little higher that what was in v4.5.0, but only to versions I consider relatively low risk.
> bump docker and docker-compose

- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/windows/conf/bin/bk-install-elastic-stack.ps1
I've noticed the following warning in log output of various stacks:
> The config option `tags-from-ec2` has been renamed to `tags-from-ec2-meta-data`. Please update your configuration.
The deprecation happened in agent 3.17.0 ([august 2019](https://github.com/buildkite/agent/pull/1067)) [1]. The stack ships with a more recent version and it seems unlikely anyone will jump through hoops to downgrade, so I think it's safe to use the newer flag.
> update agent config: tags-from-ec2 -> tags-from-ec2-meta-data

- packer/linux/conf/buildkite-agent/systemd/buildkite-agent.service
When the agent process exits cleanly, our goal is to shut the instance down and reduce the autoscaling group size by 1.
Currently, we do that by running two commands in sequence:
1. terminate-instance
2. sudo poweroff
I'm proposing we remove the poweroff call, for two reasons:
1. It's redundant. The terminate-instance script instructs the ASG to terminate this instance, and this often happens within 2-3 seconds.
2. If the ASG is a bit slow action the termination, the poweroff doesn't work anyway. The buildkite-user doesn't have the required permissions in /etc/sudoers to call poweroff, so we get the following in the system logs
> Oct 01 11:22:55 sudo[5090]: We trust you have received the usual lecture from the local System
> Oct 01 11:22:55 sudo[5090]: Administrator. It usually boils down …
> stop trying to call poweroff after the agent shuts down

- packer/linux/conf/buildkite-agent/scripts/terminate-instance
When the buildkite-agent exits cleanly (generally after an idle timeout), we ask the ASG to terminate the instance. The termination can happen *very* quickly, oftern within 2-3 seconds.
We use the legacy awslogs tool[1] to send logs to cloudwatch, and it buffers new logs for 5 seconds (or 32Kb, whichever comes first).
This results in a race condition - often the final logs from the agent as it shutdown may not make it to cloudwatch before the instance shuts down.
Long term we assume migrating from awslogs to the new cloudwatch agent might improve this situation. However, we don't plan to attempt that migration vor the v5 release and we'd like to improve the chances customers will have access to a full agent log in clouddwatch. Adding a 10 sec sleep before requesting termination is …
> add a 10sec pause before we request instance termination

- packer/linux/conf/buildkite-agent/scripts/terminate-instance
Revert #707, because we've now removed the `poweroff` call in #728 (because it wasn't working correctly anyway).
If we allow `terminate-instance` to fail silently, _and_ we don't have another `ExecStopPost` to ~shut down the instance~ _also exit non-zero_, the instance is left dead in the water: still consuming a slot in the ASG, but with no agent running, and nothing to get it out of that state.
We (re-)considered some other changes (e.g. make the `poweroff` actually work), but this seems like the best option available: if we fail to terminate the instance, then we pass the failure to systemd, which will in turn restart the agent (which, if necessary, might try to stop itself again sometime later). 
Most notably, `terminate-instance` will fail if stopping the instance would drop the ASG …
> Propagate terminate-instance failure up to systemd again

- .buildkite/steps/publish.sh
Previously `publish.sh` only supported pre-releases as including "-rc" in the git tag. This change allows us to just use any "-" to specify a pre-release version (e.g. `v5.0.0-beta1`)
> Fix publish script to support beta tags

- packer/linux/conf/buildkite-agent/scripts/stop-agent-gracefully
This addresses #733 by capturing the lifecycle transition from the first script argument. If we're not terminating due to spot the script should behave as it did before. If we are terminating due to spot, we do the following:
1. Send SIGTERM to the master agent process in a non-blocking fashion
1. Calculate the unix timestamp 20 seconds before the spot termination time and consider this our STOP_TIME
1. Check to see if the agents stop gracefully before our STOP_TIME
1.  If the agents stop on their own, exit 0. If they don't, send `SIGQUIT` and let this script exit, you only have 20 seconds before termination anyway.
I tested this by booting up a stack and manually destroying the scaling lambda as to not have anything provision agents outside this test. I then create a spot fleet …
> Send SIGQUIT before spot termination time

- CHANGELOG.md
4fafd8e was not intended to pushed directly to master. My apologies. It is already there so this PR fixed the changelog references to a commit instead of (intended) PR.
> Fix CHANGELOG for agent scaler v1.0.2 bump

- CHANGELOG.md
- README.md
- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
[Buildkite Agent 3.25.0](https://github.com/buildkite/agent/releases/tag/v3.25.0)
> Bump Buildkite Agent to v3.25.0

- templates/aws-stack.yml
By default, if the two availability zones in the agent ASG become significantly unbalanced, the ASG will terminate some instances in the larger AZ and start some new ones in the smaller AZ.
That's helpful for an ASG serving web requests, but it's not very helpful for our agent-shared workloads - the instance termination can disrupt running jobs. With the new lambda based scaler, each instance is responsible for terminating itself and the AZs become unbalanced very easily. That's not much of a problem though - the larger AZ is likely to reduce in size relatively soon, and subsequent scale-outs will restore the balance (for a while).
Sadly there's no way to suspend the AZRebalance process via cloudformation, so I held my nose and implemented it using a custom resource. It's not as ugly as I …
> The agent autoscaling group should never rebalance availability zones

- packer/windows/conf/bin/bk-install-elastic-stack.ps1
- packer/windows/conf/buildkite-agent/scripts/terminate-instance.ps1
There's a known issue around the lambda scaling behaviour and when the stack's MinSize is greater than 0 (see #712). On unix, the Buildkite service will exit on idletimeout, but restart as configured in the `systemd` service configuration. On Windows, we never restart, so the instance will end and the ASG will provision us a fresh instance. This is way more disruptive and time consuming, and leads to a lot of resource churn in AWS. While we continue to investigate the underlying issue, we're hopeful that configuring the Windows service the same way as the unix one will reduce the severity of the problem.
Our Windows service is configured through `nssm` (the "non-sucking" service manager). This service manager features the following properties to help us resolve this:
- The action to take …
> Configure Windows service exit like the unix service

- CHANGELOG.md
There's little value in keeping the v5.0.0.beta1 entry in the changelog long term, so I've converted it to the v5.0.0 final changelog entry.
It's 95% the same as beta1, with a few bug fixes and dependency bumps.
> update changelog for v5.0.0 release

- Makefile
The linux build takes ~4 minutes, the windows build takes ~25 minutes.
**WHHYYYYYY?**
> add timestamps to packer output

- templates/aws-stack.yml
I started reviewing #651 as an excuse to improve my CloudFormation knowledge, and ended up extending it into an alternative approach that might be worth considering.
This makes the following changes to master:
1. Replaces the `SpotPrice` parameter with `OnDemandPercentage` that defaults to 100%. If this is reduced, the stack will potentially use Spot instances if they're available and cheaper than the standard OnDemand price
1. Allows the `InstanceType` parameter to be a CSV with 1- 4 types. When launching  OnDemand instances the types will be used in priority order, and when launching spot instances (if the config allows them) all types will be considered (AWS will pick the instances with the best capacity and least chanec of being terminated).
The internal implementation of the …
> Support multiple instance types by switching to a Mixed Instance ASG

- README.md
As discussed in issue #759, the advice to set the AgentsPerInstance value to 1 is outdated! Removing so that everyone can have confidence to raise that number.
> Remove outdated advice re AgentsPerInstance

- packer/windows/conf/bin/bk-install-elastic-stack.ps1
fixes #761 
Gets agent token from param store if `BuildkiteAgentTokenParameterStorePath` is set and `BuildkiteAgentToken` is not for windows instances.
> Retreive agent token from param store on windows agents

- .buildkite/pipeline.yml
- .buildkite/steps/packer.sh
- Makefile
- packer/linux/buildkite-ami.json
- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/buildkite-ami.json
- packer/windows/scripts/install-buildkite-agent.ps1
Integrating https://github.com/buildkite/elastic-ci-stack-s3-secrets-hooks/pull/37 into elastic-stack.
CI:
Development:
> Integrate Go s3secrets-helper into elastic-stack

- README.md
The [AWS S3 Secrets Buildkite Plugin](https://github.com/buildkite/elastic-ci-stack-s3-secrets-hooks) allows the location of the secret files on the S3 bucket to be defined using the environment variable `BUILDKITE_PLUGIN_S3_SECRETS_BUCKET_PREFIX` ([code](https://github.com/buildkite/elastic-ci-stack-s3-secrets-hooks/blob/67c4e227b5e591608794776d6330c7fe4ea2273a/s3secrets-helper/secrets/secrets.go#L35)). 
Therefore, instead of using the pipeline name, e.g:
`s3://{bucket_name}/{pipeline-slug}/private_ssh_key`
We can point it to any other location, e.g:
`s3://{bucket_name}/{BUILDKITE_PLUGIN_S3_SECRETS_BUCKET_PREFIX}/private_ssh_key`
This is a very handy feature when dealing with multiple pipelines in a monorepo, as it allow pipelines to share the same secrets (if that is desired).
> docs: ✏️ Add reference to BUILDKITE_PLUGIN_S3_SECRETS_BUCKET_PRE

- .buildkite/pipeline.yml
- .buildkite/steps/copy.sh
- .buildkite/steps/launch.sh
- .buildkite/steps/packer.sh
- Makefile
- packer/linux/buildkite-ami.json
- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/linux/conf/buildkite-agent/hooks/environment
- packer/linux/scripts/install-buildkite-agent.sh
- packer/linux/scripts/install-docker.sh
- packer/linux/scripts/install-git-lfs.sh
- packer/linux/scripts/install-lifecycled.sh
- templates/aws-stack.yml
AWS has a growing number of ARM based instance types, using their gravitron and gravitron2 CPUs.
This expands on PR #690 by @galak, changing the CI pipeline to build an `linux/arm64` AMI, and ensuring that AMI is selected when a stack is deployed with OS:linux and and ARM instance type.
A few noteworthy things:
* On linux/amd64 we install docker-compose using a binary download. Sadly there's no official arm64 binary published (see https://github.com/docker/compose/issues/7472) so I've fallen back on installing via pip (for arm64 only). This works, but it's gross to install it differently depending on arch. Hopefully we can go back to binary installs if upstream starts publishing an arm64 version
* I'm not super happy with the changes to the CI pipeline scripts yet. They work, but they …
> Experimental support for running linux ARM instances

- .buildkite/steps/copy.sh
In PR #758 we changed the AMI mappings keys to linxuamd64/linuxarm64/windows. However, we left an older format (linux_arm64/linux_amd64) in the version of the template rendered during CI.
> Fix typo in the mappings file rendered during CI

- templates/aws-stack.yml
In PR #710 we added the option to select multiple instance types by providing the InstanceType stack param as a CSV.
Unfortunately, after merging we discovered that stack updates that changed only the InstanceType stack param would fail with a cryptic error:
> Internal Failure
Helpful!
After some experimentation, I realised my original PR was incorrectly skipping the instance type overrides for types that weren't provided by the user.
Turns out, it's possible to use YAML for 15 years and *still* get confused about lists 😳
Fixes #774
> Restore the ability to change InstanceType on a running stack

- templates/aws-stack.yml
The old way works, but any time the ASG is recreated it gets a new name and the IAM role also needs to be updated. It'd be nice to skip the IAM changes so some common stack updates (like changing only InstanceType) can be performed by users without permissions to make IAM changes. 
This converts the resource in the role to use a wildcard suffix, so the role has permission to suspend the process on any ASG called `{stack-name}-AgentAutoScaleGroup-*`.
With this change, updating a stack with only an InstanceType change requires no IAM changes:
Fixes #764 
Alternative to #768
> Adjust the way we set IAM role for the process suspender

- packer/linux/scripts/install-buildkite-agent.sh
Add the trailing slash so that the command fails if the path doesn't exist, rather than creating a file call /usr/local/bin
Inspired by this ticket: https://secure.helpscout.net/conversation/1370252863/14773?folderId=1113730
> Add trailing slash to install path

- templates/aws-stack.yml
AWS [announced gp3 EBS volumes earlier this month](https://aws.amazon.com/about-aws/whats-new/2020/12/introducing-new-amazon-ebs-general-purpose-volumes-gp3/). They're slightly cheaper and have [the same or better performance than gp2](https://aws.amazon.com/ebs/general-purpose/), so we may as well default to the new type.
> default to gp3 volumes

- templates/aws-stack.yml
Earlier this month AWS announced the new c6gn.* family of instances [1]. They have an ARM based Graviton CPU, and have additional network capacity over the standard c6g.* instances.
It's unlikely these will be commonly used in CI stacks, but you never know and it's easy for us to support them.
[1] https://aws.amazon.com/blogs/aws/coming-soon-ec2-c6gn-instances-100-gbps-networking-with-aws-graviton2-processors/
> recognise c6gn.* instances as ARM

- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/linux/conf/buildkite-agent/scripts/terminate-instance
- packer/linux/conf/docker/cron.hourly/docker-low-disk-gc
- packer/windows/conf/bin/bk-install-elastic-stack.ps1
- packer/windows/conf/buildkite-agent/scripts/terminate-instance.ps1
Extracted from #786 (thanks @holmesjr!), this pull request uses [IMDSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) session tokens when calling the EC2 Instance Metadata Service. This paves the way for making IMDSv2 (optionally?) mandatory in buildkite/elastic-ci-stack-for-aws.
References:
[Add defense in depth against open firewalls, reverse proxies, and SSRF vulnerabilities with enhancements to the EC2 Instance Metadata Service](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/) — the November 2019 announcement of IMDSv2, including why it's important for security.
[Transition to using Instance Metadata Service Version …
> Use IMDSv2 session tokens

- templates/aws-stack.yml
This pull request is inspired by #786 (thanks @holmesjr!) and a follow-up to #788 which was also extract from the PR. It currently contains the bf42884 commit from that latter PR, which will rebase away.
Introduces an `IMDSv2Tokens` parameters, which determines whether the Instance Metadata Service requires IMDSv2 tokens on all requests. The parameter defaults to `optional`, which matches the default behaviour of the IMDS, and so it backwards compatible.
Setting it to `required` makes IMDSv2 tokens mandatory. #788 changes all elastic-stack calls to IMDS to use tokens. Any other code running within builds/plugins/hooks that talks to IMDS etc will also need to use IMDSv2 tokens. This is default for recent versions of AWS SDK and CLI tools. But setting it to `required` may be problematic for …
> IMDSv2Tokens parameter: optional / required

- packer/linux/scripts/install-docker.sh
docker-compose depends on the cryptography package, [v3.4 of which introduces a build dependency on rust](https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst#34---2021-02-07); let's avoid that for now by constraining the install to `cryptography<3.4`.
This should be unpinned ASAP; hopefully `docker-compose` will offer binary download for arm64 at some point:
https://github.com/docker/compose/issues/7472
> arm64: docker-compose→paramiko→cryptography version pinned

- README.md
- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/conf/bin/bk-install-elastic-stack.ps1
- packer/windows/scripts/install-buildkite-agent.ps1
Bump buildkite-agent from v3.26.0 to the just-released [v3.27.0](https://github.com/buildkite/agent/releases/tag/v3.27.0). This brings, amongst other things, support for `%spawn` in agent naming, which the elastic-stack will use in an upcoming ~PR~ commit.
> buildkite-agent v3.27.0, agent names use %spawn

- .buildkite/steps/cleanup.sh
CI for this project includes launching test CloudFormation stacks. There's a cleanup step at the end which attempts to delete the stacks launched by that build, and also searches for older stacks/buckets etc that were missed by previous cleanups. However, the stack naming evolved since the cleanup script was written, so it wasn't finding the stacks/buckets/etc.
This PR updates the name patterns to match the newer stacks/buckets.
> CI: fix cleanup process

- templates/aws-stack.yml
This makes it a lot easier to give users access to create their own queue by allowing a permission boundary to be attached.
We currently do not allow iam role creation or attachment of policies without a permission boundary set.
For more context, see this [aws blog post on "Delegate permission management to developers by using IAM permissions boundaries"](https://aws.amazon.com/blogs/security/delegate-permission-management-to-developers-using-iam-permissions-boundaries/) and [AWS 2019 Reinvent "AWS Identity: Permission boundaries & delegation"](https://d1.awsstatic.com/events/reinvent/2019/REPEAT_1_AWS_identity_Permission_boundaries_&_delegation_SEC402-R1.pdf).
@yob @lox
> Support IAM Permissions Boundaries

- templates/aws-stack.yml
This reverts PR #767, which introduced a syntax error to the cloud formation template. I'm reverting to restore the build, but we can merge a revised PR when it's ready.
> Revert PR 767

- templates/aws-stack.yml
Original pr https://github.com/buildkite/elastic-ci-stack-for-aws/pull/767
Reverted https://github.com/buildkite/elastic-ci-stack-for-aws/pull/802
Added missing else condition. If the boundary is not supplied, the `!Ref "AWS:NoValue"` should null out the argument.
Opened this pr as the last one https://github.com/buildkite/elastic-ci-stack-for-aws/pull/804 closed due to branch rename.
> Add missing else condition to iam permission boundary

- packer/windows/scripts/install-utils.ps1
The windows AMI build has started failing because 2.2.0 isn't available any more:
I have zero knowledge about Chocolatey and how it manages package versions - it seems weird that a version would just go away. Anyway, I checked https://chocolatey.org/packages/git and it seems 2.31.0 is available now. Git is very backwards compatible, so upgrading should be safe.
> bump git on windows from 2.22.0 to 2.31.0

- packer/linux/buildkite-ami.json
- packer/linux/scripts/install-session-manager-plugin.sh
- packer/windows/buildkite-ami.json
- packer/windows/scripts/install-session-manager-plugin.ps1
Closes https://github.com/buildkite/elastic-ci-stack-for-aws/issues/817
Not sure how to install the executable silently on Windows.
> Session manager plugin

- packer/linux/scripts/install-lifecycled.sh
- packer/windows/scripts/install-lifecycled.ps1
There have been two releases of lifecycled in the past 3 months - [3.1.0](https://github.com/buildkite/lifecycled/releases/tag/v3.1.0
) and [3.2.0](https://github.com/buildkite/lifecycled/releases/tag/v3.2.0).
Neither has any changes that should impact the elastic stack, but it's nice to stick near the latest release so the delta between the elastic stack and upstream doesn't get too big.
Most of the changes are about updating the version of go we build with, and updating some key dependencies (like aws-sdk-go).
> bump lifecycled from 3.0.2 to 3.2.0

- packer/linux/scripts/install-docker.sh
- packer/windows/scripts/install-docker.ps1
* Linux: 20.10.6
* Windows: 20.10.0
We're assuming this is a backwards compatible upgrade and safe to include in the elastic stack 5.2.x to 5.3.x upgrade. Assuming the AMIs build, we'll might merge and dogfood them for our internal builds to build confidence in the compatibility and safeness of the bump.
The windows patch release is older because that's all that seems to be available.
> bump docker from 19.03.x to 20.10.x

- templates/aws-stack.yml
A single new feature is included in this release. When the elastic stack is very small (<=2 running instances), consider adding a new instance when we suspect the current instances are shutting down and there's pending jobs.
Pull request with more details is here: https://github.com/buildkite/buildkite-agent-scaler/pull/40
> bump scaler from 1.0.2 to 1.1.0

- packer/linux/scripts/install-docker.sh
- packer/windows/scripts/install-docker.ps1
* Linux 1.28.6
* Windows 1.28.5 (the latest available on chocolatey)
There's no specific features we need, we just want to do regular small bumps so the elastic stack never falls behind, and also avoid big changes in behaviour from release to release
1.29.1 is the latest released version, but I stuck with 1.28.x so we can have consistent minor versions across linux and windows. There's so new features in 1.29.x that can't wait for the next elastic stack release.
> Update docker-compose on all operating systems to 1.28.x

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
Mostly just bugfixes. Bumping in preparation for a new elastic stack release.
> bump agent from 3.27.0 to 3.29.0

- .buildkite/steps/copy.sh
Shellcheck isn't happy that we use default behaviour to split on a bash array. You'll be directed toward _adding_ quotes in [SC2048](https://www.shellcheck.net/wiki/SC2048) and then be warned to _remove_ them to comply with [SC2066](https://github.com/koalaman/shellcheck/wiki/SC2066). The answer is to silence the warning, unfortunately.
> Fix linter issue in steps/copy.sh

- templates/aws-stack.yml
These appear to be vestigial since we no longer use SNS/SQS queue for agent lifecycle operations when we removed that for lifecycled in #135.
> Remove IAM roles for SNS and SQS

- templates/aws-stack.yml
Reverts buildkite/elastic-ci-stack-for-aws#829 – This seems to have broken the agent when an EC2 is in service. I need more time to investigate, so this has to be reverted.
> Revert "Remove IAM roles for SNS and SQS"

- templates/aws-stack.yml
In #813 we added a regexp validation to this stack parameter that was intended to check the parameter is either an empty string or a path that starts with a / character.
The list of characters we permitted comes from [1]. However, we forgot to include / as a permitted character beyond the first. It's valid (and common) for paths to have multiple / to indicate hierarchy and we should support it.
Fixes #834
[1] https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-su-create.html
> allow multiple / characters in BuildkiteAgentTokenParameterStorePath

- templates/aws-stack.yml
Original Issue https://github.com/buildkite/elastic-ci-stack-for-aws/issues/834
Previous PRs https://github.com/buildkite/elastic-ci-stack-for-aws/pull/813 https://github.com/buildkite/elastic-ci-stack-for-aws/pull/835
cc: @yob @jufemaiz @vgrigoruk
> Allow dashes in BuildkiteAgentToken Path

- Makefile
While testing https://github.com/buildkite/elastic-ci-stack-for-aws/issues/843 I noticed that this typo breaks building a Windows AMI locally on Linux. Specifically it builds a Linux executable which errors out when `buildkite-agent` tries to run it during the start of a step:
```
:llama: Setting up elastic stack environment (v5.3.1)
...
/usr/local/buildkite-aws-stack/plugins/secrets/hooks/environment: line 12: /c/buildkite-agent/bin/s3secrets-helper: cannot execute binary file: Exec format error
🚨 Error: Error setting up bootstrap: The global environment hook exited with status 126
```
Note that CI works because `GOOS` is specified correctly in the pipeline env; this make target isn't used.
> Fix windows s3secrets-helper cross compile

- templates/aws-stack.yml
We would like to avoid managed secret buckets creation in case of `EnableSecretsPlugin = false`
> Create secrets bucket only when needed

- packer/linux/scripts/install-docker.sh
The latest moby upstream changes expect a `containerd` service to be installed and run independently. Thus if you were to build the AMI in master right now (we do this to get the latest ami security updates) it would cause the buildkite-ami to fail to start the docker-service and hence the machine gets killed. This fix pins the systemd images to the docker version so that the AMI's will be correctly aligned with the expected docker start commands. 
- https://github.com/moby/moby/blob/master/contrib/init/systemd/docker.service#L13
- https://github.com/moby/moby/blob/v20.10.6/contrib/init/systemd/docker.service#L13
> fix: Pin docker systemd services to the same docker version

- templates/aws-stack.yml
This IAM action is redundant, there is no s3:Get action and the asterisk rule will already match s3:Get.
Fixes #852
> Remove unused s3:Get action

- templates/aws-stack.yml
Depends on https://github.com/buildkite/buildkite-agent-scaler/pull/47 being merged to release the updated scaler version.
> Bump lambda scaler version

- templates/aws-stack.yml
Small change to allow Docker containers running on an instance and not using an awsvpc CNI to receive responses from the IDMSv2 service.
Fixes #857
> Increase the HttpPutResponseHopLimit from 1 to 2

- templates/aws-stack.yml
See https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/allocation-tag-restrictions.html for docs on the restrictions, you cannot create a tag starting with `aws:`. I’ll create a stack with this to see if you’re supposed to add the `user:` prefix or if you can cost allocate over any tag name and the `user:` part is just presentation in the cost allocation dashboard / reports.
Fixes #856
> Drop the aws prefix from the default cost tag prefix

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
Closes https://github.com/buildkite/elastic-ci-stack-for-aws/issues/862
Let me know if this PR needs anything else.  Thanks!
> Bump agent version to 3.30.0

- packer/linux/scripts/install-docker.sh
After running into package dependency issues with the yum/rpm based install from the CentOS package repositories, this should be a simpler fix to include buildx in our base image.
Alternative to https://github.com/buildkite/elastic-ci-stack-for-aws/pull/870
Fixes https://github.com/buildkite/elastic-ci-stack-for-aws/issues/765
> Install Docker buildx by downloading the GitHub release 

- README.md
- templates/aws-stack.yml
While the template and AMIs are entangled I think this is probably the most sensible support policy we can come up with.
I think there may be a future in making the AMI builds more readily forkable, perhaps with EC2 Image Builder, for folks to track software components differently to how we do in the main release series.
Down the road I’d also like to add a Windows Server 2019 arm64 build to complete our ARM line up at the Elastic CI Stack for AWS layer.
> Add support policy docs

- README.md
Document where `make packer` will run and what it will output.
Fixes #675
> Add docs that packer will run in the default vpc in us-east-1

- templates/aws-stack.yml
Adds a [`Rules`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/rules-section-structure.html) section to validate cross-parameter values:
- One of BuildkiteAgentToken or BuildkiteAgentTokenParameterStorePath must be specified
Fixes #648
> Add cross-parameter rules

- templates/aws-stack.yml
This prints the Buildkite Agent token to the CloudWatch logs, removing it ensures the token remains incognito
> Disable `set -x` from the Linux UserData script

- .buildkite/pipeline.yml
- .buildkite/steps/packer.sh
- Makefile
- packer/linux/buildkite-ami.json
- packer/linux/scripts/install-buildkite-agent.sh
- packer/linux/scripts/install-s3secrets-helper.sh
- packer/windows/buildkite-ami.json
- packer/windows/scripts/install-buildkite-agent.ps1
- packer/windows/scripts/install-s3secrets-helper.ps1
Consumes the output of the build and release pipeline in the https://github.com/buildkite/elastic-ci-stack-s3-secrets-hooks repository.
These binaries are now attached to a release there and don’t need to be built here. This also allows that project to control the go compiler used to build its source.
Fixes #880
> Use pre-built s3-secrets-helper binaries

- templates/aws-stack.yml
Customers are increasingly reporting issues with interrupted jobs due to the agent process being lost. On investigation we have discovered an issue with the way instances are terminated which has prompted a re-evaluation of how we scale out and in.
The issue appears to be a platform side race condition in the [`terminate-instance-in-auto-scaling-group`](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/linux/conf/buildkite-agent/scripts/terminate-instance#L15) API request we use to terminate instances that have fallen idle. Observing the ASG activity log we see the ASG receive the request to terminate and decrement the desired count. Concurrently, the ASG decides to boot a new instance in order to recovery the Actual Capacity by one, followed by the …
> Enable ASG cooldown period

- packer/linux/conf/buildkite-agent/hooks/environment
Quote the replacement patterns including the trailing slash to show this is part of the pattern and not a bash syntax.
See https://github.com/koalaman/shellcheck/wiki/SC2295 for details.
> Add fix for SC2295

- templates/aws-stack.yml
I updated the `InstancePolicy` to match the `Resources` of the `AsgProcessSuspenderRole`'s `AsgProcessModification` policy.
https://github.com/buildkite/elastic-ci-stack-for-aws/blob/b84d760a66f544c5f582702ba207d280fbac20a1/templates/aws-stack.yml#L1038-L1041
The `InstancePolicy` could be further cut down.
For example, do we use `sqs` or `sns` anymore ?
https://github.com/buildkite/elastic-ci-stack-for-aws/blob/b84d760a66f544c5f582702ba207d280fbac20a1/templates/aws-stack.yml#L730-L735
According to the 5.2.0's IAMRole's AccessAdvisor tab in AWS, it shows that the following are unused
* Amazon EC2 (InstancePolicy)
* Amazon CloudWatch (InstancePolicy)
* AWS CloudFormation (InstancePolicy)
* Amazon SQS (InstancePolicy)
* Amazon SNS (InstancePolicy)
It would be good to pair these (and other?) …
> Specify asg perm resources in InstancePolicy

- packer/linux/scripts/install-s3secrets-helper.sh
- packer/windows/scripts/install-s3secrets-helper.ps1
This brings in the following fixes:
- https://github.com/buildkite/elastic-ci-stack-s3-secrets-hooks/pull/48
- https://github.com/buildkite/elastic-ci-stack-s3-secrets-hooks/pull/47
> Bump s3secrets from v2.1.2 to v2.1.4

- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/linux/conf/buildkite-agent/scripts/terminate-instance
- packer/linux/conf/docker/cron.hourly/docker-low-disk-gc
- packer/windows/conf/buildkite-agent/scripts/terminate-instance.ps1
Fix the hourly cron disk check to correctly mark the instance as unhealthy with a `--region` and ensure the bash ERR trap is triggered by having a command exit non-zero.
I’ve also updated the use of IDMS to retrieve the region to use the new region API rather than munging the AvailabilityZone API.
Fixes #742
> Fix hourly disk check

- CHANGELOG.md
- templates/aws-stack.yml
- templates/ssm-ami.yml
> Bugfix: Added missing parameter `BuildkiteAgentTokenParameterStoreKMSKey` in `Autoscaling` nested cloudformation template (#901)

- .buildkite/steps/cleanup.sh
- templates/aws-stack.yml
This errored in https://buildkite.com/buildkite-aws-stack/buildkite-aws-stack/builds/2474#78f683fb-f935-40bd-bd85-1aa28114697c during cleanup because the log delete races with the stack delete.
Move the log group clean up before the stack cleanup to bypass it.
> Make the template own and delete the log group

- packer/linux/scripts/install-docker.sh
Allow `docker buildx` to run emulation so we can build arm64 images on amd64 machines.
Fixes #799
> Install qemu and binfmt hooks

- .buildkite/pipeline.yml
Spending too long waiting for the publish step from other builds to run when all the deps are already satisfied, this should unblock them faster.
> Enable eager concurrency

- templates/aws-stack.yml
This encloses all variables in the linux userdata script with quotes to prevent word splitting or globbing. Currently if a string with a space is submitted to one of the unquoted variables, the script breaks.
See shellcheck error [SC2046](https://github.com/koalaman/shellcheck/wiki/SC2046) for details on this type of error and ways to fix it.
> Enclose all variables in the linux userdata in quotes

- goss.yaml
- packer/linux/buildkite-ami.json
- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/linux/scripts/install-lifecycled.sh
- packer/windows/buildkite-ami.json
- packer/windows/conf/bin/bk-install-elastic-stack.ps1
- packer/windows/conf/cloudwatch-agent/amazon-cloudwatch-agent.json
- packer/windows/scripts/install-lifecycled.ps1
Reverts buildkite/elastic-ci-stack-for-aws#908 This is still used and was removed in error, noticed by @pzeballos :bow:
The poll-for-spot-termination handler in lifecycled is still used for the time being, I mistakenly removed this following the SQS and SNS method clean-up.
This may let be re-removed following experimentation with Lambda based approaches to better support ASG initiated termination.
> Revert "Remove lifecycled"

- templates/aws-stack.yml
We [continue](https://buildkite-community.slack.com/archives/C19BG77H9/p1631073431016900) to experience customer reports of a race condition in the ASG which spontaneously replaces terminating instances only to kill a random instance immediately afterwards. We previously observed the addition of [`Cooldown: 60`](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/888) fixing this but that appears to have been an incomplete fix.
This approach was [suggested](https://buildkite-community.slack.com/archives/C19BG77H9/p1631244925032800?thread_ts=1631073431.016900&cid=C19BG77H9) in Slack. I have tested that it still allows instances to self-terminate using the [`aws autoscaling terminate-instance-in-auto-scaling-group`](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/5c64f61111 …
> Add NewInstancesProtectedFromScaleIn: true to the ASG

- packer/linux/conf/bin/bk-install-elastic-stack.sh
Follow up to https://github.com/buildkite/elastic-ci-stack-for-aws/pull/557 I realised pointing the buildkite-agent config for the builds location would break [fix-buildkite-agent-builds-permissions](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/e1c5f8b3965fc9b6101c48aca24e91ef778c34a4/packer/linux/conf/buildkite-agent/scripts/fix-buildkite-agent-builds-permissions#L77) on instances with instance storage.
Instead of parameterising the builds path, or reading it from the agent config, I decided to bind mount the ephemeral storage into the main file system. This way the paths stay the same but the underlying block device is the nvme or RAID device.
I think this is also preferable to partitioning the block device and mounting separate partitions into the `git-mirrors` and …
> Bind mount ephemeral storage into main file system

- templates/aws-stack.yml
An out-of-order deletion of these resources can result in stranded instances that can't self terminate.
See the docs in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html#cfn-iam-policy-roles for details of this.
Fixes #927
> Declare that the ASG depends on the IAM policies

- .buildkite/pipeline.yml
- .buildkite/steps/cleanup.sh
- .buildkite/steps/delete-service-role-stack.sh
- .buildkite/steps/delete.sh
Follow up to https://github.com/buildkite/elastic-ci-stack-for-aws/pull/926
This moves the per-os-arch cleanup to its own step leaving the `cleanup` step to do the sweep for old resources that need deleting.
> Delete testing stacks in parallel

- .gitmodules
- packer/linux/conf/buildkite-agent/hooks/environment
- packer/linux/conf/buildkite-agent/hooks/pre-command
- packer/windows/conf/buildkite-agent/hooks/environment
- packer/windows/conf/buildkite-agent/hooks/pre-command
This brings in and enables the retry behaviour for docker login in both plugins, something that has proven to be reasonably flakey of late.
> Bump ECR and docker-login plugins

- .buildkite/steps/launch.sh
- templates/aws-stack.yml
Subsequent to https://github.com/buildkite/elastic-ci-stack-for-aws/pull/928 I found more resource ordering issues.
Similar to that change which ensures the IAM control pane continues to allow instances to `autoscaling:TerminateInstanceInAutoScalingGroup` under stack deletion, this change aims to enforce a delete ordering on the VPC resources such that the instances continue to have the _network access_ needed to instigate that terminate action. Previously there was no order dependency on the route table or route table to subnet association. Under stack deletion we could rip the networking out from under the instances again preventing them from ever being able to self terminate. This was fine so long as the instances weren’t protected from scale in because the ASG would initiate …
> Fix resource ordering

- packer/linux/conf/bin/bk-install-elastic-stack.sh
We at NEAR use a custom AMI, recently the update of the stack started failing due to a failure while creating the buildkite-agent binary symlink:
```
Dec  1 18:08:22 ip-10-0-2-221 user-data: ln: failed to create symbolic link ‘/usr/bin/buildkite-agent’: File exists
Dec  1 18:08:22 ip-10-0-2-221 user-data: ++ on_error 113
Dec  1 18:08:22 ip-10-0-2-221 user-data: ++ local exitCode=1
Dec  1 18:08:22 ip-10-0-2-221 user-data: ++ local errorLine=113
Dec  1 18:08:22 ip-10-0-2-221 user-data: +++ curl -X PUT -H 'X-aws-ec2-metadata-token-ttl-seconds: 60' --fail --silent --show-error --location http://169.254.169.254/latest/api/token
Dec  1 18:08:22 ip-10-0-2-221 user-data: ++ local token=AQAAAOpIVEeW-ZgjyDYWEQLzrBRHKV7UxYgIi3Rm0BON3WXY1661Aw==
Dec  1 18:08:22 ip-10-0-2-221 user-data: ++ [[ 1 != 0 …
```
> fix: force symlink override if exists

- packer/linux/scripts/install-docker.sh
[buildx](https://github.com/docker/buildx) v0.5.1 was released on December 15, 2020. Since then there have been a number of releases, introducing features and fixing defects. It would be awesome to take advantage of these changes in our Buildkite CI builds!
Upgrade buildx from 0.5.1 to 0.7.1.
See the [buildx release notes](https://github.com/docker/buildx/releases) for details of the changes.
> Bump buildx from 0.5.1 to 0.7.1

- templates/aws-stack.yml
Recognise [newish](https://aws.amazon.com/blogs/aws/join-the-preview-amazon-ec2-c7g-instances-powered-by-new-aws-graviton3-processors/) `c7g.*` instance types as ARM so they use the `linuxarm64` AMI.
This PR is a subset of https://github.com/buildkite/elastic-ci-stack-for-aws/pull/969 …  there are other new ARM instance types, but this brings us to the limit of 10 conditions within `Fn::Or` in CloudFormation. Of the new instance type, `c7g` sounds most generally useful for CI workloads, maybe, and has been [specifically requested](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/969#issuecomment-1010509706).
> Recognise c7g instances as ARM

- templates/aws-stack.yml
This PR is a retry of https://github.com/buildkite/elastic-ci-stack-for-aws/pull/969 and supersedes it – the problem encountered there is that the CloudFormation [intrinsic function `!Or`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#intrinsic-function-reference-conditions-or) can only take between minimum 2 and maximum 10 arguments.
To address that issue i've perpetrated a bit of a hack, but it works.  Basically, split the conditional into a sub-clause for each instance family.
I don't recall if it's possible to switch base branch in already-created PRs, so here's a fresh one.  Apologies to the authors of the previous one – feel free to cherry-pick my changes if you prefer to keep the original PR open.
> Add support for additional ARM/Graviton instance types, reprise

- packer/linux/conf/bin/bk-configure-docker.sh
Adds the `EnableDockerClassCSubnets` flag which configure the Docker address pool to allocate `/24` subnet instead of the default `/16` and`/20`.
We're using large instance with nvme storage to leverage the docker cache in our build (`c5d.12xlarge` with 12 agents), we often get the following error:
```
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
```
This is because the default docker address pool configuration is as follow:
Type | Default Size | Default Pool
-- | -- | --
global | /24 | 10.0.0.0/8
local | /16 | 172.17.0.0/12
local* | /20 | 192.168.0.0/16
\* _Local networks are allocated from 172.17.0.0/12, and then 192.168.0.0/16 once 172.17.0.0/12 is exhausted._
This means you'll get the error once 32 networks are …
> Allow Docker address pool customisation

- templates/aws-stack.yml
Clarify `BuildkiteAgentToken` vs `BuildkiteAgentTokenParameterStorePath` in the stack parameter descriptions.
I don't think `BuildkiteAgentToken` is _clearly_ deprecated (yet?), so don't mention that here just now.
I think we should first revisit the dynamics/security of [CloudFormation `NoEcho` parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#parameters-section-structure-properties), and the ability to create encrypted SSM Parameter Store parameters from CloudFormation.
When `BuildkiteAgentToken` is provided, we currently store it in SSM Parameter Store anyway:
```yaml
BuildkiteAgentTokenParameter:
Type: AWS::SSM::Parameter
Condition: CreateAgentTokenParameter
Properties:
Name: !Sub "/${AWS::StackName}/buildkite/agent-token" …
```
> BuildkiteAgentToken vs BuildkiteAgentTokenParameterStorePath clarity.

- packer/linux/buildkite-ami.json
There's an issue confirmed by AWS support with the more recent 20220218 release where instances using AWS Nitro to fail to run cloud-init, so this PR adjusts our Packer AMI build process to use the 20220207 AL2 AMI as the base image, which doesn't have the issue.
We'll revert this PR when AWS support have confirmed that the issue is resolved.
> Use Amazon Linux 2 AMI with working cloud init

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
We just released the buildkite agent [v3.34](https://github.com/buildkite/agent/releases)! This MR updates the elastic stack to point at the new version of the agent.
> Bump buildkite-agent to v3.34.0

- packer/linux/buildkite-ami.json
Reverts buildkite/elastic-ci-stack-for-aws#995
New AMIs have been released that fix this issue, so we can safely go back to using the latest AMIs :)
> Revert "Use Amazon Linux 2 AMI with working cloud init"

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
We released Agent v3.35 earlier today; we should bump the elastic stack to use this version and include it in Elastic Stack v5.8.
> Bump buildkite-agent to v3.35.0

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
This PR updates the elastic stack to use the latest version of the buildkite agent, v3.35.1. This version fixes an issue with file permissioning.
> Bump buildkite-agent to v3.35.1

- templates/aws-stack.yml
All references to AWS variables (eg, AWS::Region) have been enclosed
within quotations.
Omitting the quotes can cause some YAML parsers to fail.
> Add quotes around AWS variables

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
This PR updates the version of the buildkite agent used by the elastic stack to the latest, [v3.35.2](https://github.com/buildkite/agent/releases/tag/v3.35.2). This version includes a bugfix for a race condition, as well as a couple of dependency updates.
> Bump buildkite-agent to v3.35.2

- packer/linux/scripts/install-docker.sh
[Docker buildx](https://github.com/docker/buildx) v0.8.0 has been released and includes a number of nice features. In particular, I'm excited about the new [remote cache support](https://www.docker.com/blog/image-rebase-and-improved-remote-cache-support-in-new-buildkit/). It would be awesome to take advantage of this in our Buildkite pipelines!
Upgrade buildx from 0.7.1 to 0.8.2.
See the [buildx release notes](https://github.com/docker/buildx/releases) for details of the changes:
- [v0.8.0 release notes](https://github.com/docker/buildx/releases/tag/v0.8.0)
- [v0.8.1 release notes](https://github.com/docker/buildx/releases/tag/v0.8.1)
- [v0.8.2 release notes](https://github.com/docker/buildx/releases/tag/v0.8.2)
> Bump Docker Buildx from 0.7.1 to 0.8.2

- templates/aws-stack.yml
This adds the option to enable EC2 detailed monitoring for instances.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-monitoring.html
> Add option to enable detailed EC2 monitoring

- packer/linux/buildkite-ami.json
It'd be awesome to make use of the new Linux kernel.
https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-linux-2-ami-kernel-5-10/
(untested)
> Bump Linux from 4.14 to 5.10

- templates/aws-stack.yml
With this new parameter, we can enable access from the instance to its tags via metadata.
This change does not break the current configuration, as defaults to the `disabled` value, with is the default one.
> Allow accessing tags via instance metadata

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
Agent 3.36.1 fixes a major issue where using the JSON log format could cause the agent to fail to start
> Bump buildkite-agent to v3.36.1

- templates/aws-stack.yml
Attempts to deploy a Buildkite elastic-ci stack via a role with permission boundary currently fail.  It looks like the autoscaling application doesn't apply the boundary condition ARN passed to the parent stack.  
These two PRs:
https://github.com/buildkite/buildkite-agent-scaler/pull/62
https://github.com/buildkite/elastic-ci-stack-for-aws/pull/984
address this.
> Permissions boundary for Autoscaling application

- packer/linux/conf/bin/bk-install-elastic-stack.sh
The elastic stack sends its startup logs to the `/buildkite/elastic-stack/{instance_id}` log group in cloudwatch, which is basically a bash script with `set -x` enabled. As part of this process, we fetch the token from SSM Parameter store, but this is included in the output, meaning that the token gets leaked into cloudwatch logs, which are potentially much less privileged than the agent tokens themselves.
This PR disables set -x while we do secret things, and then turns it back on afterwards
> Don't accidentally send the token to logs on startup

- templates/aws-stack.yml
Avoid getting the following error when "Enforce CloudWatch log
encryption" is enabled:
```
"Your session has been terminated for the following reasons: We couldn't
start the session because encryption is not set up on the selected
CloudWatch Logs log group. Either encrypt the log group or choose an
option to enable logging without encryption."
```
> Fix IAM permissions for SSM session

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
Update `buildkite-agent` to [v3.37.0](https://github.com/buildkite/agent/releases/v3.37.0)
> Bump buildkite-agent to v3.37.0

- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/linux/conf/buildkite-agent/systemd/buildkite-agent.service
- packer/windows/conf/bin/bk-install-elastic-stack.ps1
- templates/aws-stack.yml
**🤔 Problem:** We recently released the [opentelemetry-tracing experiment](https://github.com/buildkite/agent/pull/1632) for the agent, but currently, it's tricky to use through the elastic stack for a couple of reasons:
- We don't currently expose the `--tracing-backend` argument as a cfn parameter
- At current, there's no easy way to pack arbitrary environment variables into the agents launched by the elastic stack. To use opentelemetry tracing, we need to supply an envar like `OTEL_EXPORTER_OTLP_ENDPOINT`, which tells the agent where to send its traces, and it's tricky/impossible to set this envar via the elastic stack.
**✅ Solution:** Fix those two things! 
- Make the tracing-backend config element settable through cloudformation, defaulting to `""`
- ~~Add a new cfn parameter called …
> Make tracing easier to configure

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
Agent [v3.38](https://github.com/buildkite/agent/releases/tag/v3.38.0) is out! We should use this in new versions of the elastic stack.
> Bump buildkite-agent to v3.38.0

- templates/service-role.yml
When I tried creating a new CI stack using the IAM role defined in `templates/service-role.yml`, I got the following error:
```
User: arn:aws:iam::XXX is not authorized to perform: lambda:TagResource on resource: arn:aws:lambda:XXX
```
I submit this pull request to add the missing permission `lambda:TagResource` to the IAM role.
> Add a missing permission in the service role

- .buildkite/steps/publish.sh
Moves the `Uploading templates` header to before all upload steps, to fix this:
> Move "Upload" header in publish.sh to before all uploads

- utils/log-collector
Fix for #1023 
This changes how we use the date command when gathering Lambda logs in the log-collector script, to allow support for both GNU and macOS-based `date` command usage.
> Fix log collector date command

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v5.11.1...v5.11.2)
- Fix log collector date command [#1048](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1048) (@jeremybumsted)
- Bump buildkite-agent to v3.39.1 [#1054](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1054) (@triarius)
- buildkite-agent v3.39.1 contains a security update. [buildkite/agent #1781](https://github.com/buildkite/agent/pull/1781)
> Bump CHANGELOG to v5.11.2

- goss.yaml
Sometime, docker images can take longer to download. This seem to have
caused some test flake recently.
For buildkite employees, see: https://buildkite.com/buildkite-aws-stack/buildkite-aws-stack/builds?branch=triarius%2Ftest-dcv2
for an example of test flake.
> Add timeout to goss docker commands

- README.md
The log group is `system` not `systemd`
> Fix typo in README about log collection

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v5.11.2...v5.12.0)
- Add docker compose v2 to linux [#1052](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1052) (@donbobka)
> Bump CHANGELOG for v5.12.0

- templates/aws-stack.yml
Our team would like to monitor this metric, see slack thread for more details: https://rippling.slack.com/archives/C03HS62QYQJ/p1668464627626499
> Enable GroupDesiredCapacity metric collection on ASGs by default

- templates/aws-stack.yml
As per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html#cfn-ec2-launchtemplate-blockdevicemapping-ebs-encrypted, add the option to indicate if the EBS volume is encrypted or not. Default value: `false`
(requested by a customer 🙂)
> Add property to indicate if the EBS volume is encrypted

- goss.yaml
- packer/linux/scripts/install-utils.sh
I was investigating some pipeline flakeyness and I think this will improve the situation. The previous default timeout was 10s, it is now 30s.
Bumping the version of [goss](https://github.com/goss-org/goss) is not necessary, but it should not hurt if the pipeline succeeds.
> Increase timeout for `docker info` goss test and bump goss to latest version

- templates/service-role.yml
This is necessary prior to merging https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1050.
Ideally we should rebase that PR over master and run a build on it again, however it's a contributed PR, so we may not expect that.
I have cherry-picked those commits and run a build on with the commits in this PR applied, and it seems to work: https://buildkite.com/buildkite-aws-stack/buildkite-aws-stack/builds/2884.
> Add permissions to service role to allow deployment and deletion of encrypted s3 buckets with Bucket Policy

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v5.13.0...v5.14.0)
- Add property to indicate if the EBS volume is encrypted [#1057](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1057) (@pzeballos)
- Enable GroupDesiredCapacity metric collection on ASGs by default [#1064](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1064) (@atticus-rippling)
- Bump buildkite-agent to v3.41.0 [#1069](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1069) (@triarius)
> Bump CHANGELOG for v5.14.0

- packer/linux/scripts/install-lifecycled.sh
[Full Changelog](https://github.com/buildkite/lifecycled/compare/v3.2.0...v3.3.0)
- Support configuring intervals for spot instance termination and autoscaling heartbeats [#97](https://github.com/buildkite/lifecycled/pull/97) (@stevenmatthewt)
> Bump lifecycled to v3.3.0

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v5.14.0...v5.15.0)
- Enable default bucket encryption for S3 and enforce SSL [#1050](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1050) (@ckornacker)
- Bump buildkite-agent to v3.42.0 [#1073](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1073) (@mitchbne)
- Bump Docker buildx from 0.8.2 to 0.9.1 [#1071](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1071) (@orien)
- Bump lifecycled to v3.3.0 [#1065](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1065) (@triarius)
> Bump CHANGELOG for v5.15.0

- packer/linux/conf/cloudwatch-agent/config.json
**This PR:** Adds a clause to the cloudwatch agent configuration in elastic stack instances to forward logs from `/var/log/secure` to a new Cloudwatch Logs stream, `/buildkite/auth/{instance_id}`. Here's an annotated (and slightly edited for clarity) sample of logs from that log stream:
```
// Attempting to log in with an invalid user
Jan 15 21:57:15 ip-10-0-2-201 sshd[3113]: Invalid user ben from 122.58.194.209 port 56616
Jan 15 21:57:15 ip-10-0-2-201 sshd[3113]: input_userauth_request: invalid user ben [preauth]
// oh noes, they're trying to get into the admin user
Jan 15 22:05:43 ip-10-0-2-201 sshd[3634]: Invalid user admin from 1.34.170.6 port 36540
Jan 15 22:05:43 ip-10-0-2-201 sshd[3634]: input_userauth_request: invalid user admin [preauth]
Jan 15 22:05:45 ip-10-0-2-201 sshd[3634]: …
```
> Push access logs to cloudwatch for linux instances

- .buildkite/pipeline.yml
- packer/linux/scripts/install-buildkite-agent.sh
- packer/linux/scripts/install-utils.sh
- packer/windows/scripts/install-utils.ps1
In response to [some recent CVEs in git](https://github.blog/2023-01-17-git-security-vulnerabilities-announced-2), we are updating the version of git installed on windows and linux to be v2.39.1.
Unfortunately for the linux AMIs, the version of the git-core pacakge avaliable in the default Amazon Linux 2 repos had not been updated to v2.39.1, so we are installing it from source.
> Bump git to v2.39.1

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v5.15.0...v5.16.0)
- Git is updated to v2.39.1 to address [recent vulnerabilities](https://github.blog/2023-01-17-git-security-vulnerabilities-announced-2/) [#1077](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1077) (@triarius)
- Access logs are now pushed to Cloudwatch for Linux instances [#1075](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1075) (@moskyb)
- Bump buildkite-agent to v3.43.0 [#1079](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1079) (@DrJosh9000)
> Update changelog for v5.16.0

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
[v3.43.1](https://github.com/buildkite/agent/releases/tag/v3.43.1) fixes a critical bug which makes any acquired job that runs for more than ~4.5 minutes fail
> Bump buildkite-agent to v3.43.1

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v5.16.0...5.16.1)
- Bump buildkite-agent to v3.43.1 [#1083](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1083) (@moskyb)
> Add changelog for 5.16.1

- templates/aws-stack.yml
`ec2messages:SendRepl` isn't a valid policy action. We've been getting error messages about invalid IAM policy in some of our accounts. I don't have the inside story from AWS here but I wonder if they have started being more strict on these
https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-setting-up-messageAPIs.html
Note this has not been tested by me yet, but looks more correct than the current state :-)
> correct invalid SSM policy action

- templates/aws-stack.yml
Adds the ability to customise the Name tag on the EC2 instances spawned by the ASG, defaults to "buildkite-agent" for backwards compatibility.
Might want to add a MinLength/MaxLength to this, happy to do so based on preferences.
> Add InstanceName parameter

- packer/linux/scripts/install-utils.sh
We started to build git from source to update it to a version that was not vulrenable to [CVE-2022-23521](https://nvd.nist.gov/vuln/detail/CVE-2022-23521), as the version in the Amazon Linux 2 core repo was not (and is still not) updated to a non vulrenable version.
However, even though we followed the [official instructions to build it from source](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git#_installing_from_source), there were was a discripency with the expected path for the system git config was [surfaced](https://github.com/buildkite/elastic-ci-stack-for-aws/issues/1085#issuecomment-1408595131) to us. Essentially, configuring the build with the `/usr` prefix moves the expected path for the system config from `/etc/gitconfig` to `/usr/etc/gitconfig`.
While we tried to …
> Build git 2.39.1 with rpm

- packer/linux/scripts/install-utils.sh
https://alas.aws.amazon.com/AL2/ALAS-2023-1923.html has dropped so we
can go back to installing git from the repos.
And I checked it's been updated for the repo that the docker equivalent is using at least.
```
🕙 13:20:33 ❯ docker run --rm -it amazonlinux:latest yum info git
Loaded plugins: ovl, priorities
amzn2-core                                                                                                                                                                                                                                                                                              | 3.7 kB  00:00:00
(1/3): amzn2-core/2/x86_64/group_gz …
```
> Return to installing git from the AL2 repos

- templates/aws-stack.yml
Otherwise they will launched with the amd64 ami and the stack will fail to
launch and be rolled back.
> Add support for c7gn, m7g, and r7g instance type classes to use the arm64 AMI

- packer/windows/conf/cloudwatch-agent/amazon-cloudwatch-agent.json
When log_stream_name is omitted from cloudwatch agent config, it defaults to the id of the instance sending the logs. This PR makes this choice explicit, bringing the windows config in line with the linux cloudwatch config
> Make cloudwatch log stream names explicit

- templates/aws-stack.yml
- templates/service-role.yml
We don't encourage anyone to create objects in these buckets that have public ACLs.
However, I don't think there is a use case for public access for the entire bucket though, so let's disable it.
> Explicitly Disable Public Access For Managed Secrets Buckets

- .buildkite/steps/copy.sh
- templates/aws-stack.yml
This will allow using a development version of the buildkite-agent-scaler with the elastic-ci-stack. To allow customers to use in all our supported regions, the pipeline needs to be run with the environment variable `COPY_TO_ALL_REGIONS=true`.
> Make a parameter for buildkite-agent-scaler edititon and version

- templates/aws-stack.yml
With the new defaults from AWS stated in https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html we shouldn't rely on ACLs nor there's a need to manually update public access configuration as these will now be **_ON_** by default. 
Removing these two configurations should leave the buckets with the recommended AWS security settings.
**This issue is blocking new clients to quickly bootstrap Buildkite in their account**
Fixes: #1108
> fix: remove ACL from logging bucket

- packer/linux/conf/buildkite-agent/hooks/environment
The elastic stack assumed that when docker experimental CLI was enabled, that there was already a docker config.json file. This meant that if one wasn't present, the elastic stack environment hook would fail every time
> Fix error with docker experimental CLI

- templates/aws-stack.yml
The previous wording lead customers to believe that the command could be
specified with just its name. However, `sudoers(5)` requires that the
commands be specified with fully qualified paths. This lead some users
to believe that the stack was generating an invalid line in a sudoers
file when the error was the failure to fully qualify the path.
> Update description of BuildkiteAdditionalSudoPermissions parameter

- templates/aws-stack.yml
An old Python version was being used (3.7) for the AZ Rebalancing Lambda
This PR in particular is looking at [AZ Rebalancing Autoscaling Lambda](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/aws-stack.yml#L1295) - it was picked up that 3.7 is set as the Runtime
https://3.basecamp.com/3453178/buckets/23112918/card_tables/cards/6126980695#__recording_6127034819
Line 1295 to 1317:
https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/aws-stack.yml#L1295
> Bumping python from 3.7 to 3.10

- templates/aws-stack.yml
We think using % of on demand and a spot allocation strategy is the more modern way of controlling the proportion of spot instances used. We have wanted to deprecate `SpotPrice` for some time now: https://github.com/buildkite/elastic-ci-stack-for-aws/issues/792
I've chosen to keep the default SpotAllocationStrategy to be `capacity-optimized` as it was in v5.
Make `capacity-optimized` the default spot allocation strategy
Amazon's recommended strategy is `price-capacity-optimized`: https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_InstancesDistribution.html but the default strategy for a InstancesDistribution is `lowest-price`.
In the elastic ci stack v5, we overrode the default and set it to `capacity-optimized`.
For a CI system, I think the strategy with the lowest risk of …
> Remove `SpotPrice` parameter and add parameter `SpotAllocationStrategy`

- .buildkite/pipeline.yml
- packer/windows/scripts/install-docker.ps1
The way we were installing Docker EE has stopped working. But, it seems to already be installed in the base AMI.
> Don't (re)install docker (on Windows)

- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/windows/conf/bin/bk-install-elastic-stack.ps1
Fixes: [agent/#2149](https://github.com/buildkite/agent/issues/2149)
I've tested it with `BuildkiteAgentTimestampLines=true` for linux/amd64 here:: https://buildkite.com/nepas-test-org/test-pipeline/builds/283#01889f0b-68e2-4180-92ce-41facbb96279
It's run with `BuildkiteAgentTimestampLines=false` in the CI jobs for linux/amd64, linux/arm64 and windows/amd64.
> Enable ansi-timestamps iff BuildkiteAgentTimestampLines is false

- .buildkite/steps/publish.sh
With v6, we will be renaming the default branch to main using the GitHub UI. When this change is made, the next build on the main branch won't push a stack template to the same location. So let's push to both locations for now.
> Publish to both `main` and `master` for the time being

- templates/aws-stack.yml
When the InstanceName parameter is the empty string, use the stack name instead.
> Default InstanceName to stack name

- .buildkite/steps/launch.sh
- templates/aws-stack.yml
Note that `InstanceTypes` MUST be added to the changelog.
IntanceType -> InstanceTypes
This has been extended to take up to 4 instance types.
ManagedPolicyARN -> ManagedPolicyARNs
Seems to have always taken a comma separated list of ARNs, so it should be plural.
Also add i4g to the arm64 instance types. This is needed to select the right AMI for them.
> Pluralise some parameters and add i4g

- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/linux/scripts/install-docker.sh
We use a method documented by docker to install some tools necessary for building (and running) multiarch docker images. See https://docs.docker.com/build/building/multi-platform/
Previously we did this entirely in the startup script `packer/linux/scripts/install-docker.sh`. However, as was revealed in dogfooding, launching many instances at the same time could cause the startup script to fail due to docker hub rate limits. Instead, we can pull the image when the AMI is being built by packer, and then run the installation in the startup script.
Why not pull and run when building the AMI? Running multiarch images in CI failed when I tried to do that: https://buildkite.com/buildkite-aws-stack/buildkite-aws-stack/builds/3275
> Pull docker image used for qemu binfmt in packer

- templates/aws-stack.yml
This is useful for users that are doing blue-green deployments and want the
(eg blue) stack to be able to be scaled in to 0 instances while the green
stack is fully scaled out.
> Allow the MaxSize to be 0

- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/windows/conf/bin/bk-install-elastic-stack.ps1
- templates/aws-stack.yml
This keeps the parameter name the same, but otherwise is the same as https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1123
> Backport dexperimentifing git-mirrors

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
Use https://github.com/buildkite/agent/releases/tag/v3.49.0
Related:
- https://github.com/buildkite/agent/pull/2167
> Bump buildkite-agent to v3.49.0

- packer/linux/conf/bin/bk-install-elastic-stack.sh
It's in /usr/bin/cfn-signal now, which should be in the $PATH
> Fix path to cfn-signal in install scripts

- packer/linux/conf/bin/bk-install-elastic-stack.sh
It was found on Amazon Linux 2023 that the default 10s grace period was
insufficient to allow the bootstrap to tear down cleanly when a job is
cancelled from the Buildkite API.
> Increase cancel grace period to 60s

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v5.21.0...v6.0.0-beta1)
- Upgrade base image to Amazon Linux 2023 [#1122](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1122) (@triarius)
- Many packages have been added, upgraded, or removed since Amazon Linux 2. We've explicitly called out what's been intentionally left out by us below. Refer to [docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html](https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html) for the changes Amazon have made.
- Publish template to both `main` and `master` [#1129](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1129) (@triarius)
- Increase job cancel grace period to 60s [#1144](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1144) …
> Update changelog for v6.0.0-beta1

- packer/linux/conf/bin/docker-compose
- packer/linux/scripts/install-docker.sh
Making /usr/bin/docker-compose a symlink or copy of the docker compose plugin binary is something that is increasingly popular. Indeed, this is now the only way to install a standalone `docker-compose` executable on Linux that's documented by docker: https://docs.docker.com/compose/install/standalone/#on-linux
So we did this in Elastic CI Stack for AWS v6 as well.
Unfortunately, this breaks certain workflows in the docker-compose plugin, which assumes that the `docker-compose` in the $PATH is docker-compose v1.
Arguably, the docker-compose plugin should default to v2 as v1 is EOL, but that is a breaking change. In the interim, we can prepend `--compatibility` to the docker-compose command to ensure that the plugin works as expected.
While I was in the area, I bumped the versions of docker …
> Create script to prepend `--compatibility` flag to docker-compose

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.0.0-beta1...v6.0.0-beta2)
- Bump docker compose to v2.20.0 and buildx to v0.11.1 [#1150](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1150) (@triarius)
- Reorganize build scripts to restart docker after installing qemu [#1149](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1149) (@triarius)
- Fix issues with docker-compose plugin by creating a script to prepend `--compatibility` flag to docker-compose [#1148](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1148) (@triarius)
> Update changelog for v6.0.0-beta2

- CHANGELOG.md
- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v5.22.0...v5.22.1)
- Bump buildkite-agent to v3.50.2 [#1161](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1161) (@triarius)
> Bump buildkite-agent to v3.50.2

- .buildkite/pipeline.yml
This will clean up the test stacks, even if the test fails.
> Set `allow_dependency_failure: true` on stack cleanup jobs

- packer/linux/conf/buildkite-agent/hooks/environment
It's useful to use a different exit status when the environment hook fails
so that customers can build retry logic into their pipelines.
Closes: \#845
I highly recommend reviewing with whitespace disabled.
> Exit status 2 when environment hook fails

- CHANGELOG.md
- README.md
- docs/updating-agent.md
- templates/aws-stack.yml
It's not clear from the previous name that this only affects buildkite-agent-scaler.
Also rename some occurrences of master to main.
> Rename `EventScheduleRate` to `ScalerEventScheduleRate` and include it in the changelog for v6

- Makefile
- packer/linux/conf/aws/config
- packer/linux/scripts/install-buildkite-agent.sh
It can cause jobs to hang if he cli returns results that are shown in a 
client side pager (like less). This method of disabling the pager is 
described in
https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html#cli-usage-pagination-clientside
I've also manually disabled it at certain places in the CI for this pipeline as it was in this pipeline that the issue first appeared to our knowledge.
> Disable pager for aws-cli v2 for the buildkite-agent user

- templates/aws-stack.yml
Expose parameter add on https://github.com/buildkite/buildkite-agent-scaler/pull/94 to the elastic CI stack CloudFormation template.
> Add ScalerMinPollInterval param

- packer/windows/buildkite-ami.json
- packer/windows/scripts/install-docker.ps1
The series of AMIs we used to base the windows elastic stack off of has been yanked. It had docker installed by default. In this PR, we use a more standard window AMI and install docker CE using a script maintained by Microsoft that is documented here: https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1
> Use windows server 2019 base image and docker ce

- packer/linux/conf/buildkite-agent/hooks/environment
In POSIX shells, `set -e` is not respected in certain contexts. One of these is: if it is in a function that is called on the left of a `||`.
See https://stackoverflow.com/questions/19789102/why-is-bash-errexit-not-behaving-as-expected-in-function-calls
We previously attempted to run this script in a function and exit status 2 if there was an error, but this was not working due to the above. Since it was not working, I took the liberty to change the exit code. Exit code 2 is too overloaded in my opinion.
I chose 53. This number looks like "S3", failure to network with which, could be the source of some transient failure of this hook.
I recommend review with whitespace changes hidden.
> Fix `set -e` fails from env hooks

- goss.yaml
- packer/linux/conf/ssh/systemd/refresh_authorized_keys.service
- packer/linux/scripts/install-buildkite-utils.sh
Fixes #1183 — I don't think the systemd units responsible for refreshing authorized keys are being copied into the right place when the AMI is baked. This copies the approach of install-docker:
https://github.com/buildkite/elastic-ci-stack-for-aws/blob/804061df748b42d3d40d5378892d84b2ff8e71ec/packer/linux/scripts/install-docker.sh#L19-L21
> Add missing authorized keys systemd units

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.1.0...v6.2.0)
- Change base image to Windows Server 2019 w/o containers and install Docker CE (v24.0.5) [#1180](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1180) (@triarius)
- Add cost allocation tags to EBS volumes [#1171](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1171) (@keatmin)
- Add missing authorized keys systemd units [#1184](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1184) (@sj26)
- Fix instance storage docker dir not created [#1181](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1181) (@triarius)
- Fix `set -e` fails from environment hooks [#1179](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1179) (@triarius)
> Populate CHANGELOG for v6.2.0

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
This puts the good release of the agent on the v5.22 branch
> Cherrypick bump buildkite-agent to v3.50.4

- CHANGELOG.md
The changelog has been updated on the branch stable-5-22, but its changes will not make it into main now that v6 is the stable release. This cherry-picks the change to the CHANGELOG back into main.
> Update CHANGELOG for v5.22.3

- packer/linux/scripts/install-utils.sh
This is required for `EnableInstanceStorage` on instances with multiple NVMe disks. It's not required for instances with just 1 NVMe disk.
Fixes: #1176
> Fix `mdadm` is not installed

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.2.0...v6.3.0)
- Bump buildkite-agent to v3.51.0 [#1193](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1193) (@triarius)
- Bump `git-lfs` to v3.4.0 [#1191](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1191) (@triarius)
- Update CHANGELOG for v5.22.3 [#1189](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1189) (@triarius)
- Fix `mdadm` is not installed, leading to broken instance storage when there is more than one volumes [#1190](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1190) (@triarius)
- Incorporated CHANGELOG for v5.22.3 [#1189](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1189) (@triarius)
> Bump CHANGELOG for v6.3.0

- CHANGELOG.md
I made a mistake in the previous commit. I forgot to remove the change
that updated the changelog with the changes in v5.22.3 (which is not on
the main branch) from the `Changed` section. It should be in the
`Internal` section, which was. In other words, the change was duplicated.
> Update CHANGELOG for v6.3.0 again

- .buildkite/pipeline.yaml
- .buildkite/steps/copy.sh
- .buildkite/steps/publish.sh
- docs/updating-buildkite-agent-scaler.md
- docs/updating-secrets.md
- templates/aws-stack.yml
While previously, the policy may have been different. I think it makes
sense to codify this policy:
Only builds for the latest stable tag on the main branch are published to:
- s3://buildkite-aws-stack/latest/aws-stack.yml
- s3://buildkite-aws-stack/aws-stack.yml
> Prevent tag builds from publishing a latest template when they are not "on the main branch"

- README.md
We're moving to the forum rather than Slack, so I'm adjusting the links before we do.
> Change the Community Slack links to Forum ones

- CHANGELOG.md
It was a difficult to decide whether this should be v6.3.1 or v6.4.0. But the agent incremented a minor version (v3.51.0 -> v3.52.1), so I think the elastic ci stack should too.
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.3.0...v6.4.0)
- Bump docker-compose to v2.20.3 [#1201](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1201) (@triarius)
- Bump buildkite-agent to v3.52.1 [#1200](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1200) (@triarius)
- Change the Community Slack links in documentation to Forum ones [#1199](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1199) (@mcncl)
- Prevent tag builds from publishing a latest template when they are not "on the main branch" …
> Update changelog for v6.4.0

- packer/linux/conf/bin/bk-mount-instance-storage.sh
- templates/aws-stack.yml
It's understandable for it to fail, but the result is that users that have misconfigured their stacks to use instance storage on an instance type that doesn't support it will experiance flapping instances.
Now, we will allow them to misconfigure their stack. Maybe later, we can feed a warning into the job logs, but there is presently no mechanism to do so in the agent.
> Fix instance storage mount script fails when instance storage not available

- packer/linux/buildkite-ami.json
At some point in the last couple of days, `al2023-ami-minimal-2023.0.*.*-kernel-*` stopped matching anything.
Is there a better filter?
> Fix ami_source_filter

- templates/aws-stack.yml
Including changing `ScalerEventScheduleRate` to `ScalerEventSchedulePeriod`.
> Update to scaler v1.6.0

- .buildkite/docker-compose.yml
It's not needed, and can cause missing library errors.
> Disable CGo

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v5.22.4...v5.22.5)
⚠️ This release fixes a medium-severity security vulnerability. We recommend upgrading to v6.7.1 or v5.22.5.
- Affected versions: All prior versions of Elastic CI Stack (except v5.22.5). v6.7.0 and v5.22.4 contained a partial fix.
- Impact: Privilege escalation to root on Linux agent instances
- Required privileges: Users that can run user-controlled commands on agents (e.g. by pushing a branch to a repo that triggers a build with those changes)
- Attack vector: A specially crafted build can abuse the `fix-buildkite-agent-builds-permissions` script to run commands as root on subsequent builds
- Fix: Improved input validation and file handling …
> Bump changelog for v5.22.5

- packer/linux/conf/bin/bk-configure-docker.sh
- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/linux/conf/bin/bk-mount-instance-storage.sh
Prior to this PR, the startup scripts had tracing enabled (set -x) which made them difficult to read. This PR disables tracing and adds manual logging to the startup scripts.
I've tried to log before performing an action, and log if it fails. If a file is written to, I also try to log what was written. If you compare the output of these logs (the cloudwatch log group `/buildkite/elastic-stack/<instance-id>`) before an after this PR, the after has more information and is easier to follow (IMO).
I've also removed some use of `>&2`, see https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1230/commits/e8184d8ff077abdce8cdd0ee2336105196762aed.
> Improve logging for startup scripts on linux

- packer/linux/conf/bin/bk-configure-docker.sh
- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/linux/conf/bin/bk-mount-instance-storage.sh
- packer/linux/conf/docker/systemd/docker-gc.service
- packer/linux/conf/docker/systemd/docker-low-disk-gc.service
- packer/linux/scripts/install-docker.sh
The intention was always for it to be pulled when the AMI is built, and just run when then instance is started, but it turns out the garbage collector was running before the docker setup script, so the image was being pulled on every instance start.
This PR fixes this by only enabling the timers after docker has been configured and the qemu binfmt image has run.
I've also added more comments around the mechanism by which the digest of the qemu binfmt image is passed from the packer build scripts to the startup script, as it was the source of some confusion. As well as more logging in general.
Closes: #1229
> Fix qemu binfmt image is pulled during instance startup

- templates/aws-stack.yml
- allow hyphen in InstanceTypes input
- I want to add the instance type `m7a.metal-48xl` which currently fails
- Once this is fixed, can we also have it brought back to the 5.x branch?
- Closes https://github.com/buildkite/elastic-ci-stack-for-aws/issues/1227
- See regexr test https://regexr.com/7krdq
> fix: allow hyphen in InstanceTypes

- templates/service-role.yml
We required these extra permissions when we made the switch to using the service role. I'm not sure what permutation of parameters added these extra requirements, but I don't think it would be unique for our org.
> fix: Add Missing Service Role Permissions

- templates/service-role.yml
When upgrading a stack using the service role, and the version of the autoscaler lambda
changes, this permission is needed.
> Add `lambda:UpdateFunctionCode` to service role

- templates/aws-stack.yml
This change introduces a fix to AWS Lambda functions being migrated from the go 1.x runtime to the new Custom Runtime on Amazon Linux 2, see [this post](https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linux-2/).
The changes to the Agent Scaler can be found in https://github.com/buildkite/buildkite-agent-scaler/pull/108 to support this new Elastic Stack version.
Fixes #1203.
**Note**: Customers upgrading existing stacks may not be able to upgrade to the new version, there are more details in the following comments: https://github.com/buildkite/elastic-ci-stack-for-aws/issues/1172#issuecomment-1697304023, https://github.com/buildkite/elastic-ci-stack-for-aws/issues/1172#issuecomment-1698421029
The current method of …
> Updated Agent Scaler version to 1.7.0

- templates/aws-stack.yml
- Fixes an error encountered when we attempt to unmarshal the YAML template via our internal tooling
- After experimentation, I discovered that one I wrapped quotes around `AWS::StackName` our tooling was able to parse the template successfully
- We perform some wrangling of CFN parameters via an internal CLI tool. As part of this process, the tool parses a YAML template to figure out which parameters are required as input
- Discovered this yaml parsing error when I was attempting to smoke test our upgrade to the `v6` elastic stack
- My best guess is that the yaml unmarshalling process doesn't like `::` unless it's quoted and/or escaped? 🤷
> fix: wrap quotes around AWS::StackName

- packer/linux/scripts/install-utils.sh
Rsys is no longer installed on Amazon Linux 2023, see: [changelog](https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html#journald)
This re-adds the rsyslog daemon and starts it.
> fix: re-add rsyslog

- .buildkite/pipeline.yaml
- .buildkite/steps/copy.sh
- Makefile
- packer/linux/buildkite-ami.pkr.hcl
- packer/windows/buildkite-ami.pkr.hcl
The format of the tags will be:
```
Key=AgentVersion,Value=x.y.x
Key=Version:x.y.z,Value=true
```
Since the same AMI can be used for multiple Elastic CI Stack Versions, we can't just have one `Version` tag key and need to have a separate tag key for each version of the Elastic CI Stack.
The Agent Version is not like that and is known when the image is built by Packer. Note, however, that if users elect to use the "beta" or "edge" channels for agents, the version of the agent may differ from that of the tag.
> Tag Images with Agent and Elastic CI Stack Version

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.7.1...v6.8.0)
- Bump Agent Scaler version to v1.7.0. This updates the lambda runtime to `provided.al2` from the deprecated `go1.x` [#1236](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1236) (@HugeIRL)
Note: depending on how you upgrade existing stacks, you may not automatically be upgraded to v1.7.0 of Buildkite Agent Scaler. See [here](https://github.com/buildkite/elastic-ci-stack-for-aws/issues/1172#issuecomment-1697304023) for a work around to this known issue.
- Bump buildkite-agent to v3.56.0 [#1237](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1237) (@triarius)
- Bump docker-compose to v2.22.0 [#1234](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1234) …
> Update changelog for v6.8.0

- templates/service-role.yml
I've been using the service role to manage my stacks recently, and I
observed updates failing due to missing permissions.
> Add more missing service role IAM permissions

- Makefile
- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
Update the agent used to 3.57, and use gsed instead of sed in bits of the makefile where platform-dependent functionality is used; gnu sed allows no arg to the `-i` flag but the version of sed that macOS uses (which is from freeBSD) requires an empty string as an arg for `-i` to get the same behaviour.
> Agent 3.57

- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/linux/conf/buildkite-agent/scripts/terminate-instance
- packer/windows/conf/bin/bk-install-elastic-stack.ps1
- packer/windows/conf/buildkite-agent/scripts/terminate-instance.ps1
- templates/aws-stack.yml
This is a different implementation of the same goal as #1225, but we found when testing that PR that the instances would NOT terminate on linux because the buildkite-agent user does not have permission to shutdown the instance. Rather than granting it this permisison, in this PR we mark the instance as unhealthy if
1. The idle period has expired and the agent has shutdown.
1. The call to the AWS API to terminate the instance and decrement the desired capacity fails.
1. `BuildkiteTerminateInstanceAfterJob` is enabled.
Closes: #1225
> Mark last instance unhealthy if `BuildkiteTerminateInstanceAfterJob` is enabled

- templates/aws-stack.yml
This was added in v6.7.0, but we missed adding it to the interface.
> Fix `ScalerEventSchedulePeriod` was missing from interface

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.8.0...v6.9.0)
- Instances in ASGs at their minimum capacity will now be correctly terminated when `BuildkiteTerminateInstanceAfterJob` is enabled [#1245](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1245)
- Fix ScalerEventSchedulePeriod was missing from interface [#1243](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1243)
- Update buildkite-agent to v3.57.0 [#1247](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1247) (@moskyb)
- Add more missing service role IAM permissions [#1244](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1244) (@triarius)
- Update README to show we are on Amazon Linux 2023 now …
> Update changelog for v6.9.0

- templates/aws-stack.yml
Add the various graviton3 `*7gd` instance types (w/ local nvme instance storage)
I tried to spin up a queue with `c7gd.8xlarge` led to a failure due to the stack trying to use the amd64 instead of arm64 image. This should resolve that.
> CloudFormation stack, rollback requested (ROLLBACK_COMPLETE): ["The following resource(s) failed to create: [AgentAutoScaleGroup]. Rollback requested by user." "Resource handler returned message: \"You must use a valid fully-formed launch template. The architecture 'arm64' of the specified instance type does not match the architecture 'x86_64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type …
> add support for graviton3 with local nvme

- Makefile
Not all EC2 Instance Types are available in each AWS Region, for example, in `eu-west-2` the `m7` EC2 Instance Types are not available - yet - so running the Makefile commands using the defaults will result in failing to launching the EC2 Instances for AMI Creation with the following error message:
```
Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
```
Potential future usuablity improvement could be add some kind of check(s)?
> Enable optionally changing EC2 Instance Types used for AMI Creation

- CHANGELOG.md
This week I was debugging a docker performance regression in one of our pipelines, and for a while I wondered if the docker version was a problem.
It turned out not to be, but while investigating I discovered the recent 6.8.0 elastic stack release included a reasonably large docker upgrade from 20.10.25 to 24.0.5.
The 20.10 series started in late 2020, and the 24.0 series was released in May 2023. I expect most folks docker based pipelines will continue to work unmodified, but there might be edge cases from a 3+ year jump. Maybe this will save folks a bit of debugging time.
The v3.7.0 release also included a couple of less notable version bumps, but I'm not sure if they're worth including.
* containerd 1.6.19 to 1.7.2
* runc 1.1.5 to 1.1.7
> Mention docker 20.10.25 to 24.0.5 upgrade in v6.8.0 changelog

- .buildkite/docker-compose.yml
- .buildkite/pipeline.yaml
- .buildkite/steps/build-fixperms.sh
- .buildkite/steps/packer.sh
- Makefile
- packer/linux/buildkite-ami.pkr.hcl
- packer/linux/scripts/install-buildkite-utils.sh
In #1219 I overlooked the Makefile, which is used by both the pipeline (.buildkite/steps/packer.sh) and to build the stack without using the pipeline.
The result was that anyone just running `make clean && make packer` will be missing the new binary.
For now fix-perms is specific to the stack, so while one option is to split it into its own repo and generalise it and put a ribbon on it, the other is to make the Makefile responsible for building it, and using `docker` to run a container from the Makefile has precedent (hashicorp/packer).
> Build fix-perms in Makefile

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.9.0...v6.10.0)
- Enable optionally changing EC2 Instance Types used for AMI Creation [#1252](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1252) (@tomowatt)
- Add support for graviton3 with local nvme [#1253](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1253) (@joemiller)
- Build fix-perms in Makefile [#1254](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1254) (@DrJosh9000)
- Bump agent version to v3.58.0 [#1256](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1256) (@DrJosh9000)
- Mention docker 20.10.25 to 24.0.5 upgrade in v6.8.0 changelog [#1249](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1249) (@yob)
> Update changelog for v6.10

- packer/linux/conf/bin/bk-install-elastic-stack.sh
- templates/aws-stack.yml
Following expectations from docs here https://buildkite.com/docs/agent/v3/configuration
We should allow users to configure the cancellation grace period.
- BuildkiteAgentCancelGracePeriod to `aws-stack.yml` (default 60)
> Added BuildkiteAgentCancelGracePeriod option to linux stack

- .buildkite/pipeline.yaml
- .buildkite/steps/publish.sh
[This](https://buildkite.com/buildkite-aws-stack/buildkite-aws-stack/builds/4208#018b5fc8-d1a6-47ea-9c32-c6157f3aaba8) build was supposed to publish a "latest" template, but it did not because the tag did not exist in the local git repo.
I don't know exactly why it did not work (git mirrors is looking like a likely culprit), but we should error the tag build if the tag is not present.
> Ensure tag builds have the tag

- templates/aws-stack.yml
The current `InstanceTypes` AllowedPattern allows hyphens for the first instance type listed, but not for the following ones. This is a tiny tweak to allow hyphens for all instance types listed.
Example failing case: `m7i.xlarge,m7i-flex.xlarge` will fail because the hyphen isn't the first type listed. The error message will be: `ValidationError: Parameter InstanceTypes failed to satisfy constraint: must contain 1-4 instance types separated by commas. No space before/after the comma.`
> fix: allow hyphens in all `InstanceTypes` values

- templates/aws-stack.yml
I've selected 1000 as a default value for RootVolumeIops, it will be ignored if RootVolumeType is not io1 or io2. In those cases, customers will want to specify a custom value.
Fixes: #960, #790
> Add RootVolumeIops parameter to allow io1 and io2 RootVolumeTypes

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.10.0...v6.11.0)
- BuildkiteAgentCancelGracePeriod option to linux stack [#1258](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1258) (@njgrisafi)
- RootVolumeIops parameter to allow io1 and io2 RootVolumeTypes [#1269](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1269) (@triarius)
- Allow hyphens in all `InstanceTypes` values [#1266](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1266) (@pH14)
- Bump agent to v3.60.1 [#1260](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1260) (@DrJosh9000) [#1265](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1265) (@moskyb) [#1271](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1271) (@triarius)
- …
> Update CHANGELOG for v6.11.0

- packer/linux/conf/bin/bk-mount-instance-storage.sh
- templates/aws-stack.yml
Older versions of the stack did not mount /tmp in a tmpfs (Amazon Linux 2 behaviour). 
Newer versions do, by default (Amazon Linux 2023 behaviour). 
Some people would like the older behaviour.
> Add MountTmpfsAtTmp parameter

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.11.0...v6.12.0)
- Add MountTmpfsAtTmp parameter [#1274](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1274) (@DrJosh9000)
- Bump buildkite-agent to v3.61.0 [#1275](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1275) (@DrJosh9000)
> Bump changelog for v6.12.0

- Makefile
- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
I also added a comment to the Makefile about how to get `gsed` on mac because I had to look it up.
Agent release: https://github.com/buildkite/agent/releases/tag/v3.62.0
> Bump agent version to v3.62.0

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.12.0...v6.13.0)
- Bump agent version to v3.62.0 [#1280](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1280) (@tessereth)
> Update CHANGELOG for v6.13.0

- templates/aws-stack.yml
We have been experiencing issues with `agent lost (-1)` after investigating with AWS support this turned out to happen when an instance with a gp3 root volume hits its throughput limit and becomes unresponsive. By exposing this people will be able to bump it and hopefully resolve their throttling issues. 
Resolves #1026
> feat: Allow RootVolumeThroughput to be set for gp3 root volumes

- templates/aws-stack.yml
I want to adjust the Iops for a gp3 volume, but the current condition prevents `RootVolumeIops` from being passed through.
> Allow specifiyng Iops for gp3

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.13.0...v6.14.0)
- A parameter, `RootVolumeThroughput`, to be set for gp3 root volumes [#1282](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1282) (@cmanou)
- Allow specifying IOPS for gp3 [#1283](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1283) (@bradleyayers)
- Bump buildx to v0.12.1 and docker-compose to v2.24.4 [#1284](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1284) (@triarius)
> Update CHANGELOG.md for v6.14.0

- packer/windows/conf/buildkite-agent/hooks/environment
`~` can resolve to `/c/Windows/system32/config/systemprofile` when we start the agent. We make sure it's in `/c/buildkite-agent/cfn-env` when we build the AMI, so let's reference it as being there.
I ran into this issue when doing some manual iteration on a Windows elastic stack. It should not be an issue outside of this, as there are integration tests that run jobs on Windows Elastic stacks.
> Fix path for cfn-env on windows elastic stack

- templates/aws-stack.yml
It comes from a general mandate to preserve logs generally for more time.
Close #1277 ... in case this is useful.
> Stack: support configurable log retention days.

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.14.0...v6.15.0)
- For linux, the Base AMI has been updated to [Amazon Linux 2023.3.20240131](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.3.20240131.html) which fixes [CVE-2024-21626](https://nvd.nist.gov/vuln/detail/CVE-2024-21626).
- Support configurable log retention for scaler with the `LogRetentionDays` parameter. [#1278](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1278) (@grahamc)
- Fix path for cfn-env on windows elastic stack did not always work [#1286](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1286) (@triarius)
> Update CHANGELOG for v6.15.0

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
Update agent version number from `3.63.0` to `3.65.0` in installation scripts.
Buildkite Agent Version 3.65.0 release: https://github.com/buildkite/agent/releases/tag/v3.65.0
> Update Agent Version to 3.65.0

- packer/linux/scripts/install-docker.sh
[Docker buildx](https://github.com/docker/buildx) v0.13 has been released!
Upgrade buildx from 0.12.1 to 0.13.0
See the [buildx release notes](https://github.com/docker/buildx/releases) for details of the changes:
- [v0.13.0 release notes](https://github.com/docker/buildx/releases/tag/v0.13.0)
> Bump Docker buildx to v0.13.0 and Docker Compose to v2.24.6

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.16.0...v6.17.0)
- Bump Docker to v25.0.3 from repositories configured for the [Base Amazon Linux 2023 AMI](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.3.20240304.html)
- Update agent to 3.66 [#1301](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1301) (@moskyb) [#1295](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1295) (@matthewborden)
- Bump Docker buildx to v0.13.0 and Docker Compose to v2.24.6 [#1299](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1299) (@orien)
- Update ECR plugin to v2.8.0 [#1300](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1300) (@lucaswilric)
Fixes: …
> Update CHANGELOG for v6.17.0

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.17.0...v6.18.0)
- Bump agent version to v3.67.0 [#1303](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1303) (@DrJosh9000)
> Bump changelog for v6.18.0

- packer/linux/buildkite-ami.pkr.hcl
The Amazon packer builder plugin [removed](https://github.com/hashicorp/packer-plugin-amazon/pull/191) this default tag in v1.0.9. We don't pin or lock a specific version of the plugin so I'm not sure when we began using it, but on [at least one occasion](https://buildkite.com/buildkite-aws-stack/buildkite-aws-stack/builds/4323#018d8289-2be8-4e2c-b489-9cbbaa25cc32/135-228), a CI build was killed before Packer finished running and terminated the instance.
Because it was not tagged, it was also not terminated up by `cleanup.sh` which would normally occur after the next successful build.
This PR restores the default tag so it can be cleaned up.
> Restore "Packer Builder" tag for Packer instances

- packer/linux/buildkite-ami.pkr.hcl
GuardDuty is complaining to us about Packer instances being probed on their SSH port, which by default is open to the world.
Packer can be configured to allow connections only from a particular CIDR, however elastic-stack runs in the `main` VPC on `10.16.0.0/16`, whereas Packer runs in the default VPC on `172.31.0.0/16`, and there is no routing configured between them.
Apparently they communicate over the public internet, so this seems the simplest method to block public SSH.
There's a few other options to consider, I'm happy to go down one of these paths instead:
* Launch the Packer instances in the same VPC as the Elastic Stack by hard coding `vpc_id` (brittle if you update the stack)
* Launch the Packer instances in the same VPC as the Elastic Stack by setting `vpc_filter` (we …
> Only allow SSH to reach Packer instance from Elastic Stack

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.18.0...v6.19.0)
- Bump agent version [#1314](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1314) (@patrobinson)
- Only allow SSH to reach Packer instance from Elastic Stack [#1308](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1308) (@steveh)
- Restore "Packer Builder" tag for Packer instances [#1307](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1307) (@steveh)
> Create release v6.19.0

- .buildkite/pipeline.yaml
- .buildkite/steps/launch.sh
- goss.yaml
- packer/linux/buildkite-ami.pkr.hcl
This PR is verifying the changes / fix for:
https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1312 -> https://github.com/buildkite/elastic-ci-stack-for-aws/issues/1311 raised by [Gezi-lzq](https://github.com/Gezi-lzq)
@patrobinson and I have:
A big thank you to [Gezi-lzq](https://github.com/Gezi-lzq) for raising and your contribution! We really appreciate it :) was easier to open up this branch to get it merged. 
> ## Describe the bug
> The SSH key generated by Packer for provisioning is not being completely removed from the authorized_keys file. This issue was believed to have been addressed in Issue #544 but persists due to the key's presence in the root account's authorized_keys, not just the ec2-user. This incomplete removal contravenes the security policies intended for …
> Test/verify OS PR to Elastic Stack - clearing SSH keys

- packer/linux/scripts/install-docker.sh
[Docker buildx](https://github.com/docker/buildx) v0.14.0 has been released!
Upgrade buildx from 0.13.0 to 0.14.0
See the [buildx release notes](https://github.com/docker/buildx/releases) for details of the changes:
- [v0.14.0 release notes](https://github.com/docker/buildx/releases/tag/v0.14.0)
- [v0.13.1 release notes](https://github.com/docker/buildx/releases/tag/v0.13.1)
> Bump Docker buildx to v0.14.0 and Docker Compose to v2.27.0

- packer/windows/conf/buildkite-agent/scripts/terminate-instance.ps1
Steps to reproduce:
- Create a windows stack
- Set`ScaleInIdlePeriod` to some number greater than 0 (I used 6 to speed up the feedback)
- Set `TerminateInstanceAfterJob` to false
- Set the MinSize to 1 (this step is necessary to ensure a call to `terminate-instance-in-auto-scaling-group` fails)
- Set the MaxSize to 1 (again prevent terminate instance succeeding)
- Ensure no jobs get assigned to the agent
Observed behaviour: After the ScaleInIdlePeriod the EC2 instance is running but the buildkite-agent is in the `SERVICE_STOPPED` state.
Expected behaviour: the EC2 instance is running and the buildkite-agent is in `SERVICE_STARTED` state.
This bug was likely introduced in https://github.com/buildkite/elastic-ci-stack-for-aws/commit/c3ebaa5c45995471e3035838e1ecfb68be493b1a
First it's …
> Fix windows agent not restarting

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.19.0...v6.20.0)
- Fix windows agent not restarting [#1318](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1318) (@patrobinson)
- Fix SSH key clearance in buildkite-ami.pkr.hcl [#1316](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1316) (@Gezi-lzq @123sarahj123)
- Bump Docker buildx to v0.14.0 and Docker Compose to v2.27.0 [#1317](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1317) (@orien)
> Update changelog for v6.20.0 release

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.20.0...v6.21.0)
- Bump agent version to 3.73.1 [#1323](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1323) [#1321](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1321) [#1320](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1320) (@DrJosh9000 + @moskyb)
> Update changelog for v6.21.0

- packer/linux/conf/bin/bk-configure-docker.sh
- templates/aws-stack.yml
Adds new `DockerNetworkingProtocol` Cloud Formation Parameter, for opting in to starting containers with both ipv4 and ipv6 addresses. This might be useful when running the elastic stack on dual stack and ipv6-only subnets.
Prior to this change, elastic stack instances could run on dual stack and ipv6-only VPC subnets and many things continue to work as normal. However, docker builds and containers did not - containers are started with private ipv4 addresses and no ipv6 addresses. Attempts to connect to global or VPC ipv6 addresses from inside a container fail. When this new parameter is set to `dualstack`, containers will be assigned an ipv6 address and depending on the configuration of the VPC it's running in, containers may be able to connect to the outside world over ipv6.
When the …
> Add new stack parameter for enabling dualstack docker [PLT-2325]

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
Per our [agent release doc](https://guide.buildkite.net/engineering/teams/pipelines/agent-release-process/index.html#update-the-elastic-ci-stack-agent-version).
> Upgrade agent to 3.74.0

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.21.0...v6.22.0)
* Add new stack parameter for enabling dualstack docker [PLT-2325] [#1306](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1306) (@yob)
* Upgrade agent to 3.74.0 [#1328](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1328) (@zhming0)
<details>
<summary>Full Agent Changelog </summary>
<p><a href="https://github.com/buildkite/agent/compare/v3.73.1...v3.74.0">Full Changelog</a></p>
<h5 id="security">Security</h5>
<ul>
<li>⚠️ When using <code>artifact download</code>, artifacts that were uploaded with paths containing <code>..</code> will no longer be able to traverse up from the destination path. This change is unlikely to break the vast majority of pipelines, however if …
> Update changelog for v6.22.0

- .buildkite/docker-compose.yml
- .github/dependabot.yml
- Makefile
- go.mod
- go.sum
The go.mod file is for the internal fix-perms tool, which has a very narrow focus and very few dependencies, but strictly speaking it does have dependencies that might need updating from time to time.
> Create dependabot.yml, update some Go things

- internal/fixperms/fdfs/fdfs.go
Calling fchownat on a file updates the file's ctime (metadata update time), even if uid and gid don't change.
Git uses ctime (along with other metadata) to determine if checked out files have been modified. If the ctime has changed, it rewrites the contents of the file during checkout.
This makes git checkouts in already cloned repos slower than they need to be:
```
[buildkite-agent@ip-10-0-1-159 linux]$ time git checkout -f 626737a5791b
HEAD is now at 626737a5791b Merge tag 'pinctrl-v6.10-2' of git://git.kernel.org/pub/scm/linux/kernel/git/linusw/linux-pinctrl
real    0m0.255s
user    0m0.130s
sys     0m0.235s
[buildkite-agent@ip-10-0-1-159 linux]$ /usr/bin/fix-buildkite-agent-builds-permissions buildkite-rian-i-0868df7f3b3f2c10d-1 rians-test-org linux
[buildkite-agent@ip-10-0-1-159 …
```
> Avoid chowning files with expected ownership

- docs/updating-agent.md
This page has been migrated into the Guide but still appears here, so I've added a breadcrumb to the new place.
> Fix 'Updating the Agent' page with link to guide.

- goss.yaml
- packer/linux/buildkite-ami.pkr.hcl
- packer/linux/scripts/install-buildkite-test-splitter.sh
We're trying to make it as easy to get started with using the test splitter client as possible.
This PR adds the current release (v0.7.2) to the packer build for linux (we're not currently building a windows version).
> First pass at adding test-splitter to the elastic-ci linux stack.

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
- templates/aws-stack.yml
- Bump agent version to [v3.75.1](https://github.com/buildkite/agent/releases/tag/v3.75.1)
- Bump scaler default version to [v1.8.0](https://github.com/buildkite/buildkite-agent-scaler/releases/tag/v1.8.0)
> Bump Agent and Scaler

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.22.2...v6.22.3)
- Bump Agent to v3.75.1 and Scaler to v1.8.0 [#1345](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1345) (@DrJosh9000)
> [!NOTE]
> Depending on how you upgrade existing stacks, you may not automatically be upgraded to v1.8.0 of Buildkite Agent Scaler. [A work around](https://github.com/buildkite/elastic-ci-stack-for-aws/issues/1172#issuecomment-1697304023) exists for this known issue.
<details>
<summary>Agent Changelog </summary>
[Full Changelog](https://github.com/buildkite/agent/compare/v3.75.0...v3.75.1)
- Fix downloaded artifact permissions [#2894](https://github.com/buildkite/agent/pull/2894) (@DrJosh9000)
</details>
> Bump changelog for v6.22.3

- packer/linux/scripts/install-buildkite-test-splitter.sh
Bump Test Splitter to v0.8.0
https://github.com/buildkite/test-splitter/releases/download/v0.8.0/test-splitter_0.8.0_linux_amd64
https://github.com/buildkite/test-splitter/releases/download/v0.8.0/test-splitter_0.8.0_linux_arm64
> Bump Test Splitter version to v0.8.0

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.22.3...v6.22.4)
- Bump agent to v3.76.2 [#1353](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1353), [#1351](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1351) (@DrJosh9000)
- Bump Test Splitter version to v0.8.0 [#1349](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1349) (@nprizal)
- Upgrade test-splitter-client to v0.7.3 [#1344](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1344) (@wooly)
<details>
<summary>Agent Changelog </summary>
[Full Changelog](https://github.com/buildkite/agent/compare/v3.76.1...v3.76.2)
> [!NOTE]
> v3.76.0 fixed an issue which caused the HTTP client in the agent to fall back to HTTP/1.1, see …
> Bump changelog for v6.22.4

- templates/aws-stack.yml
RootVolumeIops became configurable for gp3 in 6.14.0 - https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1283 this updates the cfn stack description to match
I also noticed that `RootVolumeIops` and `RootVolumeThroughput` are not mentioned at all on the website: https://buildkite.com/docs/agent/v3/elastic-ci-aws/parameters - but I don't think that page is directly controlled from this repo
> docs: update RootVolumeIops to include gp3

- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/windows/conf/bin/bk-install-elastic-stack.ps1
- templates/aws-stack.yml
This change adds the option to add a KMS key to the stack for signing and verifying of pipelines. Setting this to a keyspec will create the key and configure all agents to use this key.
> Add the option to create a KMS key for signing of pipelines

- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/windows/conf/bin/bk-install-elastic-stack.ps1
- templates/aws-stack.yml
This also fixes a misconfiguration on the windows agent. 
This setting is critical to rolling out signing as it is helpful during migration if you want to enable warn mode while updating pipelines.
> This setting determines the Buildkite agent's response when it receives a job without a proper signature, and also specifies how strictly the agent should enforce signature verification for incoming jobs. The agent will warn about missing or invalid signatures, but will still proceed to execute the job. If not explicitly specified, the default behavior is block, which prevents any job without a valid signature from running, ensuring a secure pipeline environment by default.
> Add signing verification behaviour and fix windows config option

- templates/aws-stack.yml
As it says in the title, this PR adds the `r8g` EC2 instance class to the logic that's used to determine if the current instance is ARM based.
> fix: Add `r8g` to the `UsingArmInstances` logic

- packer/linux/buildkite-ami.pkr.hcl
The new Amazon Linux AMI seems to have broken multi-platform docker image support.
```
[ec2-user@ip-172-31-57-192 ~]$ docker run --rm --platform linux/arm64/v8 -t arm64v8/ubuntu uname -m
exec /usr/bin/uname: exec format error
```
This pins the version for now
> Pin amazon linux ami

- templates/aws-stack.yml
This PR adds the [new EC2 `m8g`](https://aws.amazon.com/ec2/instance-types/m8g/) instances to the `UsingArmInstances` block.
> Add m8g instances to UsingArmInstances

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.28.0...v6.29.0)
- Add m8g instances to UsingArmInstances [#1381](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1381) (@wgrrrr)
- Bump agent to v3.83.0 [#1383](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1383) (@DrJosh9000)
- Bump golang.org/x/sys from 0.25.0 to 0.26.0 [#1382](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1382) (@dependabot[bot])
<details>
[Full Changelog](https://github.com/buildkite/agent/compare/v3.82.1...v3.83.0)
- Exit with code 94 if a mirror lock times out [#3023](https://github.com/buildkite/agent/pull/3023) (@DrJosh9000)
- Add support for oidc aws session tags …
> Bump changelog for v6.29.0

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.29.0...v6.29.1)
- Bump agent to v3.83.1 [#1385](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1385) (@DrJosh9000)
<details>
[Full Changelog](https://github.com/buildkite/agent/compare/v3.83.0...v3.83.1)
- Fix artifact up/download timeouts [#3033](https://github.com/buildkite/agent/pull/3033) (@DrJosh9000)
</details>
> Bump changelog for v6.29.1

- packer/linux/buildkite-ami.pkr.hcl
- packer/linux/scripts/install-session-manager-plugin.sh
This was removed in the migration to Amazon Linux 3 with the [belief that there was no use case for the Session Manager Plugin being present on the agent](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1122#discussion_r1220593363). It has since been realised that it is quite useful. For example, the agent may be used to start ECS Tasks which perform work in other environments/network configurations (such as Database migrations during deployments).
The install script was first restored (`git checkout 2d32dfcc211b268e903a742de87bb27070c53cb7^ -- packer/linux/scripts/install-session-manager-plugin.sh`), then modified slightly per [AWS documentation for Amazon Linux 3](https://docs.aws.amazon.com/systems-manager/latest/userguide/install-plugin-linux.html).
> Restore SSM Session Manager Plugin

- templates/aws-stack.yml
These new instance types https://aws.amazon.com/ec2/instance-types/c8g/ ought to be recognised as ARM64 workers.
> Add support for c8g instances.

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.29.1...v6.30.0)
- Add support for c8g instances. [#1392](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1392) (@toothbrush)
- Restore SSM Session Manager Plugin [#1389](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1389) (@ellsclytn)
- Bump agent to v3.84.0 [#1393](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1393) (@DrJosh9000)
- fix: update goss to be more explicit with platform in docker tests [#1390](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1390) (@wolfeidau)
<details>
[Full Changelog](https://github.com/buildkite/agent/compare/v3.83.1...v3.84.0)
- Add command for canceling a running a build …
> Bump changelog for v6.30.0

- templates/aws-stack.yml
tldr; customer requested an increase in the pool of InstanceTypes beyond 4 instances due to issues around frequent spot interruptions in our BK ASG
coda: https://coda.io/d/_dHnUHNps1YO#Escalations-Pipelines_tuQbCBf6/r812&view=center
The Customer has created an issue on the repo https://github.com/buildkite/elastic-ci-stack-for-aws/issues/1395
The summary of the issue is that they want broader selection of instance types for spot instances. And they are raising this as this has become a pain point for them recently and would like us to resolve this and take it up
> PS-195 increase the instance_types from 4 to 10

- packer/linux/scripts/install-docker.sh
- Upgrade buildx from 0.15.0 to 0.18.0
- Upgrade Docker Compose from 2.27.0 to 2.30.3
See the [buildx](https://github.com/docker/buildx/releases) and [compose](https://github.com/docker/compose/releases) release notes for details of the changes:
> Bump Docker buildx to v0.18.0 and Docker Compose to v2.30.3

- Makefile
- goss.yaml
- packer/linux/buildkite-ami.pkr.hcl
- packer/linux/conf/bin/bk-configure-docker.sh
- packer/linux/conf/docker/systemd/docker-binfmt.service
- packer/linux/scripts/cleanup.sh
- packer/linux/scripts/install-docker.sh
The AMI version we had pinned due to issues with multiarchecture docker builds failing was removed from list of public AMIs.
```bash
$ aws ec2 describe-images --filters 'Name=name,Values=al2023-ami-minimal-2023.5.20240903.0-*'
{
"Images": []
}
```
This paired with a few changes which broke our packer build I have made a few changes:
1. Because we run update during the packer build, and a couple of the updates were 400Mb+ and filled up our 2Gb default ebs volume.
2. Added a command to cleanup downloads and cache files from dnf to keep the image lean after these upgrades...
3. Changes in systemd now remove cleanup binfmt_misc on restart https://github.com/systemd/systemd/issues/13129 so we need to add a `docker-binfmt.service` which runs at startup to support multiarchecture docker builds. …
> Update packer and the AMI with some fixes for binfmt

- packer/linux/scripts/install-docker.sh
- Upgrade buildx from 0.18.0 to 0.19.2
- Upgrade Docker Compose from 2.30.3 to 2.31.0
See the [buildx](https://github.com/docker/buildx/releases) and [compose](https://github.com/docker/compose/releases) release notes for details of the changes:
> Bump Docker buildx to v0.19.2 and Docker Compose to v2.31.0

- .buildkite/steps/cleanup.sh
We create three CloudFormation Stacks on each build of the elastic stack, confirming instances boot and work as expected. There are specific steps in the build that attempt to delete all resources created for those tests, but from time to time they can fail.
This cleanup step runs at the end of the build and will delete any resources this pipeline might've left behind, regardless of whether they were created in this specific build or not.
I noticed that the AWS Account these test stacks were created in had many old S3 buckets like this:
* buildkite-aws-stack-test--managedsecretsloggingbuc-XXXXXXXXX
These are the logging buckets created by test stacks to holds access logs for the matching secrets S3 bucket. We attempt to delete them in `.buildkite/steps/delete.sh`, but some slip through …
> Try harder to delete test S3 logging buckets created during CI

- packer/linux/scripts/install-buildkite-utils.sh
- packer/windows/scripts/install-s3secrets-helper.ps1
Updates https://github.com/buildkite/elastic-ci-stack-s3-secrets-hooks to the latest release. There are no functional changes in this release, it's all maintenance:
* update golang from 1.16 to 1.23
* update various gomods, like the AWS SDK
I followed the docs in https://github.com/buildkite/elastic-ci-stack-for-aws/blob/main/docs/updating-secrets.md to make this PR
> Update bk/elastic-ci-stack-s3-secrets-hooks to v2.2.0

- .buildkite/steps/publish.sh
We recently changed the S3 bucket that holds public CloudFormation templates for the elastic stack from old fashioned ACLs to new fashioned Bucket Owner with Bucket Resource Policy that grants public read access.
Now, this script is failing with an error:
upload failed: build/mappings.yml to s3://buildkite-aws-stack/secrets-2-2-0/mappings.yml An error occurred (AccessControlListNotSupported) when calling the PutObject operation: The bucket does not allow ACLs
I think removing the --acl flag from our publish command should fix that.
> stop setting ACLs when publishing templates to S3

- .buildkite/pipeline.yaml
Currently we rely on the instance role to have the permissions to create, test and destroy cloud formation stacks during our integration tests.
This proposes moving to a specific OIDC assumable IAM role instead, which is our current preferred pattern.
> Assume an IAM role via OIDC when running integration tests

- .buildkite/docker-compose.yml
- .buildkite/pipeline.cleanamis.yaml
- .buildkite/steps/clean-old-amis
- .buildkite/steps/copy.sh
We've been publishing AMIs to 20 regions for ~6 years, and we've built quite a collection.
Many of them we want to keep indefinitely, like any that we've published in a released Cloud Formation template on [1]. Or any that were published in the last 12 months.
However, there's many many other images that it's safe to garbage collect. For example, we publish AMIs to every region for every main branch build, so we and customers can test them. They're useful for a short time, but any older than 12 months we can remove. By that time, customers have the option to move to a formal release with the features they want.
[1] https://github.com/buildkite/elastic-ci-stack-for-aws/releases
> New pipeline: deregister old AMIs

- .buildkite/pipeline.cleanamis.yaml
- .buildkite/steps/copy.sh
All regions we publish the elastic stack to, anyway. There's 20 - any region launched in the last few years and not requested by a customer currently has no AMIs published to it.
The pipeline is still in dry run mode, so this will have no actual impact on AMIs. The IAM role also lacks permission to actually delete anything yet.
This will give logs of every region that I can examine and spot check for correctness though.
> Expand the AMI cleaning pipeline to all regions

- .buildkite/pipeline.cleanamis.yaml
I've run some test builds in dry mode, and spot checked the job logs for multiple regions. Everything I checked looked as expected:
* all regions show elastic stack AMIs tagged with a version are left untouched
* all regions show only elastic stack AMIs in the list
* all regions cap the deletions at only 10 images (for now)
This will require expanding the IAM role to permit deregistering images and deleting snapshots.
I propose leaving the 10-image cap for now. In the unlikely event of a mistake, this will limit the blast radius of deregistered images. We can increase the number once we build confidence.
> remove DRY_RUN flag from AMI cleaning script

- .buildkite/steps/clean-old-amis
I started with 10 while I was building the pipeline, mainly to limit the blast radius if I accidentally deregistered the wrong images.
The pipeline is now up and running and I've manually run it a few times. It's working just as planned, and only un-versioned images created more than a year ago are being deregistered.
I'm confident we can increase this to a higher number now. Looking at the logs for some regions, I can see most have 900-1200 images in them. Once this chance merges, I'll do a couple of manually runs to cut those numbers down by a few hundred, then we can rely on the weekly scheduled build to keep the number down over time.
> Increase AMI garbage collection to 100 images per run

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
[Full Changelog](https://github.com/buildkite/agent/compare/v3.88.0...v3.89.0)
- Adding support for Additional Hooks Paths [#3124](https://github.com/buildkite/agent/pull/3124) (@CerealBoy)
- Bump the container-images group across 5 directories with 2 updates [#3143](https://github.com/buildkite/agent/pull/3143) (@dependabot[bot])
- Update golang.org/x/net [#3140](https://github.com/buildkite/agent/pull/3140) (@yob)
> Bump agent to v3.89.0

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/v6.32.0...v6.33.0)
- This adds an optional override for agent API endpoint [#1428](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1428) (@wolfeidau)
- Bump agent to v3.89.0 [#1427](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1427) (@CerealBoy)
- Bump golang.org/x/sys from 0.28.0 to 0.29.0 [#1426](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1426) (@dependabot[bot])
<details>
[Full Changelog](https://github.com/buildkite/agent/compare/v3.88.0...v3.89.0)
- Adding support for Additional Hooks Paths [#3124](https://github.com/buildkite/agent/pull/3124) (@CerealBoy)
- Bump the container-images group across 5 directories with 2 …
> Bump changelog for v6.33.0

- templates/aws-stack.yml
Adds EBS volume tags for `Name` and `BuildkiteQueue` that match the attached instance name, while also keeping optional cost allocation tags.
> Add EBS volume tag for BK queue, keep optional cost allocation tags

- .github/workflows/linear_issue_open.yml
This adds a GitHub workflow to sync Issue/PR opens to Linear so that we can manage those more easily.
Secrets are in the repo already for API calls.
> 🔨 Add GitHub action for Linear sync

- goss.yaml
We've seen builds where the order of installs from the `install-utils` script can impact the `gid` of the `docker` group, but we specify that `docker` must be in `993` in our GOSS test
https://github.com/buildkite/elastic-ci-stack-for-aws/blob/9965c106699eb60d938f81c813e81b9456b6a181/goss.yaml#L104
The install order in our instance [build](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/9965c106699eb60d938f81c813e81b9456b6a181/packer/linux/buildkite-ami.pkr.hcl#L84) can determine the GIDs that packages get; `install-utils` runs first, so `993` may be taken by the time we install Docker.
We allow the `docker` group to have a GID between `990` and `995`, inclusive. We could expand this, but it _feels_ like a fine range to start with given we aren't aiming to add lots of packages.
> ➖ Docker can be a range of GIDs

- templates/aws-stack.yml
> [!WARNING]  
> This release will force an upgrade of the agent scaler by checking the version is 1.9.1 or higher. This is required so we can introduce a new parameter to the agent scaler to pass through agent endpoint.
This is an go based test which shows the regex works as intended, maybe helpful in the future.
```go
package semver
import (
"regexp"
"testing"
)
func isGreaterThan190(version string) bool {
pattern := `^(?:(?:[2-9]|[1-9]\d+)\.\d+\.\d+|1\.(?:[1-9]\d+\.\d+|9\.[1-9]\d*))$`
matched, _ := regexp.MatchString(pattern, version)
return matched
}
func TestVersionValidation(t *testing.T) {
tests := []struct {
name        string
version     string
want        bool
description string
}{
{
name:        "equal_to_boundary",
version:     "1.9.0",
want:        false,
description: "Equal …
```
> Upgrade the agent scaler which introduces a new agent endpoint param

- packer/linux/conf/buildkite-agent/systemd/buildkite-agent.service
The PATH configured in `buildkite-agent.service` is inherited by all jobs executed by Buildkite.
Normally, a binary installed to `/usr/local/bin` would take precedence over similarly named files in `/usr/bin` or `/bin`. This commit restores that expectation allowing an administrator to replace a binary by installing a replacement into `/usr/local/bin`.
There is no entry for `/bin` because al2023 symlinks `/usr/bin` to `/bin`. A specific entry for `/bin` is unnecessary.
Finally, `/usr/local/sbin` and `/usr/sbin` have been removed because as the buildkite-agent is a regular user, it should not have the required permissions to use those binaries.
> Fix PATH used by jobs

- templates/aws-stack.yml
_(this is yet another approach to #1422 and #1424 - pick the one you prefer 😅)_
We have a use case where we want to have a single KMS key that Buildkite agents in multiple accounts can use to sign and verify pipeline steps. By letting the user specify the whole key ARN rather than just the key ID, the user is free to use a key wherever they want.
This third attempt has a different set of tradeoffs to the previous two:
* non-breaking change - this template will accept the same parameter as before, but the user can provide either the Key ID part or the full ARN, better than #1422's breaking change
* slightly less complex conditional and one less parameter - having to check that either-or Key ID or ARN are provided made #1424 a bit unwieldy
> Let user provide full KMS Key ARN and update descriptions

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
[Full Changelog](https://github.com/buildkite/agent/compare/v3.90.0...v3.91.0)
- Jitter within ping, status, log loops [#3164](https://github.com/buildkite/agent/pull/3164) (@DrJosh9000)
- Roko v1.3.1 [#3157](https://github.com/buildkite/agent/pull/3157) (@moskyb)
- Better plugin checkout logging [#3166](https://github.com/buildkite/agent/pull/3166) (@DrJosh9000)
- Add /.buildkite dir for Dockerfile updates [#3162](https://github.com/buildkite/agent/pull/3162) (@DrJosh9000)
<details>
<summary><h3>Dependency bumps</h3></summary>
- Bump the cloud-providers group with 6 updates [#3167](https://github.com/buildkite/agent/pull/3167) (@dependabot[bot])
- Bump gopkg.in/DataDog/dd-trace-go.v1 from 1.70.3 to 1.71.0 [#3168](https://github.com/buildkite/agent/pull/3168) (@dependabot[bot])
- Bump the …
> bump agent version to v3.91.0

- packer/linux/buildkite-ami.pkr.hcl
- packer/windows/buildkite-ami.pkr.hcl
Overriding the defaults set by packer with the goal of providing better performance for instances launched using this AMI by ensuring we use GP3 volumes by default.
> **launch_block_device_mappings** - Add one or more block devices before the Packer build starts. If you add instance store volumes or EBS volumes in addition to the root device volume, the created AMI will contain block device mapping information for those volumes.
https://developer.hashicorp.com/packer/integrations/hashicorp/amazon/latest/components/builder/ebs
https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-plan-storage-compare-volume-types.html
> Tidy up hcl whitespace and upgrade windows to use gp3 for more iops

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
bump agent version to the latest v3.94.0, which is released today https://github.com/buildkite/agent/pull/3234
> bump agent version to v3.94.0

- packer/linux/conf/bin/bk-fetch.sh
To enable migration of configuration from s3 to AWS SSM parameter store, this change introduces the option to provide a path which is exported to an env file via https://github.com/buildkite/elastic-ci-stack-for-aws/blob/main/packer/linux/conf/bin/bk-install-elastic-stack.sh#L301
The path is prefixed with `ssm:` to align with the current structure, note isn't a proper URL as using one would be confusing when the convention for SSM parameter store is to start the path with a `/`.
This is used in the agents systemd service https://github.com/buildkite/elastic-ci-stack-for-aws/blob/main/packer/linux/conf/buildkite-agent/systemd/buildkite-agent.service#L15.
As an example we have the configuration for open telemetry in parameter store `ssm:/config/elastic-stack-otel/buildkite_tracing_backend` …
> Add the option to recursively copy ssm parameters to an env file

- .buildkite/docker-compose.yml
- Makefile
- go.mod
- Bumps the base `go` version in `go.mod` to `1.23`
- Increments the same in the Makefile
- Uses `golang:1.23` in the fixperms tests image in the `compose` file
- TIL that `-alpine` versions don't have `/usr/bin/cp` installed
> Bump Go to 1.23

- templates/aws-stack.yml
- Adds a `BuildkiteAgentSignalGracePeriod` parameter which sets `BUILDKITE_SIGNAL_GRACE_PERIOD_SECONDS`
- Default is set to be `-1` as per the current implementation
Closes https://github.com/buildkite/elastic-ci-stack-for-aws/issues/1459
> Add a param for signal grace period

- Makefile
- go.mod
- update `go` version to `1.23.6`, according to https://go.dev/doc/devel/release#go1.23.0 only fixes have been implented
> chore: go to 1.23.6 (just fixes)

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
Buildkite Agent bumped to [v3.97.0](https://github.com/buildkite/agent/releases/tag/v3.97.0), previously [v3.94.0](https://github.com/buildkite/agent/releases/tag/v3.94.0).
Highlights from [CHANGELOG](https://github.com/buildkite/agent/blob/v3.97.0/CHANGELOG.md):
- Add pause and resume subcommands [#3273](https://github.com/buildkite/agent/pull/3273) (@DrJosh9000)
- Redact meta-data values and step attribute updates with warnings [#3243](https://github.com/buildkite/agent/pull/3243) (@DrJosh9000)
- Redact annotations [#3242](https://github.com/buildkite/agent/pull/3242) (@DrJosh9000)
- ANSI parser speedup [#3237](https://github.com/buildkite/agent/pull/3237) (@DrJosh9000)
Full [CHANGELOG](https://github.com/buildkite/agent/blob/v3.97.0/CHANGELOG.md) for this version range:
> ## …
> Buildkite Agent v3.97.0, was v3.94.0

- CHANGELOG.md
Preparing for v6.37.0 release…
> ### Added
> * Option to recursively copy AWS SSM parameters to an env file by @wolfeidau in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1455
> * More instance types by @ivannalisetska in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1465
> * `BuildkiteAgentSignalGracePeriod` parameter by @mcncl in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1468
> 
> ### Changed
> * Buildkite Agent v3.97.0, was v3.93.1 by @pda & @PriyaSudip in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1473 & https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1453
> * Go 1.23 by @mcncl in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1467
>   * Go 1.23.6 (just fixes) by @mcncl in …
> CHANGELOG for v6.37.0

- packer/linux/scripts/install-docker.sh
- Upgrade buildx from 0.19.2 to 0.23.0
- Upgrade Docker Compose from 2.31.0 to 2.35.1
See the [buildx](https://github.com/docker/buildx/releases) and [compose](https://github.com/docker/compose/releases) release notes for details of the changes:
> Bump Docker buildx to v0.23.0 and Docker Compose to v2.35.1

- templates/aws-stack.yml
The documentation of parameters available for use with the AWS elastic stack lists the wrong username for SSH access to agents - it should be `ec2-user` rather than `ec2_user.` Just correcting this.
> Fix incorrect username in SSH access doc

- README.md
Due to a little restructuring of the official Elastic CI Stack for AWS-related content in the Buildkite Docs, this PR amends a few of the links to the relevant docs pages in the README of this repo.
> Amend recommendations links.

- packer/linux/scripts/install-buildkite-agent.sh
- packer/windows/scripts/install-buildkite-agent.ps1
Updates the agent version to [v3.98.1](https://github.com/buildkite/agent/releases/tag/v3.98.1), was [v3.97.0](https://github.com/buildkite/agent/releases/tag/v3.97.0)
> [v3.98.1](https://github.com/buildkite/agent/tree/v3.98.1) (2025-06-04)
[Full Changelog](https://github.com/buildkite/agent/compare/v3.98.0...v3.98.1)
Fixed
Gracefully Handle Missing GitHub PR refs/pull/%s/head in Checkout https://github.com/buildkite/agent/pull/3294 (@123sarahj123)
Fix bootstrap subprocess handling https://github.com/buildkite/agent/pull/3331 (@DrJosh9000)
Reduce git fetch from twice to once for typical Github PR build https://github.com/buildkite/agent/pull/3327 (@zhming0)
Set job log tempfile permissions to 644 (was 600) https://github.com/buildkite/agent/pull/3330 (@moskyb)
Internal
Tag tests with os …
> Bump Agent v3.97.0 -> v3.98.1

- README.md
Renames and re-links a handful of links that are currently outdated after an update to the Agent/Running on AWS section in the Docs.
> Update EC2 README after AWS section change in Docs

- README.md
I clicked on this badge expecting it to take me to the pipeline. Instead it selected the text in the SVG 😅  
For folks without access this will 404, but that seems fine to me. Eventually I think we'd like to make the pipeline public, so this problem will eventually solve itself.
> Add link from build badge in README

- README.md
- packer/linux/conf/bin/bk-install-elastic-stack.sh
- templates/aws-stack.yml
Introduce configurable [systemd resource limits](https://www.freedesktop.org/software/systemd/man/latest/systemd.resource-control.html) for the Buildkite agent to prevent resource exhaustion. The implementation allows control over CPU, memory, and I/O limits through CloudFormation parameters.
* Add `ExperimentalEnableResourceLimits` parameter to toggle resource limits
* Add configurable parameters for memory, CPU, and I/O limits with sensible defaults
* Add systemd slice and drop-in configuration in `bk-install-elastic-stack.sh`
Resource limits can be configured using these CloudFormation parameters:
`ResourceLimitsMemoryHigh`: MemoryHigh limit (default: 90%)
`ResourceLimitsMemoryMax`: MemoryMax limit (default: 90%)
`ResourceLimitsMemorySwapMax`: MemorySwapMax limit (default: 90%) …
> feat: pave road to resource limit control

- templates/aws-stack.yml
This fixes issue with missing parameters like `ExperimentalEnableResourceLimits` in https://buildkite.com/docs/agent/v3/aws/elastic-ci-stack/ec2-linux-and-windows/template-parameters Add rest of missing params
> fix: add new parameters to labeled sections

- CHANGELOG.md
- Update agent to v3.101.0 [#1499](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1499) ([scadu](https://github.com/scadu))
<details>
[Full Changelog](https://github.com/buildkite/agent/compare/v3.100.1...v3.101.0)
- Add support for http/protobuf transport for OTLP [#3366](https://github.com/buildkite/agent/pull/3366) (@catkins)
- Tweak apply-if-changed flag and usage string [#3367](https://github.com/buildkite/agent/pull/3367) (@DrJosh9000)
- Gather changed files list once [#3368](https://github.com/buildkite/agent/pull/3368) (@DrJosh9000)
- if_changed fixes: support older Git versions, adhere to skip string limit [#3372](https://github.com/buildkite/agent/pull/3372) (@DrJosh9000)
- Self-execute the path from os.Executable in more …
> Release v6.40.6

- templates/aws-stack.yml
Add a way to control the number of idle instances: https://github.com/buildkite/buildkite-agent-scaler/blob/61bab8e9318432ca0f89aa1c0dcbd80b8ec1d543/template.yaml#L57C1-L60C17
I guess documentation needs to be adjusted, unless autogenerated.
> Add support for InstanceBuffer

- renovate.json
Track buildkite-agent releases.
Also, define monthly schedule for updates, except for the agent which will receive updates as soon as possible.
> Renovate: add config for buildkite-agent

- .buildkite/scripts/generate-changelog.sh
Automate generating CHANGELOG.md with automatically fetching agent’s release notes.
Required tools: ghch
Sample usage: 
```
GITHUB_TOKEN=$(op read "op://MyGitHub/token") bash .buildkite/scripts/generate-changelog.sh v6.40.7
```
`op read` comes from 1Password CLI. See https://developer.1password.com/docs/cli/reference/commands/read/.
> Add script for generating changelog

- .buildkite/pipeline.cleanamis.yaml
- .buildkite/pipeline.yaml
Roll out using session tags for OIDC assumable IAM role trust policy.
Follow on from the work to support session tags in https://github.com/buildkite-plugins/aws-assume-role-with-web-identity-buildkite-plugin/pull/18
Requires matching update to the IAM role in PR: https://github.com/buildkite/aws-buildkite-dist/pull/130  to be shipped first
> Update to use OIDC session tokens on AWS role assumption

- packer/linux/conf/bin/bk-install-elastic-stack.sh
- templates/aws-stack.yml
We've added `signal-grace-period-seconds` to the CloudFormation in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1468, but it wasn't referenced in the configuration file's template.
Also, change default value to `-1`, aligning with [agent's defaults](https://buildkite.com/docs/agent/v3/cli-bootstrap#signal-grace-period-seconds).
Fixes #1530
> Fix agent's signal-grace-period-seconds

- README.md
- config.json.example
Removed the optional parameters `KeyName` and `ImageId` to ensure portability
> SUP-4081 - Update config.json.example for installing Elastic CI stack with the AWS CLI

- packer/linux/conf/bin/bk-configure-docker.sh
- templates/aws-stack.yml
Make the Docker default address pools configurable parameters. This will allow users the ability to change the CIDRs if these addresses conflict with the VPC IP range the Elastic CI Stack has been deployed to.
Fixes: https://github.com/buildkite/elastic-ci-stack-for-aws/issues/1512
> Allow Docker default address pools to be changed

- .gitmodules
Bumping version to v2.5.0 in order to enable the functionality of full secret redaction
Implements batch redaction of secrets using buildkite-agent's redactor command. Features JSON batching for v3.66.0+ and warns to upgrade for redaction on lower versions.
Fixes #1471
> Bumping S3 Secrets plugin to v2.5.0

- packer/linux/conf/bin/bk-install-elastic-stack.sh
- packer/windows/conf/bin/bk-install-elastic-stack.ps1
- templates/aws-stack.yml
Inspired by https://github.com/buildkite/elastic-ci-stack-for-aws/pull/839
Fixes https://github.com/buildkite/elastic-ci-stack-for-aws/issues/1012
* This adds the newly released agent config [`disconnect-after-uptime`](https://buildkite.com/docs/agent/v3/cli-start#disconnect-after-uptime), present in release [`v3.102.0`](https://github.com/buildkite/agent/releases/tag/v3.102.0).
* This allows a max lifetime for agents to be configured.
* Any running jobs will be completed and the agent will then shut down.
* When the `buildkite-agent` service is stopped, its EC2 instance will also be terminated.
> Implement new agent disconnect-after-uptime config

- templates/aws-stack.yml
* Allows up to 5 comma-separated (`key=value`) tags to be defined for the IAM Role used by the EC2 instances.
* Adds `CreatedBy=buildkite-elastic-ci-stack` Tag to the IAM Role to work around a zero to many edge case for user-defined tags.
Fixes https://github.com/buildkite/elastic-ci-stack-for-aws/issues/1441
> Allow up to 5 tags to be defined on the EC2 instance role

- .buildkite/pipeline.yaml
- packer/linux/scripts/install-utils.sh
- packer/windows/scripts/install-utils.ps1
Updates the Windows AMI to use AWS CLI v2. Successfully tested building, pushing and pulling Docker images to/from private ECR repo with `ecr` plugin (`v2.9.1`) to perform the necessary `aws ecr get-login-password` and the `docker-compose` plugin (`v5.10.0`) from Elastic CI Stack agents using a Windows AMI built with these changes.
Pipeline changes from adjacent [PR](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1557) included here to facilitate testing of this Windows AMI.
Fixes https://github.com/buildkite/elastic-ci-stack-for-aws/issues/1304 https://github.com/buildkite/elastic-ci-stack-for-aws/issues/843
Relates to https://github.com/buildkite/elastic-ci-stack-for-aws/pull/670 https://github.com/buildkite-plugins/ecr-buildkite-plugin/issues/37
> AWS CLI v2 in Windows AMI

- templates/aws-stack.yml
Inspired by https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1270
Adds the necessary [permissions](https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache-private.html#pull-through-cache-private-permissions) in order to allow the IAM Role to [use](https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache-working-pulling.html) an __existing__ ECR Private Registry as a [pull through cache](https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache.html).
> Implement IAM permissions required to use ECR Private Registry as pull through cache

- packer/linux/scripts/install-utils.sh
Fixes https://github.com/buildkite/elastic-ci-stack-for-aws/issues/1402
Upgrades `gnupg2-minimal` to `gnupg2-full`.
> Upgrade gpg in AL2023 to full install

- packer/linux/scripts/install-docker.sh
- packer/windows/scripts/install-docker.ps1
Partially implements https://github.com/buildkite/elastic-ci-stack-for-aws/pull/763
* Installs the [AWS ECR Credential Helper](https://github.com/awslabs/amazon-ecr-credential-helper) for both Linux and Windows. To be used in the future by the ECR plugin (pending [PR](https://github.com/buildkite-plugins/ecr-buildkite-plugin/pull/118))
* To be implemented with `export BUILDKITE_PLUGIN_ECR_CREDENTIAL_HELPER=true` in the agent `environment` hooks for both [Linux](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/1b98a2d27f2ee29a87791bf58d618c119baf48af/packer/linux/conf/buildkite-agent/hooks/environment#L109C51-L125) and [Windows](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/1b98a2d27f2ee29a87791bf58d618c119baf48af/packer/windows/conf/buildkite-agent/hooks/environment# …
> Install AWS ECR Credential Helper

- .buildkite/steps/packer.sh
- packer/linux/.trigger-base-build
- packer/windows/.trigger-base-build
In https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1593 we aimed to simplify base AMI build logic, however we did miss fetching the base AMI ID from S3.
This is needed when base AMI is not rebuild within the same pipeline build, so it's not available in the meta-data.
> Fix: base AMI lookup

- .buildkite/pipeline.yaml
Remove `if_changed` conditional for the base image as we hit a Catch 22 now for base AMI ID detection.
To be reverted once base AMI ID reference is published to S3.
> Temporarily remove build conditional for base AMI

- packer/linux/base/base.pkr.hcl
After merging
https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1597, goss test started failing with missing refresh_authorized_keys.timer.
Looking closer, it looks like Packer overrides `/tmp/conf` directory with content of `../shared/conf`.
___
Verifying base AMI built with this change, we got the timer back:
```
systemctl status refresh_authorized_keys.timer
○ refresh_authorized_keys.timer - Download ssh authorized_keys file from s3
Loaded: loaded (/etc/systemd/system/refresh_authorized_keys.timer; disabled; preset: disabled)
Active: inactive (dead)
Trigger: n/a
Triggers: ● refresh_authorized_keys.service
```
> Fix missing refresh_authorized_keys.timer

- packer/linux/stack/conf/bin/bk-configure-docker.sh
- templates/aws-stack.yml
Allows users to configure the default bridge network (`docker0`) for both IPv4 and IPv6.
Adds parameters:
- `DockerFixedCidrV4` (default: `""`)
- Since we are setting `DockerIPv4AddressPool1`, Docker uses the first subnet from the first pool for `docker0`
- **NOTE:** Must be configured as a subset of the first pool in `DockerIPv4AddressPool1` or the Docker daemon will fail to start with `network does not contain specified subnet`
- `DockerFixedCidrV6` (default: `2001:db8:1::/64`)
Fixes https://github.com/buildkite/elastic-ci-stack-for-aws/issues/512
> Allow configurable Docker default bridge networks
